export enum ErrorCode {
  // Auth
  AUTH_REQUIRED = 1001,
  AUTH_INVALID_TOKEN = 1002,
  AUTH_TOKEN_EXPIRED = 1003,
  AUTH_INVALID_CREDENTIALS = 1004,
  AUTH_INSUFFICIENT_PERMISSIONS = 1005,
  AUTH_ACCOUNT_DISABLED = 1006,
  AUTH_OTP_EXPIRED = 1007,
  AUTH_OTP_INVALID = 1008,

  // Validation
  VALIDATION_ERROR = 2001,
  VALIDATION_INVALID_FORMAT = 2002,
  VALIDATION_MISSING_FIELD = 2003,
  VALIDATION_INVALID_RANGE = 2004,

  // Resource
  RESOURCE_NOT_FOUND = 3001,
  RESOURCE_ALREADY_EXISTS = 3002,
  RESOURCE_CONFLICT = 3003,
  RESOURCE_LOCKED = 3004,

  // Ride
  RIDE_NOT_FOUND = 4001,
  RIDE_INVALID_STATUS = 4002,
  RIDE_ALREADY_CANCELLED = 4003,
  RIDE_NO_DRIVERS_AVAILABLE = 4004,
  RIDE_PRICE_MISMATCH = 4005,

  // Driver
  DRIVER_NOT_FOUND = 5001,
  DRIVER_NOT_AVAILABLE = 5002,
  DRIVER_OFFLINE = 5003,
  DRIVER_DOCUMENTS_PENDING = 5004,
  DRIVER_DOCUMENTS_REJECTED = 5005,

  // Payment
  PAYMENT_FAILED = 6001,
  PAYMENT_METHOD_INVALID = 6002,
  PAYMENT_INSUFFICIENT_FUNDS = 6003,
  PAYMENT_REFUND_FAILED = 6004,

  // Internal / infra
  INTERNAL_ERROR = 9001,
  SERVICE_UNAVAILABLE = 9002,
  RATE_LIMIT_EXCEEDED = 9003,
  EXTERNAL_SERVICE_ERROR = 9004,
  DATABASE_ERROR = 9005,
  DUPLICATE_RECORD = 9006,
}

export interface SpinrError {
  code: ErrorCode;
  message: string;
  message_key?: string;
  action_hint?: string;
  request_id?: string;
  timestamp?: string;
  details?: Record<string, unknown>;
}

export interface SpinrErrorResponse {
  success: false;
  error: SpinrError;
}
