"""Admin Compliance & Tax Reporting — regulatory/tax exports that aren't
covered by operational analytics (routes/admin/analytics.py) or the
fixed-format SGI forms (routes/admin/sgi_forms.py).

Every report generated here is:
  - Spinr-branded (backend/utils/report_branding.py), never a regulator's
    own fixed layout — fixed-format documents (SGI D00032/D00033, future
    equivalents) are generated by sgi_form_filler instead.
  - Logged to compliance_export_events (migration 263) for audit trail —
    who pulled which report, when, over what params.

Money arithmetic is Decimal-only per CLAUDE.md — never float.
"""

import csv
import io
import logging
from datetime import datetime, timedelta, timezone
from decimal import Decimal

from fastapi import APIRouter, Depends, HTTPException, Query, Response

try:
    from ... import db_supabase
    from ...dependencies import get_admin_user
    from ...utils import report_branding
except ImportError:
    import db_supabase
    from dependencies import get_admin_user
    from utils import report_branding

logger = logging.getLogger(__name__)
api_router = APIRouter(prefix="/compliance", tags=["Admin Compliance"])

_ALLOWED_FORMATS = ("pdf", "csv", "xlsx", "docx")


def _d(v) -> Decimal:
    if v in (None, ""):
        return Decimal("0")
    return Decimal(str(v))


def _parse_date_range(date_range: str) -> datetime:
    """Mirrors routes/admin/analytics.py's _parse_date_range shorthand."""
    now = datetime.now(timezone.utc)
    mapping = {
        "today": timedelta(days=1),
        "7d": timedelta(days=7),
        "30d": timedelta(days=30),
        "90d": timedelta(days=90),
        "1y": timedelta(days=365),
    }
    return now - mapping.get(date_range, timedelta(days=30))


async def _log_compliance_export(admin: dict, report_type: str, params: dict, row_count: int) -> None:
    """Best-effort write to the compliance_export_events audit table. A
    failure here must not block the admin from getting their report, but
    must surface loudly (CLAUDE.md: never silently swallow DB errors) —
    logged as an error, not a warning, so it's actionable."""
    try:
        await db_supabase.insert_one(
            "compliance_export_events",
            {
                "admin_user_id": admin.get("id") or admin.get("user_id"),
                "report_type": report_type,
                "params": params,
                "row_count": row_count,
            },
        )
    except Exception as e:
        logger.error(f"Failed to log compliance_export_events for {report_type}: {e}", exc_info=True)


# Known production tax_breakdown labels (services/fare_service.py /
# features.py's _apply_tax writes exactly these — "GST", "PST", "HST"; see
# features.py:939-945). Matched by exact label, not substring, so a future
# label like "GST/HST" or an unrelated fee containing "gst" can't silently
# shift money between buckets — it lands in `unrecognized` instead, which
# is surfaced as its own column rather than folded into GST/PST/HST.
_KNOWN_TAX_LABELS = ("GST", "PST", "QST", "HST")


async def _gst_pst_rows(start_date: datetime, end_date: datetime) -> tuple[list[dict], Decimal, Decimal, Decimal]:
    """Sum GST/PST/HST from completed rides' persisted tax_breakdown, grouped
    by calendar month. Reads what was actually charged (ride.tax_breakdown),
    the same field the rider receipt (utils/receipt_pdf.py) and email
    receipt (utils/email_receipt.py) render from — never recomputed."""
    rides = await db_supabase.get_rows(
        "rides",
        {
            "status": "completed",
            "ride_completed_at": {"$gte": start_date.isoformat(), "$lte": end_date.isoformat()},
        },
        columns="id,ride_completed_at,tax_breakdown,total_fare",
        limit=10000,
    )

    by_month: dict[str, dict[str, Decimal]] = {}
    gst_total = Decimal("0")
    pst_total = Decimal("0")
    hst_total = Decimal("0")
    for ride in rides:
        completed_at = ride.get("ride_completed_at") or ""
        month_key = completed_at[:7] if len(completed_at) >= 7 else "unknown"
        tax_breakdown = ride.get("tax_breakdown") or {}
        if not isinstance(tax_breakdown, dict):
            continue
        bucket = by_month.setdefault(
            month_key,
            {"GST": Decimal("0"), "PST": Decimal("0"), "HST": Decimal("0"), "unrecognized": Decimal("0")},
        )
        for label, payload in tax_breakdown.items():
            if not isinstance(payload, dict):
                continue
            amount = _d(payload.get("amount"))
            if amount == 0:
                continue
            label_upper = label.upper()
            if label_upper == "GST":
                bucket["GST"] += amount
                gst_total += amount
            elif label_upper in ("PST", "QST"):
                bucket["PST"] += amount
                pst_total += amount
            elif label_upper == "HST":
                bucket["HST"] += amount
                hst_total += amount
            else:
                # Not a known tax label — never silently fold an
                # unrecognized amount into GST/PST/HST (CLAUDE.md: don't
                # silently swallow errors that could misstate a filing).
                logger.error(
                    f"Unrecognized tax_breakdown label '{label}' on ride {ride.get('id')} "
                    f"— excluded from GST/PST/HST totals, reported separately as 'unrecognized'"
                )
                bucket["unrecognized"] += amount

    rows = [
        {
            "month": month,
            "gst": f"{v['GST']:.2f}",
            "pst": f"{v['PST']:.2f}",
            "hst": f"{v['HST']:.2f}",
            "unrecognized_tax": f"{v['unrecognized']:.2f}",
            "total_tax": f"{(v['GST'] + v['PST'] + v['HST'] + v['unrecognized']):.2f}",
        }
        for month, v in sorted(by_month.items())
    ]
    return rows, gst_total, pst_total, hst_total


@api_router.get("/gst-pst-remittance")
async def get_gst_pst_remittance(
    date_range: str = Query("30d", pattern="^(today|7d|30d|90d|1y)$"),
    format: str = Query("pdf", pattern="^(pdf|csv|xlsx|docx)$"),
    admin: dict = Depends(get_admin_user),
):
    """GST/PST tax remittance summary, grouped by month, over completed
    rides in the requested date range. Spinr-branded (never a fixed
    regulator format — CRA remittance filing has no prescribed layout,
    unlike SGI's forms)."""
    start_date = _parse_date_range(date_range)
    end_date = datetime.now(timezone.utc)

    try:
        rows, gst_total, pst_total, hst_total = await _gst_pst_rows(start_date, end_date)
    except Exception as e:
        logger.error(f"Failed to build GST/PST remittance summary: {e}", exc_info=True)
        raise HTTPException(status_code=503, detail="Compliance report data unavailable — database error") from e

    fieldnames = ["month", "gst", "pst", "hst", "unrecognized_tax", "total_tax"]
    subtitle = (
        f"{start_date.date().isoformat()} to {end_date.date().isoformat()} — "
        f"Total GST ${gst_total:.2f}, Total PST ${pst_total:.2f}, Total HST ${hst_total:.2f}"
    )

    await _log_compliance_export(
        admin,
        "gst_pst_remittance",
        {"date_range": date_range, "format": format, "start": start_date.isoformat(), "end": end_date.isoformat()},
        len(rows),
    )

    if format == "csv":
        buf = io.StringIO()
        writer = csv.DictWriter(buf, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
        return Response(
            content=buf.getvalue().encode("utf-8-sig"),
            media_type="text/csv",
            headers={"Content-Disposition": 'attachment; filename="gst_pst_remittance.csv"'},
        )

    if format == "xlsx":
        wb, ws = report_branding.new_branded_workbook("GST/PST Remittance Summary", subtitle)
        report_branding.write_branded_table(ws, fieldnames, rows)
        buf = io.BytesIO()
        wb.save(buf)
        return Response(
            content=buf.getvalue(),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": 'attachment; filename="gst_pst_remittance.xlsx"'},
        )

    if format == "docx":
        doc = report_branding.new_branded_document("GST/PST Remittance Summary", subtitle)
        report_branding.add_branded_table(doc, fieldnames, rows)
        buf = io.BytesIO()
        doc.save(buf)
        return Response(
            content=buf.getvalue(),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": 'attachment; filename="gst_pst_remittance.docx"'},
        )

    # default: pdf
    pdf = report_branding.new_branded_pdf("GST/PST Remittance Summary", subtitle)
    pdf.set_font(report_branding.BRAND_FONT, "B", 9)
    col_w = 45
    for name in fieldnames:
        pdf.cell(col_w, 8, name.replace("_", " ").title(), border=1)
    pdf.ln()
    pdf.set_font(report_branding.BRAND_FONT, "", 9)
    for row in rows:
        for name in fieldnames:
            pdf.cell(col_w, 7, str(row.get(name, "")), border=1)
        pdf.ln()
    return Response(
        content=bytes(pdf.output()),
        media_type="application/pdf",
        headers={"Content-Disposition": 'attachment; filename="gst_pst_remittance.pdf"'},
    )
