"""Admin Compliance & Tax Reporting — regulatory/tax exports that aren't
covered by operational analytics (routes/admin/analytics.py) or the
fixed-format SGI forms (routes/admin/sgi_forms.py).

Every report generated here is:
  - Spinr-branded (backend/utils/report_branding.py), never a regulator's
    own fixed layout — fixed-format documents (SGI D00032/D00033, future
    equivalents) are generated by sgi_form_filler instead.
  - Logged to compliance_export_events (migration 263) for audit trail —
    who pulled which report, when, over what params.

Money arithmetic is Decimal-only per CLAUDE.md — never float.
"""

import csv
import io
import logging
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request, Response
from fastapi.responses import JSONResponse

try:
    from ... import db_supabase
    from ...dependencies import get_admin_user
    from ...routes.drivers._shared import _decrypt_driver_pii, _ride_income
    from ...services import admin_export_approvals
    from ...services.stripe_kyc_sync import get_legal_name_and_address_from_stripe
    from ...settings_loader import get_app_settings
    from ...utils import metrics, report_branding
    from ...utils.email_provider import send_transactional_email
    from ...utils.rate_limiter import default_limiter as limiter
except ImportError:
    import db_supabase
    from dependencies import get_admin_user
    from routes.drivers._shared import _decrypt_driver_pii, _ride_income
    from services import admin_export_approvals  # type: ignore
    from services.stripe_kyc_sync import get_legal_name_and_address_from_stripe  # type: ignore
    from settings_loader import get_app_settings
    from utils import metrics, report_branding
    from utils.email_provider import send_transactional_email
    from utils.rate_limiter import default_limiter as limiter

logger = logging.getLogger(__name__)
api_router = APIRouter(prefix="/compliance", tags=["Admin Compliance"])


def _d(v) -> Decimal:
    if v in (None, ""):
        return Decimal("0")
    return Decimal(str(v))


def _parse_date_range(date_range: str) -> datetime:
    """Mirrors routes/admin/analytics.py's _parse_date_range shorthand."""
    now = datetime.now(timezone.utc)
    mapping = {
        "today": timedelta(days=1),
        "7d": timedelta(days=7),
        "30d": timedelta(days=30),
        "90d": timedelta(days=90),
        "1y": timedelta(days=365),
    }
    return now - mapping.get(date_range, timedelta(days=30))


def _capture_export_failure(report_type: str, error: Exception) -> None:
    """Explicit domain-tagged Sentry event for a compliance-export failure.
    Best-effort — never raises, no-op if SENTRY_DSN isn't configured. Same
    shape as services/data_transfer/observability.py's capture_failure."""
    try:
        import sentry_sdk  # type: ignore

        with sentry_sdk.push_scope() as scope:
            scope.set_tag("domain", "admin")
            scope.set_tag("surface", "backend")
            scope.set_tag("report_type", report_type)
            sentry_sdk.capture_exception(error)
    except Exception as sentry_err:
        logger.debug(f"compliance Sentry capture skipped: {sentry_err}")


async def _log_compliance_export(admin: dict, report_type: str, params: dict, row_count: int) -> None:
    """Best-effort write to the compliance_export_events audit table. A
    failure here must not block the admin from getting their report, but
    must surface loudly (CLAUDE.md: never silently swallow DB errors) —
    logged as an error, not a warning, so it's actionable."""
    try:
        await db_supabase.insert_one(
            "compliance_export_events",
            {
                "admin_user_id": admin.get("id") or admin.get("user_id"),
                "report_type": report_type,
                "params": params,
                "row_count": row_count,
            },
        )
    except Exception as e:
        logger.error(f"Failed to log compliance_export_events for {report_type}: {e}", exc_info=True)


# Known production tax_breakdown labels (services/fare_service.py /
# features.py's _apply_tax writes exactly these — "GST", "PST", "HST"; see
# features.py:939-945). Matched by exact label, not substring, so a future
# label like "GST/HST" or an unrelated fee containing "gst" can't silently
# shift money between buckets — it lands in `unrecognized` instead, which
# is surfaced as its own column rather than folded into GST/PST/HST.
_KNOWN_TAX_LABELS = ("GST", "PST", "QST", "HST")

# Applies to every source query in this module. A regulatory/tax export
# that silently drops rows past this cap would misstate the filing with no
# visible signal — _check_truncated() below turns that into a loud error
# log plus a visible "(TRUNCATED)" marker on the exported report instead.
_ROW_LIMIT = 10000


# AI-3's stated acceptance criterion (docs/threat-model/admin-panel.md;
# ACTION_ITEMS.md B10): "any export > 1,000 rows requires a second admin's
# approval." Dark-launched behind settings.dual_approval_exports_enabled
# (migration 268, default false) -- until an admin explicitly flips it on,
# _check_export_gate always returns None (ungated) and every report here
# behaves exactly as it did before this gate existed.
_APPROVAL_GATE_ROW_THRESHOLD = 1000

# CRA T4A (Box 048, "Fees for Services") reporting threshold — matches
# utils/t4a_annual_job.py's own _T4A_THRESHOLD constant (kept separate
# rather than imported: that module owns the annual push-notification
# job, a different concern from this admin-triggered export).
_T4A_THRESHOLD = Decimal("500.00")


async def _check_export_gate(
    admin: dict, route_key: str, gate_params: dict, row_count: int
) -> Optional[JSONResponse]:
    """Returns a 202 JSONResponse if this export needs (and doesn't yet
    have) a second admin's approval; returns None if the caller should
    proceed with generating the report as normal -- either the gate is
    off, the export is under threshold, or an approved grant exists (in
    which case it's consumed here, single-use)."""
    settings = await get_app_settings()
    if not settings.get("dual_approval_exports_enabled"):
        return None
    if row_count <= _APPROVAL_GATE_ROW_THRESHOLD:
        return None

    grant = await admin_export_approvals.find_approved_grant(
        requested_by=admin["id"], route_key=route_key, params=gate_params
    )
    if grant:
        await admin_export_approvals.consume(grant["id"])
        return None

    pending = await admin_export_approvals.find_pending_request(
        requested_by=admin["id"], route_key=route_key, params=gate_params
    )
    if not pending:
        pending = await admin_export_approvals.create_request(
            requested_by=admin["id"], route_key=route_key, params=gate_params, row_count=row_count
        )
    return JSONResponse(
        status_code=202,
        content={
            "approval_required": True,
            "request_id": pending["id"],
            "status": pending["status"],
            "row_count": row_count,
        },
    )


def _check_truncated(fetched_count: int, report_type: str) -> bool:
    if fetched_count < _ROW_LIMIT:
        return False
    logger.error(
        f"{report_type} export hit the {_ROW_LIMIT}-row fetch limit — report is truncated "
        f"and may misstate the true totals for the requested range. Narrow the date range "
        f"or add a driver_id filter to get a complete export."
    )
    return True


async def _gst_pst_rows(start_date: datetime, end_date: datetime) -> tuple[list[dict], Decimal, Decimal, Decimal, bool]:
    """Sum GST/PST/HST from completed rides' persisted tax_breakdown, grouped
    by calendar month. Reads what was actually charged (ride.tax_breakdown),
    the same field the rider receipt (utils/receipt_pdf.py) and email
    receipt (utils/email_receipt.py) render from — never recomputed."""
    rides = await db_supabase.get_rows(
        "rides",
        {
            "status": "completed",
            "ride_completed_at": {"$gte": start_date.isoformat(), "$lte": end_date.isoformat()},
        },
        columns="id,ride_completed_at,tax_breakdown,total_fare",
        limit=_ROW_LIMIT,
    )
    truncated = _check_truncated(len(rides), "gst_pst_remittance")

    by_month: dict[str, dict[str, Decimal]] = {}
    gst_total = Decimal("0")
    pst_total = Decimal("0")
    hst_total = Decimal("0")
    for ride in rides:
        completed_at = ride.get("ride_completed_at") or ""
        month_key = completed_at[:7] if len(completed_at) >= 7 else "unknown"
        tax_breakdown = ride.get("tax_breakdown") or {}
        if not isinstance(tax_breakdown, dict):
            continue
        bucket = by_month.setdefault(
            month_key,
            {"GST": Decimal("0"), "PST": Decimal("0"), "HST": Decimal("0"), "unrecognized": Decimal("0")},
        )
        for label, payload in tax_breakdown.items():
            if not isinstance(payload, dict):
                continue
            amount = _d(payload.get("amount"))
            if amount == 0:
                continue
            label_upper = label.upper()
            if label_upper == "GST":
                bucket["GST"] += amount
                gst_total += amount
            elif label_upper in ("PST", "QST"):
                bucket["PST"] += amount
                pst_total += amount
            elif label_upper == "HST":
                bucket["HST"] += amount
                hst_total += amount
            else:
                # Not a known tax label — never silently fold an
                # unrecognized amount into GST/PST/HST (CLAUDE.md: don't
                # silently swallow errors that could misstate a filing).
                logger.error(
                    f"Unrecognized tax_breakdown label '{label}' on ride {ride.get('id')} "
                    f"— excluded from GST/PST/HST totals, reported separately as 'unrecognized'"
                )
                bucket["unrecognized"] += amount

    rows = [
        {
            "month": month,
            "gst": f"{v['GST']:.2f}",
            "pst": f"{v['PST']:.2f}",
            "hst": f"{v['HST']:.2f}",
            "unrecognized_tax": f"{v['unrecognized']:.2f}",
            "total_tax": f"{(v['GST'] + v['PST'] + v['HST'] + v['unrecognized']):.2f}",
        }
        for month, v in sorted(by_month.items())
    ]
    return rows, gst_total, pst_total, hst_total, truncated


def _render_tabular_report(
    *,
    title: str,
    filename_base: str,
    fieldnames: list[str],
    rows: list[dict],
    subtitle: str,
    format: str,
    pdf_landscape: bool = False,
    pdf_col_widths: list[float] | None = None,
) -> Response:
    """Shared branded-report rendering for any (fieldnames, rows) tabular
    report — used by both the GST/PST remittance and insurance-period audit
    endpoints so format handling (pdf/csv/xlsx/docx) lives in one place.

    pdf_landscape/pdf_col_widths: reports with several columns or long
    cell values (UUIDs, ISO timestamps) need landscape orientation and
    wider ratios for those columns — passed per-report since each report's
    column shape differs. Regression: an earlier fixed-width single-line
    pdf.cell() renderer clipped/overlapped text into an unreadable table
    the moment real data (full UUIDs, microsecond timestamps) was used —
    confirmed against a real downloaded report from the live admin portal.
    Now uses fpdf2's native Table API (report_branding.render_pdf_table),
    which wraps text and syncs row heights instead of clipping."""
    if format == "csv":
        buf = io.StringIO()
        writer = csv.DictWriter(buf, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
        return Response(
            content=buf.getvalue().encode("utf-8-sig"),
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.csv"'},
        )

    if format == "xlsx":
        wb, ws = report_branding.new_branded_workbook(title, subtitle)
        report_branding.write_branded_table(ws, fieldnames, rows)
        buf = io.BytesIO()
        wb.save(buf)
        return Response(
            content=buf.getvalue(),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.xlsx"'},
        )

    if format == "docx":
        doc = report_branding.new_branded_document(title, subtitle)
        report_branding.add_branded_table(doc, fieldnames, rows)
        buf = io.BytesIO()
        doc.save(buf)
        return Response(
            content=buf.getvalue(),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f'attachment; filename="{filename_base}.docx"'},
        )

    # default: pdf
    pdf = report_branding.new_branded_pdf(title, subtitle, landscape=pdf_landscape)
    report_branding.render_pdf_table(pdf, fieldnames, rows, col_widths=pdf_col_widths)
    return Response(
        content=bytes(pdf.output()),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename_base}.pdf"'},
    )


def _require_spinr_ca(email_to: Optional[str]) -> None:
    """Reports may only be emailed to a @spinr.ca address — this is an
    internal-admin delivery convenience, not a general "email this PDF
    anywhere" feature, so the domain is hard-validated rather than trusting
    whatever the admin typed."""
    if email_to and not email_to.lower().strip().endswith("@spinr.ca"):
        raise HTTPException(status_code=422, detail="Reports can only be emailed to a @spinr.ca address")


async def _deliver_report(resp: Response, email_to: Optional[str], admin: dict, title: str) -> Response:
    """If `email_to` is set, email the already-rendered report as an
    attachment (reusing the Response _render_tabular_report already built —
    no separate rendering path to keep in sync) and return a small JSON
    confirmation instead of streaming the file to the browser. Otherwise
    return `resp` unchanged for a normal download."""
    if not email_to:
        return resp
    disposition = resp.headers.get("content-disposition", "")
    filename = disposition.split("filename=", 1)[-1].strip('"') if "filename=" in disposition else "report"
    try:
        sent = await send_transactional_email(
            to=email_to,
            subject=f"Spinr — {title}",
            text=f"Attached: {title}, generated by {admin.get('email') or admin.get('id')}.",
            attachments=[{"filename": filename, "content": resp.body}],
            email_type="admin_report",
            recipient_user_id=None,
        )
    except Exception as e:
        # send_transactional_email's own docstring says it returns True/False
        # and never raises, but an unhandled exception here (e.g. from the
        # SES/Resend client construction, or DB error in the suppression
        # check) previously fell through to FastAPI's default 500, which the
        # admin dashboard's generic error toast rendered as the unhelpful
        # "Could not generate report / Internal Server Error". Catch and log
        # the real exception loudly, then surface the same clean 502 the
        # `not sent` branch already gives for an expected send failure.
        logger.error("compliance report email send failed for %s: %s", title, e, exc_info=True)
        raise HTTPException(status_code=502, detail="Could not send the report email — try downloading it instead") from e
    if not sent:
        raise HTTPException(status_code=502, detail="Could not send the report email — try downloading it instead")
    return Response(content=f'{{"emailed_to": "{email_to}"}}', media_type="application/json")


@api_router.get("/gst-pst-remittance")
@limiter.limit("10/minute")
async def get_gst_pst_remittance(
    request: Request,
    date_range: str = Query("30d", pattern="^(today|7d|30d|90d|1y)$"),
    format: str = Query("pdf", pattern="^(pdf|csv|xlsx|docx)$"),
    email_to: Optional[str] = Query(
        None, description="Email the report to this @spinr.ca address instead of downloading it"
    ),
    admin: dict = Depends(get_admin_user),
):
    """GST/PST tax remittance summary, grouped by month, over completed
    rides in the requested date range. Spinr-branded (never a fixed
    regulator format — CRA remittance filing has no prescribed layout,
    unlike SGI's forms)."""
    _require_spinr_ca(email_to)
    start_date = _parse_date_range(date_range)
    end_date = datetime.now(timezone.utc)

    try:
        rows, gst_total, pst_total, hst_total, truncated = await _gst_pst_rows(start_date, end_date)
    except Exception as e:
        logger.error(f"Failed to build GST/PST remittance summary: {e}", exc_info=True)
        _capture_export_failure("gst_pst_remittance", e)
        metrics.inc("spinr_admin_compliance_export_total", {"report_type": "gst_pst_remittance", "outcome": "error"})
        raise HTTPException(status_code=503, detail="Compliance report data unavailable — database error") from e

    gate_response = await _check_export_gate(
        admin,
        "compliance.gst_pst_remittance",
        {"date_range": date_range, "format": format, "email_to": email_to},
        len(rows),
    )
    if gate_response is not None:
        return gate_response

    fieldnames = ["month", "gst", "pst", "hst", "unrecognized_tax", "total_tax"]
    subtitle = (
        f"{start_date.date().isoformat()} to {end_date.date().isoformat()} — "
        f"Total GST ${gst_total:.2f}, Total PST ${pst_total:.2f}, Total HST ${hst_total:.2f}"
    )
    if truncated:
        subtitle += f" — ⚠ TRUNCATED at {_ROW_LIMIT} rides; narrow the date range for a complete filing"

    await _log_compliance_export(
        admin,
        "gst_pst_remittance",
        {"date_range": date_range, "format": format, "start": start_date.isoformat(), "end": end_date.isoformat()},
        len(rows),
    )
    metrics.inc("spinr_admin_compliance_export_total", {"report_type": "gst_pst_remittance", "outcome": "success"})

    resp = _render_tabular_report(
        title="GST/PST Remittance Summary",
        filename_base="gst_pst_remittance",
        fieldnames=fieldnames,
        rows=rows,
        subtitle=subtitle,
        format=format,
    )
    return await _deliver_report(resp, email_to, admin, "GST/PST Remittance Summary")


# ── Insurance-Period Regulatory Audit ────────────────────────────────


_PERIOD_LABELS = {
    0: "0 — Offline",
    1: "1 — Available (contingent liability)",
    2: "2 — En route to pickup (primary commercial)",
    3: "3 — Passenger aboard (primary commercial, full)",
}


async def _insurance_period_rows(
    start_date: datetime, end_date: datetime, driver_id: Optional[str]
) -> tuple[list[dict], bool]:
    """Pull driver_insurance_periods rows for the requested window (append-
    only regulatory audit table, migration 64), joined with each driver's
    name for readability — mirrors the driver-identification already shown
    on the real SGI forms (sgi_field_maps.py), not new PII exposure."""
    filters: dict = {"started_at": {"$gte": start_date.isoformat(), "$lte": end_date.isoformat()}}
    if driver_id:
        filters["driver_id"] = driver_id

    periods = await db_supabase.get_rows(
        "driver_insurance_periods",
        filters,
        columns="id,driver_id,period,started_at,ended_at,ride_id",
        order="started_at",
        desc=True,
        limit=_ROW_LIMIT,
    )
    truncated = _check_truncated(len(periods), "insurance_period_audit")
    if not periods:
        return [], truncated

    driver_ids = sorted({p["driver_id"] for p in periods if p.get("driver_id")})
    driver_names: dict[str, str] = {}
    for i in range(0, len(driver_ids), 200):
        batch = driver_ids[i : i + 200]
        driver_rows = await db_supabase.get_rows(
            "drivers", {"id": {"$in": batch}}, columns="id,name,first_name,last_name", limit=len(batch)
        )
        for d in driver_rows:
            concatenated = f"{d.get('first_name', '')} {d.get('last_name', '')}".strip()
            driver_names[d["id"]] = d.get("name") or concatenated or d["id"]

    rows = [
        {
            "driver_name": driver_names.get(p["driver_id"], p["driver_id"]),
            "period": _PERIOD_LABELS.get(p.get("period"), str(p.get("period"))),
            "started_at": report_branding.format_report_timestamp(p.get("started_at")),
            "ended_at": report_branding.format_report_timestamp(p.get("ended_at"), empty="(open)"),
        }
        for p in periods
    ]
    return rows, truncated


@api_router.get("/insurance-period-audit")
@limiter.limit("10/minute")
async def get_insurance_period_audit(
    request: Request,
    date_range: str = Query("30d", pattern="^(today|7d|30d|90d|1y)$"),
    driver_id: Optional[str] = None,
    format: str = Query("pdf", pattern="^(pdf|csv|xlsx|docx)$"),
    email_to: Optional[str] = Query(
        None, description="Email the report to this @spinr.ca address instead of downloading it"
    ),
    admin: dict = Depends(get_admin_user),
):
    """Driver insurance-period transition audit export — for SGI or a
    future province's regulator audit of TNC insurance-period
    classification (CLAUDE.md's Insurance periods table). Spinr-branded;
    this is Spinr's own audit trail, not a fixed regulator form."""
    _require_spinr_ca(email_to)
    start_date = _parse_date_range(date_range)
    end_date = datetime.now(timezone.utc)

    try:
        rows, truncated = await _insurance_period_rows(start_date, end_date, driver_id)
    except Exception as e:
        logger.error(f"Failed to build insurance-period audit export: {e}", exc_info=True)
        _capture_export_failure("insurance_period_audit", e)
        metrics.inc(
            "spinr_admin_compliance_export_total", {"report_type": "insurance_period_audit", "outcome": "error"}
        )
        raise HTTPException(status_code=503, detail="Compliance report data unavailable — database error") from e

    gate_response = await _check_export_gate(
        admin,
        "compliance.insurance_period_audit",
        {"date_range": date_range, "driver_id": driver_id, "format": format, "email_to": email_to},
        len(rows),
    )
    if gate_response is not None:
        return gate_response

    # driver_id and ride_id are intentionally excluded from the rendered
    # report (product decision) — driver_id filtering still works via the
    # `driver_id` query param above; `driver_name` already identifies the
    # driver on the report itself.
    fieldnames = ["driver_name", "period", "started_at", "ended_at"]
    subtitle = f"{start_date.date().isoformat()} to {end_date.date().isoformat()}" + (
        f" — driver {driver_id}" if driver_id else " — all drivers"
    )
    if truncated:
        subtitle += f" — ⚠ TRUNCATED at {_ROW_LIMIT} rows; narrow the date range or filter by driver_id"

    await _log_compliance_export(
        admin,
        "insurance_period_audit",
        {
            "date_range": date_range,
            "format": format,
            "driver_id": driver_id,
            "start": start_date.isoformat(),
            "end": end_date.isoformat(),
        },
        len(rows),
    )
    metrics.inc("spinr_admin_compliance_export_total", {"report_type": "insurance_period_audit", "outcome": "success"})

    resp = _render_tabular_report(
        title="Driver Insurance-Period Audit",
        filename_base="insurance_period_audit",
        fieldnames=fieldnames,
        rows=rows,
        subtitle=subtitle,
        format=format,
        # Long period-label/ISO-timestamp content still needs landscape +
        # wider ratios than the shorter driver_name column — portrait +
        # equal widths is what produced the overlapping, unreadable table
        # (see docstring on _render_tabular_report).
        pdf_landscape=True,
        pdf_col_widths=[2.5, 2.5, 2.2, 2.2],
    )
    return await _deliver_report(resp, email_to, admin, "Driver Insurance-Period Audit")


# ── Knight Archer Insurance — Driver Onboarding Report ───────────────


async def _knight_archer_driver_rows(status: Optional[str]) -> tuple[list[dict], bool]:
    """Pull every onboarded driver's license/status info for Knight Archer
    (a Saskatchewan insurance company Spinr reports driver onboarding to,
    separate from the SGI D00032/D00033 regulator forms). Deliberately
    covers every driver status, not just active — Knight Archer's ask was
    for "driver onboarded, driver license, with all status", i.e. the full
    roster regardless of where a driver currently sits in the pipeline
    (pending/needs_review/active/suspended/banned)."""
    filters: dict = {}
    if status:
        filters["status"] = status

    drivers = await db_supabase.get_rows(
        "drivers",
        filters,
        columns="id,name,first_name,last_name,license_number,license_class,status,created_at",
        order="created_at",
        desc=True,
        limit=_ROW_LIMIT,
    )
    truncated = _check_truncated(len(drivers), "knight_archer_driver_onboarding")
    if not drivers:
        return [], truncated

    # license_number is vault-encrypted at rest — same decrypt helper
    # sgi_forms.py uses for the SGI forms, since this report needs the real
    # license number too, not the encrypted token.
    drivers = [await _decrypt_driver_pii(d) for d in drivers]

    rows = [
        {
            "driver_name": d.get("name") or f"{d.get('first_name', '')} {d.get('last_name', '')}".strip() or d["id"],
            "license_number": d.get("license_number") or "",
            "license_class": d.get("license_class") or "",
            "status": d.get("status") or "",
            "onboarded_at": report_branding.format_report_timestamp(d.get("created_at")),
        }
        for d in drivers
    ]
    return rows, truncated


@api_router.get("/knight-archer-driver-onboarding")
@limiter.limit("10/minute")
async def get_knight_archer_driver_onboarding(
    request: Request,
    status: Optional[str] = Query(None, description="Exact match on drivers.status; omit to include every status"),
    format: str = Query("pdf", pattern="^(pdf|csv|xlsx|docx)$"),
    email_to: Optional[str] = Query(
        None, description="Email the report to this @spinr.ca address instead of downloading it"
    ),
    admin: dict = Depends(get_admin_user),
):
    """Knight Archer (Saskatchewan insurance company) driver-onboarding
    report — driver name, license number, license class, and current
    status, for every onboarded driver regardless of status. Spinr-branded,
    not a fixed regulator form (see module docstring)."""
    _require_spinr_ca(email_to)
    try:
        rows, truncated = await _knight_archer_driver_rows(status)
    except Exception as e:
        logger.error(f"Failed to build Knight Archer driver onboarding export: {e}", exc_info=True)
        _capture_export_failure("knight_archer_driver_onboarding", e)
        metrics.inc(
            "spinr_admin_compliance_export_total",
            {"report_type": "knight_archer_driver_onboarding", "outcome": "error"},
        )
        raise HTTPException(status_code=503, detail="Compliance report data unavailable — database error") from e

    fieldnames = ["driver_name", "license_number", "license_class", "status", "onboarded_at"]
    subtitle = f"Status: {status}" if status else "All statuses"
    if truncated:
        subtitle += f" — ⚠ TRUNCATED at {_ROW_LIMIT} rows; narrow with the status filter"

    await _log_compliance_export(
        admin,
        "knight_archer_driver_onboarding",
        {"status": status, "format": format},
        len(rows),
    )
    metrics.inc(
        "spinr_admin_compliance_export_total",
        {"report_type": "knight_archer_driver_onboarding", "outcome": "success"},
    )

    resp = _render_tabular_report(
        title="Knight Archer Insurance — Driver Onboarding Report",
        filename_base="knight_archer_driver_onboarding",
        fieldnames=fieldnames,
        rows=rows,
        subtitle=subtitle,
        format=format,
        pdf_landscape=True,
        pdf_col_widths=[2.5, 2.2, 1.6, 1.8, 2.0],
    )
    return await _deliver_report(resp, email_to, admin, "Knight Archer Insurance — Driver Onboarding Report")


# ── T4A / Reportable Platform Operator Filer Handoff ─────────────────
#
# Spinr's drivers are independent contractors, which triggers two
# separate CRA obligations: the traditional T4A (Box 048, "Fees for
# Services", ≥$500/year threshold) and — since Jan 1 2024 — the
# Reportable Platform Operator rules (Income Tax Act Part XX.1, Canada's
# adoption of the OECD Model Reporting Rules for Digital Platforms,
# "Personal Services" category), which additionally requires collecting
# and verifying each qualifying driver's Tax ID (SIN/BN) and filing a
# Platform Information Return by January 31.
#
# Decision (see ACTION_ITEMS.md): Spinr does not collect or store SIN.
# It never has — migration 92's own docstring already establishes SIN
# stays on Stripe Connect Express's side, retrievable one driver at a
# time only via the audited POST /drivers/{id}/reveal-sin admin
# endpoint (super_admin only, every reveal logged). Actual CRA filing
# (T4A and/or the Platform Information Return — which one(s) apply is a
# determination for a tax advisor, not this code) is expected to go
# through a third-party filer. This export is exactly the SIN-free half
# of that handoff: per-driver annual earnings plus Stripe-verified legal
# name/address for every driver who crossed the threshold, so the filer
# has everything except the SIN itself, which they collect directly from
# the driver (or an admin retrieves per-driver via reveal-sin when
# actually filing).


async def _t4a_filer_handoff_rows(year: int) -> tuple[list[dict], bool, int]:
    """Per-driver annual earnings (from completed rides, same
    driver_earnings-first definition as routes/drivers/_shared.py's
    _ride_income, used by the driver-facing T4A summary) for every driver
    at or above the $500 CRA threshold in `year`, plus their Stripe-
    verified legal name/mailing address. Reads all of the year's
    completed rides in ONE query and aggregates in Python — avoids an
    N+1 per-driver rides query for what could be hundreds of drivers."""
    start = f"{year}-01-01"
    end = f"{year + 1}-01-01"
    rides = await db_supabase.get_rows(
        "rides",
        {"status": "completed", "ride_completed_at": {"$gte": start, "$lt": end}},
        columns="driver_id,driver_earnings,base_fare,distance_fare,time_fare,tip_amount",
        limit=_ROW_LIMIT,
    )
    truncated = _check_truncated(len(rides), "t4a_filer_handoff")

    earnings_by_driver: dict[str, Decimal] = {}
    trips_by_driver: dict[str, int] = {}
    for r in rides:
        driver_id = r.get("driver_id")
        if not driver_id:
            continue
        earnings_by_driver[driver_id] = earnings_by_driver.get(driver_id, Decimal("0")) + _ride_income(r)
        trips_by_driver[driver_id] = trips_by_driver.get(driver_id, 0) + 1

    qualifying_ids = sorted(did for did, total in earnings_by_driver.items() if total >= _T4A_THRESHOLD)
    if not qualifying_ids:
        return [], truncated, 0

    driver_rows: list[dict] = []
    for i in range(0, len(qualifying_ids), 200):
        batch = qualifying_ids[i : i + 200]
        driver_rows.extend(
            await db_supabase.get_rows(
                "drivers",
                {"id": {"$in": batch}},
                columns="id,name,first_name,last_name,stripe_account_id,stripe_id_number_provided",
                limit=len(batch),
            )
        )
    by_id = {d["id"]: d for d in driver_rows}

    rows: list[dict] = []
    for driver_id in qualifying_ids:
        d = by_id.get(driver_id, {})
        # Live per-driver Stripe call — acceptable here: this is an
        # admin-triggered, once-a-year batch operation over a bounded
        # driver count, not a request-latency-sensitive hot path (unlike
        # the SLA-bound paths CLAUDE.md's anti-pattern list warns about).
        stripe_info = await get_legal_name_and_address_from_stripe(d) or {}
        rows.append(
            {
                "driver_name": d.get("name") or f"{d.get('first_name', '')} {d.get('last_name', '')}".strip() or driver_id,
                "legal_name_stripe": stripe_info.get("legal_name") or "",
                "address_line1": stripe_info.get("address_line1") or "",
                "address_line2": stripe_info.get("address_line2") or "",
                "city": stripe_info.get("city") or "",
                "province": stripe_info.get("province") or "",
                "postal_code": stripe_info.get("postal_code") or "",
                "country": stripe_info.get("country") or "",
                "total_trips": trips_by_driver.get(driver_id, 0),
                "total_earnings": f"{earnings_by_driver[driver_id]:.2f}",
                "sin_on_file_at_stripe": "Yes" if d.get("stripe_id_number_provided") else "No",
            }
        )
    return rows, truncated, len(qualifying_ids)


@api_router.get("/t4a-filer-handoff")
@limiter.limit("10/minute")
async def get_t4a_filer_handoff(
    request: Request,
    year: int = Query(..., ge=2020, le=2100),
    format: str = Query("xlsx", pattern="^(pdf|csv|xlsx|docx)$"),
    email_to: Optional[str] = Query(
        None, description="Email the report to this @spinr.ca address instead of downloading it"
    ),
    admin: dict = Depends(get_admin_user),
):
    """Per-driver annual earnings + Stripe-verified legal name/address for
    every driver who crossed the $500 CRA reporting threshold in `year` —
    for handoff to a third-party tax filer. Never includes the SIN
    itself (see the module-section docstring above). Restricted to
    super_admin: unlike the other Compliance reports, this one surfaces
    verified legal name + mailing address in bulk, a meaningfully more
    sensitive combination than aggregate tax totals."""
    if (admin.get("role") or "").lower() != "super_admin":
        raise HTTPException(status_code=403, detail="t4a_filer_handoff requires super_admin role")
    _require_spinr_ca(email_to)

    try:
        rows, truncated, qualifying_count = await _t4a_filer_handoff_rows(year)
    except Exception as e:
        logger.error(f"Failed to build T4A filer handoff export for {year}: {e}", exc_info=True)
        _capture_export_failure("t4a_filer_handoff", e)
        metrics.inc("spinr_admin_compliance_export_total", {"report_type": "t4a_filer_handoff", "outcome": "error"})
        raise HTTPException(status_code=503, detail="Compliance report data unavailable — database error") from e

    gate_response = await _check_export_gate(
        admin,
        "compliance.t4a_filer_handoff",
        {"year": year, "format": format, "email_to": email_to},
        len(rows),
    )
    if gate_response is not None:
        return gate_response

    fieldnames = [
        "driver_name",
        "legal_name_stripe",
        "address_line1",
        "address_line2",
        "city",
        "province",
        "postal_code",
        "country",
        "total_trips",
        "total_earnings",
        "sin_on_file_at_stripe",
    ]
    subtitle = (
        f"Tax year {year} — {qualifying_count} driver(s) at or above the ${_T4A_THRESHOLD} CRA threshold. "
        "SIN not included — retrieve per-driver via the audited reveal-sin admin endpoint when filing."
    )
    if truncated:
        subtitle += f" — ⚠ TRUNCATED at {_ROW_LIMIT} rides; narrow the query"

    await _log_compliance_export(admin, "t4a_filer_handoff", {"year": year, "format": format}, len(rows))
    metrics.inc("spinr_admin_compliance_export_total", {"report_type": "t4a_filer_handoff", "outcome": "success"})

    resp = _render_tabular_report(
        title=f"T4A Filer Handoff — Tax Year {year}",
        filename_base=f"t4a_filer_handoff_{year}",
        fieldnames=fieldnames,
        rows=rows,
        subtitle=subtitle,
        format=format,
        pdf_landscape=True,
    )
    return await _deliver_report(resp, email_to, admin, f"T4A Filer Handoff — Tax Year {year}")
