from decimal import Decimal
from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field

try:
    from .. import db_supabase
    from ..dependencies import get_current_user
    from ..settings_loader import get_app_settings
    from ..utils.audit_logger import log_user_action as _audit_log_user
    from ..utils.error_handling import (
        PaymentException,
        PaymentMethodInvalidException,
    )
    from ..utils.error_keys import ErrorKeys
    from ..utils.idempotency import idempotent_endpoint
    from ..utils.money import dollars_to_cents
    from ..utils.rate_limiter import payment_action_limit
except ImportError:
    import db_supabase
    from dependencies import get_current_user
    from settings_loader import get_app_settings
    from utils.audit_logger import log_user_action as _audit_log_user
    from utils.error_handling import (
        PaymentException,
        PaymentMethodInvalidException,
    )
    from utils.error_keys import ErrorKeys
    from utils.idempotency import idempotent_endpoint
    from utils.money import dollars_to_cents
    from utils.rate_limiter import payment_action_limit
import logging

import stripe

logger = logging.getLogger(__name__)
api_router = APIRouter(prefix="/payments", tags=["Payments"])


class PaymentIntentRequest(BaseModel):
    """Request body for POST /payments/create-intent."""

    amount: Decimal = Field(..., gt=0, le=100000, decimal_places=2, description="Amount in CAD (1–100000)")
    ride_id: Optional[str] = None
    # UUID v4 generated by the mobile client for each new payment attempt.
    # Prevents Stripe idempotency-key collisions when the same user pays
    # the same fare amount on two separate rides within the same 24 h window.
    client_idempotency_key: Optional[str] = None
    payment_method_id: Optional[str] = None


class PaymentSheetRequest(BaseModel):
    """Request body for POST /payments/payment-sheet."""

    amount: Decimal = Field(..., gt=0, le=100000, decimal_places=2, description="Fare amount in CAD")
    ride_id: Optional[str] = None
    client_idempotency_key: Optional[str] = None


async def get_or_create_stripe_customer(user_id: str, stripe_secret: str):
    user = await db_supabase.get_user_by_id(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    stripe_customer_id = user.get("stripe_customer_id")

    if not stripe_customer_id:
        customer = stripe.Customer.create(
            email=user.get("email"),
            name=f"{user.get('first_name', '')} {user.get('last_name', '')}".strip(),
            metadata={"user_id": user_id},
            api_key=stripe_secret,
        )
        stripe_customer_id = customer.id
        await db_supabase.update_one("users", {"id": user_id}, {"stripe_customer_id": stripe_customer_id})
        # Re-read to use the authoritative value in case a concurrent replica wrote first.
        # (The loser's Stripe customer is unused but harmless; deduplication can run offline.)
        fresh = await db_supabase.get_user_by_id(user_id)
        if not fresh:
            raise HTTPException(status_code=404, detail="User not found during Stripe customer creation")
        stripe_customer_id = fresh["stripe_customer_id"]

    return stripe_customer_id


@api_router.post("/create-intent")
@payment_action_limit
@idempotent_endpoint(scope="payment_intent")
async def create_payment_intent(
    body: PaymentIntentRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Create a Stripe payment intent.

    `amount` is validated by Pydantic (positive, ≤ 100000 CAD) before we
    reach Stripe. Rejecting at the boundary gives a 422 response on bad
    input instead of a 500 after Stripe refuses it.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        raise HTTPException(
            status_code=503,
            detail="Payment processing is not configured. Please contact support.",
        )

    try:
        # Cross-check requested amount against the stored ride fare (8-3).
        # Decimal comparison avoids float equality pitfalls.
        if body.ride_id:
            ride = await db_supabase.get_ride(body.ride_id)
            if not ride:
                raise HTTPException(status_code=404, detail="Ride not found")
            ride_fare = Decimal(str(ride.get("total_fare", 0)))
            requested = Decimal(str(body.amount))
            if requested != ride_fare:
                raise PaymentException(
                    message=f"Payment amount {requested} does not match ride fare {ride_fare}",
                    message_key=ErrorKeys.RIDE_PRICE_MISMATCH,
                    action_hint="Refresh the fare estimate",
                )

        # Decimal-safe dollars→cents (HALF_UP). ``int(body.amount * 100)``
        # would undercharge by 1¢ on values like $0.29, $1.13, $17.81 due
        # to binary-float drift. See backend/utils/money.py.
        amount = dollars_to_cents(body.amount)

        # Get or create customer for saved payments
        stripe_customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)

        intent_params = {
            "amount": amount,
            "currency": "cad",
            "automatic_payment_methods": {"enabled": True},
            "metadata": {"user_id": current_user["id"], "ride_id": body.ride_id or ""},
        }

        if stripe_customer_id:
            intent_params["customer"] = stripe_customer_id

        if body.payment_method_id:
            intent_params["payment_method"] = body.payment_method_id

        # Idempotency key ties this PaymentIntent to a specific ride so a
        # network retry cannot create a duplicate charge (P2-8 / DV-4).
        # Priority: client-supplied UUID (most specific) > ride-scoped key
        # (safe: ride IDs are globally unique) > 1-minute time-bucket per user
        # (last resort when ride_id absent — prevents same-amount collisions
        # that occurred with the old "intent-{user}-{amount}" pattern).
        import time as _time

        if body.client_idempotency_key:
            idempotency_key = body.client_idempotency_key
        elif body.ride_id:
            idempotency_key = f"ride-{body.ride_id}-{current_user['id']}"
        else:
            idempotency_key = f"intent-{current_user['id']}-{int(_time.time() // 60)}"
        intent = stripe.PaymentIntent.create(
            **intent_params,
            api_key=stripe_secret,
            idempotency_key=idempotency_key,
        )

        return {"client_secret": intent.client_secret, "payment_intent_id": intent.id, "mock": False}
    except stripe.error.CardError as e:
        logger.error(f"Stripe CardError on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=402, detail=e.user_message or "Card declined") from e
    except stripe.error.StripeError as e:
        logger.error(f"Stripe API error on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment service unavailable. Please try again.") from e
    except Exception as e:
        logger.error(f"Unexpected error on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/confirm")
@payment_action_limit
async def confirm_payment(
    body: Dict[str, Any], request: Request = None, current_user: dict = Depends(get_current_user)
):
    """Confirm payment was successful"""
    payment_intent_id = body.get("payment_intent_id")
    ride_id = body.get("ride_id")

    if payment_intent_id and payment_intent_id.startswith("pi_mock_"):
        # Mock payment
        if ride_id:
            await db_supabase.update_ride(ride_id, {"payment_status": "paid", "payment_intent_id": payment_intent_id})
        return {"status": "succeeded", "mock": True}

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if stripe_secret:
        try:
            intent = stripe.PaymentIntent.retrieve(payment_intent_id, api_key=stripe_secret)

            if intent.metadata.get("user_id") != str(current_user["id"]):
                raise HTTPException(status_code=403, detail="Not authorized to confirm this payment")

            if ride_id:
                await db_supabase.update_ride(
                    ride_id, {"payment_status": intent.status, "payment_intent_id": payment_intent_id}
                )

            return {"status": intent.status, "mock": False}
        except Exception as e:
            logger.error(f"Stripe error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e

    return {"status": "unknown", "mock": True}


@api_router.post("/setup-intent")
@payment_action_limit
async def create_setup_intent(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Create a SetupIntent to save a new payment method"""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        return {"client_secret": "mock_setup_secret", "mock": True}

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)

        if not customer_id:
            raise HTTPException(status_code=400, detail="Could not create Stripe customer")

        import time as _time

        setup_intent = stripe.SetupIntent.create(
            customer=customer_id,
            payment_method_types=["card"],
            api_key=stripe_secret,
            idempotency_key=f"setup-intent-{current_user['id']}-{int(_time.time() // 3600)}",
        )

        return {
            "client_secret": setup_intent.client_secret,
            "setup_intent_id": setup_intent.id,
            "customer_id": customer_id,
            "mock": False,
        }
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.get("/methods")
async def get_payment_methods(current_user: dict = Depends(get_current_user)):
    """Get saved payment methods for the user"""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        return {"methods": [], "mock": True}

    try:
        user = await db_supabase.get_user_by_id(current_user["id"])
        stripe_customer_id = user.get("stripe_customer_id") if user else None

        if not stripe_customer_id:
            return {"methods": [], "mock": False}

        methods = stripe.PaymentMethod.list(
            customer=stripe_customer_id,
            type="card",
            api_key=stripe_secret,
        )

        return {
            "methods": [
                {
                    "id": m.id,
                    "brand": m.card.brand,
                    "last4": m.card.last4,
                    "exp_month": m.card.exp_month,
                    "exp_year": m.card.exp_year,
                }
                for m in methods.data
            ],
            "mock": False,
        }
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


# ─── Cards CRUD via Stripe ───


@api_router.get("/cards")
async def get_cards(current_user: dict = Depends(get_current_user)):
    """Get user's saved cards from Stripe. Last4, brand, expiry all from Stripe."""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        # Demo mode — return empty
        return []

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)
        methods = stripe.PaymentMethod.list(customer=customer_id, type="card", api_key=stripe_secret)
        user = await db_supabase.get_user_by_id(current_user["id"])
        default_pm = user.get("default_payment_method") if user else None
        return [
            {
                "id": m.id,
                "brand": m.card.brand.capitalize(),
                "last4": m.card.last4,
                "exp_month": m.card.exp_month,
                "exp_year": m.card.exp_year,
                "is_default": m.id == default_pm,
            }
            for m in methods.data
        ]
    except Exception as e:
        logger.error(f"Get cards error: {e}", exc_info=True)
        return []


class AddCardRequest(BaseModel):
    """Add-card request body.

    Accepts only a Stripe `payment_method_id` created client-side via
    Stripe.js or @stripe/stripe-react-native. Raw card fields (PAN, CVC,
    expiry) must NEVER flow through the backend — accepting them puts
    the server in PCI-DSS SAQ-D scope. See AUDIT C-PAY-01.
    """

    payment_method_id: str = Field(..., min_length=1, max_length=128)


# Field names that indicate the caller sent raw card data (PAN/CVV/expiry).
# If ANY of these are present in the request body, we refuse to process
# the request at all — before any logging, before JSON parsing by pydantic,
# before touching Stripe. This is the PCI-DSS perimeter.
_RAW_CARD_FIELDS = {
    "card_number",
    "cardNumber",
    "card_no",
    "number",
    "pan",
    "primary_account_number",
    "cvv",
    "cvv2",
    "cvc",
    "cvc2",
    "security_code",
    "card_security_code",
    "expiry",
    "expiration",
    "expiration_date",
    "exp_month",
    "exp_year",
}


@api_router.post("/cards")
@payment_action_limit
async def add_card(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Add a saved card. Requires client-side tokenization.

    Contract:
      - Body must be ``{"payment_method_id": "pm_..."}``.
      - Body must NOT contain any raw-card fields (PAN, CVC, expiry).
      - If stripe_secret_key is unset (demo mode), a fake record is
        returned with a random last4 — the payment_method_id is still
        required for contract parity so the mobile app integrates with
        a single API shape across environments.

    PCI-DSS note: we deliberately raise a plain 400 BEFORE reading the
    full JSON for logging/metrics so an attacker probing the endpoint
    with a PAN does not get it persisted in access logs. The error
    response intentionally does NOT echo the offending keys back.
    """
    # Parse once; reject immediately if the body shape hints at raw card data.
    try:
        data = await request.json()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid JSON body") from exc

    if not isinstance(data, dict):
        raise HTTPException(status_code=400, detail="Body must be a JSON object")

    forbidden = _RAW_CARD_FIELDS.intersection(data.keys())
    if forbidden:
        # Log that a raw-card POST was attempted but DO NOT log the keys'
        # values. The client needs tokenization; tell them where to look.
        logger.error(
            f"Rejected raw-card POST to /payments/cards from user={current_user.get('id')}: {sorted(forbidden)} present"
        )
        raise HTTPException(
            status_code=400,
            detail=(
                "Raw card data is not accepted. Tokenize card details "
                "client-side using Stripe.js / @stripe/stripe-react-native "
                "and submit only {'payment_method_id': 'pm_...'}."
            ),
        )

    # Validate the allowed shape. Pydantic rejects missing / wrong types with 422.
    try:
        body = AddCardRequest(**data)
    except Exception as exc:
        # B-P3-leak-cleanup: don't interpolate the Pydantic exception
        # repr (which can include field paths and request structure
        # hints). 400 is a 4xx so the framework sanitiser does not
        # rescue this — manual cleanup matters. Body-shape errors
        # should reach clients via FastAPI's RequestValidationError
        # path normally; this except block is the fallback for the
        # ad-hoc dict-driven payload here.
        logger.error("AddCardRequest validation failed", exc_info=exc)
        raise HTTPException(
            status_code=400,
            detail="Invalid request payload.",
        ) from exc

    payment_method_id = body.payment_method_id

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        # Demo mode — fabricate a response. Requires payment_method_id for
        # shape parity with production so mobile has one integration path.
        logger.info(f"[DEMO] Card added via {payment_method_id[:8]}...")
        return {
            "id": payment_method_id,
            "brand": "Visa",
            "last4": "4242",
            "exp_month": 12,
            "exp_year": 2030,
            "is_default": True,
        }

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)

        # Attach the client-tokenized PaymentMethod to the customer.
        # The PAN never touched our server — the token came from Stripe.js.
        pm = stripe.PaymentMethod.attach(payment_method_id, customer=customer_id, api_key=stripe_secret)

        # Confirm with SetupIntent — saves card for future off-session use.
        import time as _time

        si = stripe.SetupIntent.create(
            customer=customer_id,
            payment_method=pm.id,
            confirm=True,
            automatic_payment_methods={"enabled": True, "allow_redirects": "never"},
            api_key=stripe_secret,
            idempotency_key=f"setup-intent-{current_user['id']}-{int(_time.time() // 3600)}",
        )

        # Set as default if first card
        user = await db_supabase.get_user_by_id(current_user["id"])
        if not user.get("default_payment_method"):
            await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": pm.id})
            stripe.Customer.modify(customer_id, invoice_settings={"default_payment_method": pm.id})

        logger.info(f"Card added: {pm.card.brand} ****{pm.card.last4} | SetupIntent: {si.id} ({si.status})")

        return {
            "id": pm.id,
            "brand": pm.card.brand.capitalize(),
            "last4": pm.card.last4,
            "exp_month": pm.card.exp_month,
            "exp_year": pm.card.exp_year,
            "is_default": not bool(user.get("default_payment_method")),
            "setup_intent_id": si.id,
            "setup_intent_status": si.status,
        }
    except stripe.error.CardError as e:
        raise PaymentMethodInvalidException(
            message=e.user_message or "Card declined",
            message_key=ErrorKeys.PAYMENT_METHOD_INVALID,
            action_hint="Add a different card",
        ) from e
    except stripe.error.CardError as e:
        raise PaymentMethodInvalidException(
            message=e.user_message or "Card declined",
            message_key=ErrorKeys.PAYMENT_METHOD_INVALID,
            action_hint="Add a different card",
        ) from e
    except stripe.error.StripeError as e:
        logger.error(f"Stripe API error on add-card: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment service unavailable. Please try again.") from e
    except Exception as e:
        logger.error(f"Unexpected error on add-card: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/cards/{card_id}/default")
@payment_action_limit
async def set_default_card(card_id: str, request: Request = None, current_user: dict = Depends(get_current_user)):
    """Set card as default. Updates both our DB and Stripe customer."""
    await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": card_id})

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    if stripe_secret:
        try:
            user = await db_supabase.get_user_by_id(current_user["id"])
            cid = user.get("stripe_customer_id")
            if cid:
                stripe.Customer.modify(cid, invoice_settings={"default_payment_method": card_id}, api_key=stripe_secret)
        except Exception as e:
            logger.error(f"Stripe set default failed for card {card_id}: {e}", exc_info=True)

    import asyncio

    asyncio.create_task(
        _audit_log_user(
            current_user,
            "default_payment_method_set",
            "users",
            current_user["id"],
            {"card_id": card_id},
        )
    )
    return {"success": True}


@api_router.delete("/cards/{card_id}")
@payment_action_limit
async def delete_card(card_id: str, request: Request = None, current_user: dict = Depends(get_current_user)):
    """Detach card from Stripe and clear default if needed."""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    if stripe_secret:
        try:
            stripe.PaymentMethod.detach(card_id, api_key=stripe_secret)
        except Exception as e:
            logger.error(f"Stripe detach failed for card {card_id}: {e}", exc_info=True)

    user = await db_supabase.get_user_by_id(current_user["id"])
    if user and user.get("default_payment_method") == card_id:
        await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": None})

    return {"success": True}


@api_router.post("/payment-sheet")
@payment_action_limit
async def create_payment_sheet(
    body: PaymentSheetRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Return the three secrets needed to initialise Stripe PaymentSheet.

    The mobile client calls initPaymentSheet({ paymentIntent, ephemeralKey,
    customer }) then presentPaymentSheet() to complete the payment in a
    pre-built Stripe modal that supports Google Pay and Apple Pay without
    any card-form UI on our side.

    Returns:
        paymentIntent:  PaymentIntent client_secret
        ephemeralKey:   EphemeralKey secret (scoped to this customer)
        customer:       Stripe customer ID
        publishableKey: App should already have this; included for convenience
    """
    import time as _time

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    stripe_pk = settings.get("stripe_publishable_key", "")

    if not stripe_secret:
        raise HTTPException(
            status_code=503,
            detail="Payment processing is not configured. Please contact support.",
        )

    if body.ride_id:
        ride = await db_supabase.get_ride(body.ride_id)
        if not ride:
            raise HTTPException(status_code=404, detail="Ride not found")
        ride_fare = Decimal(str(ride.get("total_fare", 0)))
        requested = Decimal(str(body.amount))
        if requested != ride_fare:
            raise PaymentException(
                message=f"Payment amount {requested} does not match ride fare {ride_fare}",
                message_key=ErrorKeys.RIDE_PRICE_MISMATCH,
                action_hint="Refresh the fare estimate",
            )

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)
        amount_cents = int(Decimal(str(body.amount)).quantize(Decimal("0.01")) * 100)

        # EphemeralKey lets the PaymentSheet modal manage the customer's
        # saved cards. api_version must match the version configured on the
        # Stripe webhook endpoint in the dashboard. We pin it to the version
        # bundled with the installed SDK (stripe.api_version) so it stays in
        # sync automatically on SDK upgrades.
        # Current bundled version: 2026-04-22.dahlia (stripe==15.1.0)
        # ACTION REQUIRED on SDK upgrade: verify the Stripe dashboard webhook
        # endpoint API version matches stripe.api_version after upgrading.
        ephemeral_key = stripe.EphemeralKey.create(
            {"customer": customer_id},
            api_version=stripe.api_version,
            api_key=stripe_secret,
        )

        if body.client_idempotency_key:
            idempotency_key = body.client_idempotency_key
        elif body.ride_id:
            idempotency_key = f"ps-{body.ride_id}-{current_user['id']}"
        else:
            idempotency_key = f"ps-{current_user['id']}-{int(_time.time() // 60)}"

        intent = stripe.PaymentIntent.create(
            amount=amount_cents,
            currency="cad",
            customer=customer_id,
            automatic_payment_methods={"enabled": True},
            metadata={"user_id": current_user["id"], "ride_id": body.ride_id or ""},
            api_key=stripe_secret,
            idempotency_key=idempotency_key,
        )

        return {
            "paymentIntent": intent.client_secret,
            "ephemeralKey": ephemeral_key.secret,
            "customer": customer_id,
            "publishableKey": stripe_pk,
        }
    except stripe.error.StripeError as e:
        logger.error("Stripe payment-sheet error", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment provider error. Please try again.") from e
    except Exception as e:
        logger.error("payment-sheet unexpected error", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e
