from decimal import ROUND_HALF_UP, Decimal
from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

try:
    from .. import db_supabase
    from ..core.config import settings as core_settings
    from ..dependencies import get_current_user
    from ..settings_loader import get_app_settings
    from ..utils.audit_logger import log_user_action as _audit_log_user
    from ..utils.error_handling import (
        ErrorCode,
        PaymentMethodInvalidException,
        SpinrException,
    )
    from ..utils.error_keys import ErrorKeys
    from ..utils.idempotency import idempotent_endpoint
    from ..utils.money import dollars_to_cents
    from ..utils.rate_limiter import payment_action_limit
except ImportError:
    import db_supabase
    from core.config import settings as core_settings
    from dependencies import get_current_user
    from settings_loader import get_app_settings
    from utils.audit_logger import log_user_action as _audit_log_user
    from utils.error_handling import (
        ErrorCode,
        PaymentMethodInvalidException,
        SpinrException,
    )
    from utils.error_keys import ErrorKeys
    from utils.idempotency import idempotent_endpoint
    from utils.money import dollars_to_cents
    from utils.rate_limiter import payment_action_limit
import logging

import stripe

logger = logging.getLogger(__name__)
api_router = APIRouter(prefix="/payments", tags=["Payments"])


def _q2(v: Any) -> Decimal:
    """Quantize a money value to 2dp (HALF_UP). Decimal-only — never float."""
    return Decimal(str(v or 0)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


async def _authoritative_ride_charge(ride_id: str, rider_id: str, tip_amount: Decimal) -> Decimal:
    """Server-authoritative amount the rider owes for a ride: grand_total + tip.

    ``grand_total`` already includes area/booking fees and GST/PST; ``total_fare``
    is only the fare-side subtotal. We compute the charge here rather than
    trusting the client-supplied amount so the Stripe (create-intent /
    payment-sheet) paths can never undercharge by omitting fees or tax — the
    same total ``/rides/{id}/process-payment`` settles. Falls back to
    ``total_fare`` only for legacy rides written before ``grand_total`` existed.
    """
    ride = await db_supabase.get_ride(ride_id)
    if not ride:
        raise HTTPException(status_code=404, detail="Ride not found")
    if ride.get("rider_id") != rider_id:
        raise HTTPException(status_code=403, detail="Not authorized to pay for this ride")
    # Explicit None check, not truthiness: a legitimate $0 grand_total (comp /
    # fully-covered ride) must NOT fall through to a non-zero total_fare and
    # overcharge. Only fall back when grand_total was never written (legacy).
    grand_raw = ride.get("grand_total")
    if grand_raw is None:
        grand_raw = ride.get("total_fare", 0)
    grand = _q2(grand_raw)
    return _q2(grand + _q2(tip_amount))


class PaymentIntentRequest(BaseModel):
    """Request body for POST /payments/create-intent."""

    amount: Decimal = Field(..., gt=0, le=100000, decimal_places=2, description="Amount in CAD (1–100000)")
    ride_id: Optional[str] = None
    # Tip is added on top of the ride's grand_total when ride_id is present.
    # For ride payments the server computes the charge as grand_total + tip and
    # ignores `amount` (advisory only) — see _authoritative_ride_charge.
    tip_amount: Decimal = Field(0, ge=0, le=500, decimal_places=2)
    # UUID v4 generated by the mobile client for each new payment attempt.
    # Prevents Stripe idempotency-key collisions when the same user pays
    # the same fare amount on two separate rides within the same 24 h window.
    client_idempotency_key: Optional[str] = None
    payment_method_id: Optional[str] = None


class ConfirmPaymentRequest(BaseModel):
    """Request body for POST /payments/confirm.

    Typed (not a raw dict) so the pi_mock_* production guard and the
    ownership checks below operate on validated, length-bounded strings —
    unknown keys are rejected instead of silently carried along.
    """

    model_config = {"extra": "forbid"}

    payment_intent_id: Optional[str] = Field(None, min_length=1, max_length=255)
    ride_id: Optional[str] = Field(None, min_length=1, max_length=64)


class PaymentSheetRequest(BaseModel):
    """Request body for POST /payments/payment-sheet."""

    amount: Decimal = Field(..., gt=0, le=100000, decimal_places=2, description="Fare amount in CAD")
    ride_id: Optional[str] = None
    # See PaymentIntentRequest.tip_amount — server charges grand_total + tip
    # for ride payments and treats `amount` as advisory.
    tip_amount: Decimal = Field(0, ge=0, le=500, decimal_places=2)
    client_idempotency_key: Optional[str] = None


async def get_or_create_stripe_customer(user_id: str, stripe_secret: str):
    user = await db_supabase.get_user_by_id(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    stripe_customer_id = user.get("stripe_customer_id")

    if not stripe_customer_id:
        customer = stripe.Customer.create(
            email=user.get("email"),
            name=f"{user.get('first_name', '')} {user.get('last_name', '')}".strip(),
            metadata={"user_id": user_id},
            api_key=stripe_secret,
            idempotency_key=f"cus-create-{user_id}",
        )
        stripe_customer_id = customer.id
        await db_supabase.update_one("users", {"id": user_id}, {"stripe_customer_id": stripe_customer_id})
        # Re-read to use the authoritative value in case a concurrent replica wrote first.
        # (The loser's Stripe customer is unused but harmless; deduplication can run offline.)
        fresh = await db_supabase.get_user_by_id(user_id)
        if not fresh:
            raise HTTPException(status_code=404, detail="User not found during Stripe customer creation")
        stripe_customer_id = fresh["stripe_customer_id"]

    return stripe_customer_id


@api_router.post("/create-intent")
@payment_action_limit
@idempotent_endpoint(scope="payment_intent")
async def create_payment_intent(
    body: PaymentIntentRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Create a Stripe payment intent.

    `amount` is validated by Pydantic (positive, ≤ 100000 CAD) before we
    reach Stripe. Rejecting at the boundary gives a 422 response on bad
    input instead of a 500 after Stripe refuses it.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        raise HTTPException(
            status_code=503,
            detail="Payment processing is not configured. Please contact support.",
        )

    try:
        # For ride payments the server is authoritative on the amount: charge
        # grand_total + tip (the full rider-owed total incl. area fees + GST/PST),
        # not the client-supplied figure. This closes an undercharge where the
        # client sent only total_fare (fare minus fees/tax) and the tax went
        # uncollected — and mirrors what /rides/{id}/process-payment settles.
        charge_amount = Decimal(str(body.amount))
        if body.ride_id:
            charge_amount = await _authoritative_ride_charge(body.ride_id, current_user["id"], body.tip_amount)

        # Decimal-safe dollars→cents (HALF_UP). ``int(amount * 100)``
        # would undercharge by 1¢ on values like $0.29, $1.13, $17.81 due
        # to binary-float drift. See backend/utils/money.py.
        amount = dollars_to_cents(charge_amount)

        # Get or create customer for saved payments
        stripe_customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)

        intent_params = {
            "amount": amount,
            "currency": "cad",
            "automatic_payment_methods": {"enabled": True},
            "metadata": {"user_id": current_user["id"], "ride_id": body.ride_id or ""},
        }

        if stripe_customer_id:
            intent_params["customer"] = stripe_customer_id

        if body.payment_method_id:
            intent_params["payment_method"] = body.payment_method_id

        # Idempotency key ties this PaymentIntent to a specific ride so a
        # network retry cannot create a duplicate charge (P2-8 / DV-4).
        # Priority: client-supplied UUID (most specific) > ride-scoped key
        # (safe: ride IDs are globally unique) > 1-minute time-bucket per user
        # (last resort when ride_id absent — prevents same-amount collisions
        # that occurred with the old "intent-{user}-{amount}" pattern).
        import time as _time

        if body.client_idempotency_key:
            idempotency_key = body.client_idempotency_key
        elif body.ride_id:
            # Include the charge amount (cents) so that if the rider changes
            # their tip and retries, Stripe sees a distinct key and creates a
            # fresh PaymentIntent instead of raising IdempotencyError on the
            # amount mismatch. Same amount → same key → still idempotent.
            idempotency_key = f"ride-{body.ride_id}-{current_user['id']}-{amount}"
        else:
            idempotency_key = f"intent-{current_user['id']}-{int(_time.time() // 60)}"
        intent = stripe.PaymentIntent.create(
            **intent_params,
            api_key=stripe_secret,
            idempotency_key=idempotency_key,
        )

        # 3-D Secure / SCA happy-path: PaymentIntent succeeded at the API
        # boundary but Stripe is asking the rider to complete an additional
        # authentication step (3DS challenge). The mobile SDK reads
        # `client_secret` + `next_action` to drive the flow. We surface this
        # as a 402 with `code='action_required'` so the rider app branches
        # into Stripe's handleNextAction() rather than treating it as
        # success and confirming the payment server-side.
        if getattr(intent, "status", None) == "requires_action":
            return JSONResponse(
                status_code=402,
                content={
                    "success": False,
                    "detail": "Additional authentication required",
                    "error": {
                        "code": ErrorCode.PAYMENT_METHOD_INVALID.value,
                        "message": "Additional authentication required",
                        "message_key": ErrorKeys.PAYMENT_METHOD_INVALID,
                        "details": {
                            "code": "action_required",
                            "client_secret": intent.client_secret,
                            "payment_intent_id": intent.id,
                            "next_action": getattr(intent, "next_action", None),
                        },
                    },
                },
            )

        return {
            "client_secret": intent.client_secret,
            "payment_intent_id": intent.id,
            "mock": False,
        }
    except stripe.error.CardError as e:
        # Order matters: CardError must come BEFORE the generic StripeError
        # branch (Python checks except clauses top-down, and CardError is a
        # StripeError subclass). Card-decline / wrong-CVC / expired-card all
        # land here and must surface as 402 so the rider SDK switches to
        # the "try another card" UX. 3-D Secure challenges raised
        # synchronously (rare; the success-path handler above is the common
        # route) appear as code='authentication_required' and we forward
        # that to the SDK as code='action_required'.
        logger.error(f"Stripe CardError on create-intent: {e}", exc_info=True)
        details: Dict[str, Any] = {}
        if getattr(e, "code", None) == "authentication_required":
            details["code"] = "action_required"
        raise PaymentMethodInvalidException(
            message=getattr(e, "user_message", None) or "Card declined",
            message_key=ErrorKeys.PAYMENT_METHOD_INVALID,
            status_code=402,
            action_hint="Add a different card",
            details=details or None,
        ) from e
    except stripe.error.RateLimitError as e:
        # Stripe is throttling us. 429 with Retry-After lets the rider
        # app's Axios interceptor back off rather than retrying instantly.
        # We use SpinrException directly (not RateLimitExceededException)
        # to keep the response shape identical to the OTP-lockout 429
        # handler — same parser on the mobile side.
        logger.error(f"Stripe RateLimitError on create-intent: {e}", exc_info=True)
        raise SpinrException(
            message="Payment provider is rate-limiting requests. Please try again shortly.",
            error_code=ErrorCode.RATE_LIMIT_EXCEEDED,
            status_code=429,
            headers={"Retry-After": "30"},
            action_hint="Try again in a moment",
        ) from e
    except stripe.error.StripeError as e:
        logger.error(f"Stripe API error on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment service unavailable. Please try again.") from e
    except HTTPException:
        # Intentional 4xx (ownership 403, validation 400) from helpers like
        # _authoritative_ride_charge must reach the client, not become a 500.
        raise
    except Exception as e:
        logger.error(f"Unexpected error on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/confirm")
@payment_action_limit
@idempotent_endpoint(scope="payment_confirm")
async def confirm_payment(
    body: ConfirmPaymentRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Confirm payment was successful"""
    payment_intent_id = body.payment_intent_id
    ride_id = body.ride_id

    # Mock-payment shortcut is allowed only outside production, OR for an
    # allow-listed app-store reviewer account (so a reviewer can reach a "paid"
    # confirmation without a real charge). Reject everyone else up front —
    # before claiming the ride into payment_status=processing — so a rejected
    # request can't strand the ride. In production any other authenticated rider
    # could otherwise send "pi_mock_*" and settle their own ride for free.
    _is_reviewer = current_user.get("phone") in core_settings.review_login_map()
    if (
        payment_intent_id
        and payment_intent_id.startswith("pi_mock_")
        and core_settings.ENV.lower() == "production"
        and not _is_reviewer
    ):
        logger.error(
            "Rejected mock payment intent %s in production for ride %s",
            payment_intent_id,
            ride_id,
        )
        raise HTTPException(
            status_code=400,
            detail="Mock payments are not supported in production",
        )

    if ride_id:
        ride = await db_supabase.get_ride(ride_id)
        if not ride:
            raise HTTPException(status_code=404, detail="Ride not found")
        if ride["rider_id"] != current_user["id"]:
            raise HTTPException(status_code=403, detail="forbidden")

        # C-3: Idempotency check — if a prior webhook already settled this payment,
        # return early with a clear signal rather than re-entering the Stripe flow.
        # This covers the case where the rider app retries confirm_payment after a
        # network timeout when the webhook has already processed the payment.
        # HTTP 200 (not 409) because the payment succeeded — this is not an error.
        payment_status = ride.get("payment_status")
        if payment_status in ("paid", "processing"):
            logger.info(
                "confirm_payment: ride %s already in payment_status=%s, returning early (C-3 idempotency)",
                ride_id,
                payment_status,
            )
            return {"status": "already_processed", "payment_status": payment_status}

        claimed = await db_supabase.claim_ride_payment_processing(ride_id)
        if not claimed:
            raise HTTPException(status_code=409, detail="payment_already_processing")

    # Mock-payment shortcut (non-production only; production rejected above).
    if payment_intent_id and payment_intent_id.startswith("pi_mock_"):
        if ride_id:
            _ride = await db_supabase.get_ride(ride_id)
            if not _ride or _ride.get("rider_id") != current_user["id"]:
                raise HTTPException(
                    status_code=403,
                    detail="Not authorized to confirm payment for this ride",
                )
            await db_supabase.update_ride(
                ride_id,
                {"payment_status": "paid", "payment_intent_id": payment_intent_id},
            )
        return {"status": "succeeded", "mock": True}

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if stripe_secret:
        try:
            intent = stripe.PaymentIntent.retrieve(payment_intent_id, api_key=stripe_secret)

            if intent.metadata.get("user_id") != str(current_user["id"]):
                raise HTTPException(status_code=403, detail="Not authorized to confirm this payment")

            if ride_id:
                _ride = await db_supabase.get_ride(ride_id)
                if not _ride or _ride.get("rider_id") != current_user["id"]:
                    raise HTTPException(
                        status_code=403,
                        detail="Not authorized to confirm payment for this ride",
                    )

                # SECURITY (C1): ownership alone is insufficient — a rider owns
                # many PaymentIntents. Bind the PI to THIS ride and verify it
                # actually covers the owed total, or a rider could confirm a
                # cheap / other-ride intent against an expensive ride and underpay.
                pi_ride_id = (intent.metadata or {}).get("ride_id")
                if pi_ride_id and pi_ride_id != ride_id:
                    logger.error(
                        "[confirm][security] PI %s metadata ride_id=%s != ride %s",
                        payment_intent_id,
                        pi_ride_id,
                        ride_id,
                    )
                    raise HTTPException(status_code=403, detail="Payment does not match this ride")

                # Only a genuinely succeeded charge can mark a ride paid, and only
                # when the captured amount covers the authoritative owed total
                # (grand_total). amount_received is 0 until the PI succeeds.
                if intent.status == "succeeded":
                    _grand = _ride.get("grand_total")
                    if _grand is None:
                        _grand = _ride.get("total_fare", 0)
                    owed_cents = int((_q2(_grand) * 100).to_integral_value())
                    received = int(getattr(intent, "amount_received", 0) or 0)
                    if received < owed_cents:
                        logger.error(
                            "[confirm][security] underpay ride=%s pi=%s received=%d owed=%d",
                            ride_id,
                            payment_intent_id,
                            received,
                            owed_cents,
                        )
                        raise HTTPException(
                            status_code=402,
                            detail={
                                "code": "AMOUNT_MISMATCH",
                                "message": "Payment amount does not cover the fare.",
                            },
                        )

                await db_supabase.update_ride(
                    ride_id,
                    {
                        "payment_status": intent.status,
                        "payment_intent_id": payment_intent_id,
                    },
                )

            return {"status": intent.status, "mock": False}
        except HTTPException:
            # Ownership 403s above must reach the client, not become a 500.
            raise
        except Exception as e:
            logger.error(f"Stripe error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e

    return {"status": "unknown", "mock": True}


@api_router.post("/setup-intent")
@payment_action_limit
async def create_setup_intent(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Create a SetupIntent to save a new payment method"""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        return {"client_secret": "mock_setup_secret", "mock": True}

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)

        if not customer_id:
            raise HTTPException(status_code=400, detail="Could not create Stripe customer")

        import time as _time

        setup_intent = stripe.SetupIntent.create(
            customer=customer_id,
            payment_method_types=["card"],
            api_key=stripe_secret,
            idempotency_key=f"setup-intent-{current_user['id']}-{int(_time.time() // 60)}",
        )

        return {
            "client_secret": setup_intent.client_secret,
            "setup_intent_id": setup_intent.id,
            "customer_id": customer_id,
            "mock": False,
        }
    except HTTPException:
        # The 400 for a missing Stripe customer must reach the client.
        raise
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.get("/methods")
@payment_action_limit
async def get_payment_methods(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Get saved payment methods for the user"""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        return {"methods": [], "mock": True}

    try:
        user = await db_supabase.get_user_by_id(current_user["id"])
        stripe_customer_id = user.get("stripe_customer_id") if user else None

        if not stripe_customer_id:
            return {"methods": [], "mock": False}

        methods = stripe.PaymentMethod.list(
            customer=stripe_customer_id,
            type="card",
            api_key=stripe_secret,
        )

        return {
            "methods": [
                {
                    "id": m.id,
                    "brand": m.card.brand,
                    "last4": m.card.last4,
                    "exp_month": m.card.exp_month,
                    "exp_year": m.card.exp_year,
                }
                for m in methods.data
            ],
            "mock": False,
        }
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


# ─── Cards CRUD via Stripe ───


@api_router.get("/cards")
@payment_action_limit
async def get_cards(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Get user's saved cards from Stripe. Last4, brand, expiry all from Stripe."""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        # Demo mode (Stripe intentionally unconfigured for local/staging):
        # return a single selectable demo card so the booking flow has a payment
        # method to attach. Settlement then goes through charge_ride's
        # "unconfigured" path, which marks the ride paid without a real charge.
        # Not reachable in production — config fails fast on a missing Stripe key.
        return [
            {
                "id": "pm_demo_card",
                "brand": "Demo",
                "last4": "0000",
                "exp_month": 12,
                "exp_year": 2099,
                "is_default": True,
            }
        ]

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)
        methods = stripe.PaymentMethod.list(customer=customer_id, type="card", api_key=stripe_secret)
        user = await db_supabase.get_user_by_id(current_user["id"])
        default_pm = user.get("default_payment_method") if user else None
        return [
            {
                "id": m.id,
                "brand": m.card.brand.capitalize(),
                "last4": m.card.last4,
                "exp_month": m.card.exp_month,
                "exp_year": m.card.exp_year,
                "is_default": m.id == default_pm,
            }
            for m in methods.data
        ]
    except Exception as e:
        # C7: do NOT mask a Stripe outage as "no cards" — that's the log-and-
        # continue-on-payment-error anti-pattern CLAUDE.md forbids, and it makes
        # a rider think their saved card vanished. Surface 502 so the client retries.
        logger.error(f"Get cards error: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Could not load your saved cards. Please try again.") from e


class AddCardRequest(BaseModel):
    """Add-card request body.

    Accepts only a Stripe `payment_method_id` created client-side via
    Stripe.js or @stripe/stripe-react-native. Raw card fields (PAN, CVC,
    expiry) must NEVER flow through the backend — accepting them puts
    the server in PCI-DSS SAQ-D scope. See AUDIT C-PAY-01.
    """

    payment_method_id: str = Field(..., min_length=1, max_length=128)


# Field names that indicate the caller sent raw card data (PAN/CVV/expiry).
# If ANY of these are present in the request body, we refuse to process
# the request at all — before any logging, before JSON parsing by pydantic,
# before touching Stripe. This is the PCI-DSS perimeter.
_RAW_CARD_FIELDS = {
    "card_number",
    "cardNumber",
    "card_no",
    "number",
    "pan",
    "primary_account_number",
    "cvv",
    "cvv2",
    "cvc",
    "cvc2",
    "security_code",
    "card_security_code",
    "expiry",
    "expiration",
    "expiration_date",
    "exp_month",
    "exp_year",
}


@api_router.post("/cards")
@payment_action_limit
async def add_card(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Add a saved card. Requires client-side tokenization.

    Contract:
      - Body must be ``{"payment_method_id": "pm_..."}``.
      - Body must NOT contain any raw-card fields (PAN, CVC, expiry).
      - If stripe_secret_key is unset (demo mode), a fake record is
        returned with a random last4 — the payment_method_id is still
        required for contract parity so the mobile app integrates with
        a single API shape across environments.

    PCI-DSS note: we deliberately raise a plain 400 BEFORE reading the
    full JSON for logging/metrics so an attacker probing the endpoint
    with a PAN does not get it persisted in access logs. The error
    response intentionally does NOT echo the offending keys back.
    """
    # Parse once; reject immediately if the body shape hints at raw card data.
    try:
        data = await request.json()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid JSON body") from exc

    if not isinstance(data, dict):
        raise HTTPException(status_code=400, detail="Body must be a JSON object")

    forbidden = _RAW_CARD_FIELDS.intersection(data.keys())
    if forbidden:
        # Log that a raw-card POST was attempted but DO NOT log the keys'
        # values. The client needs tokenization; tell them where to look.
        logger.error(
            f"Rejected raw-card POST to /payments/cards from user={current_user.get('id')}: {sorted(forbidden)} present"
        )
        raise HTTPException(
            status_code=400,
            detail=(
                "Raw card data is not accepted. Tokenize card details "
                "client-side using Stripe.js / @stripe/stripe-react-native "
                "and submit only {'payment_method_id': 'pm_...'}."
            ),
        )

    # Validate the allowed shape. Pydantic rejects missing / wrong types with 422.
    try:
        body = AddCardRequest(**data)
    except Exception as exc:
        # B-P3-leak-cleanup: don't interpolate the Pydantic exception
        # repr (which can include field paths and request structure
        # hints). 400 is a 4xx so the framework sanitiser does not
        # rescue this — manual cleanup matters. Body-shape errors
        # should reach clients via FastAPI's RequestValidationError
        # path normally; this except block is the fallback for the
        # ad-hoc dict-driven payload here.
        logger.error("AddCardRequest validation failed", exc_info=exc)
        raise HTTPException(
            status_code=400,
            detail="Invalid request payload.",
        ) from exc

    payment_method_id = body.payment_method_id

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        # Demo mode — fabricate a response. Requires payment_method_id for
        # shape parity with production so mobile has one integration path.
        logger.info(f"[DEMO] Card added via {payment_method_id[:8]}...")
        return {
            "id": payment_method_id,
            "brand": "Visa",
            "last4": "4242",
            "exp_month": 12,
            "exp_year": 2030,
            "is_default": True,
        }

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)

        # Attach the client-tokenized PaymentMethod to the customer.
        # The PAN never touched our server — the token came from Stripe.js.
        pm = stripe.PaymentMethod.attach(payment_method_id, customer=customer_id, api_key=stripe_secret)

        # Confirm with SetupIntent — saves card for future off-session use.

        si = stripe.SetupIntent.create(
            customer=customer_id,
            payment_method=pm.id,
            confirm=True,
            automatic_payment_methods={"enabled": True, "allow_redirects": "never"},
            api_key=stripe_secret,
            idempotency_key=f"setup-card-{current_user['id']}-{pm.id}",
        )

        # Set as default if first card
        user = await db_supabase.get_user_by_id(current_user["id"])
        if not user.get("default_payment_method"):
            await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": pm.id})
            stripe.Customer.modify(
                customer_id,
                invoice_settings={"default_payment_method": pm.id},
                api_key=stripe_secret,
            )

        logger.info(f"Card added: {pm.card.brand} ****{pm.card.last4} | SetupIntent: {si.id} ({si.status})")

        return {
            "id": pm.id,
            "brand": pm.card.brand.capitalize(),
            "last4": pm.card.last4,
            "exp_month": pm.card.exp_month,
            "exp_year": pm.card.exp_year,
            "is_default": not bool(user.get("default_payment_method")),
            "setup_intent_id": si.id,
            "setup_intent_status": si.status,
        }
    except stripe.error.CardError as e:
        raise PaymentMethodInvalidException(
            message=e.user_message or "Card declined",
            message_key=ErrorKeys.PAYMENT_METHOD_INVALID,
            action_hint="Add a different card",
        ) from e
    except stripe.error.StripeError as e:
        logger.error(f"Stripe API error on add-card: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment service unavailable. Please try again.") from e
    except Exception as e:
        logger.error(f"Unexpected error on add-card: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/cards/{card_id}/default")
@payment_action_limit
async def set_default_card(
    card_id: str,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Set card as default. Updates both our DB and Stripe customer.

    C7: Stripe is updated FIRST; the DB default is only written once Stripe
    accepts it, so a Stripe failure can't leave our DB pointing at a default the
    payment processor doesn't know about. On Stripe error we surface 502 (not a
    silent success) so the client retries.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    if stripe_secret:
        try:
            user = await db_supabase.get_user_by_id(current_user["id"])
            cid = user.get("stripe_customer_id")
            if cid:
                stripe.Customer.modify(
                    cid,
                    invoice_settings={"default_payment_method": card_id},
                    api_key=stripe_secret,
                )
        except Exception as e:
            logger.error(f"Stripe set default failed for card {card_id}: {e}", exc_info=True)
            raise HTTPException(status_code=502, detail="Could not update your default card. Please try again.") from e

    await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": card_id})

    import asyncio

    asyncio.create_task(
        _audit_log_user(
            current_user,
            "default_payment_method_set",
            "users",
            current_user["id"],
            {"card_id": card_id},
        )
    )
    return {"success": True}


@api_router.delete("/cards/{card_id}")
@payment_action_limit
async def delete_card(
    card_id: str,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Detach card from Stripe and clear default if needed.

    C7: the Stripe detach must SUCCEED before we mutate our DB. Previously a
    failed detach was logged-and-ignored, then the DB default was cleared anyway
    — leaving the card live in Stripe but gone from the UI. Now a failed detach
    raises 502 and the DB is left untouched.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    if stripe_secret:
        try:
            stripe.PaymentMethod.detach(card_id, api_key=stripe_secret)
        except Exception as e:
            logger.error(f"Stripe detach failed for card {card_id}: {e}", exc_info=True)
            raise HTTPException(status_code=502, detail="Could not remove your card. Please try again.") from e

    user = await db_supabase.get_user_by_id(current_user["id"])
    if user and user.get("default_payment_method") == card_id:
        await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": None})

    return {"success": True}


@api_router.post("/payment-sheet")
@payment_action_limit
async def create_payment_sheet(
    body: PaymentSheetRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Return the three secrets needed to initialise Stripe PaymentSheet.

    The mobile client calls initPaymentSheet({ paymentIntent, ephemeralKey,
    customer }) then presentPaymentSheet() to complete the payment in a
    pre-built Stripe modal that supports Google Pay and Apple Pay without
    any card-form UI on our side.

    Returns:
        paymentIntent:  PaymentIntent client_secret
        ephemeralKey:   EphemeralKey secret (scoped to this customer)
        customer:       Stripe customer ID
        publishableKey: App should already have this; included for convenience
    """
    import time as _time

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    stripe_pk = settings.get("stripe_publishable_key", "")

    if not stripe_secret:
        raise HTTPException(
            status_code=503,
            detail="Payment processing is not configured. Please contact support.",
        )

    # CS-002: For ride payments use the server-authoritative charge
    # (grand_total + tip) rather than trusting body.amount. body.amount is
    # advisory only — a client can send a lower value to underpay area fees,
    # GST/PST, or tip. _authoritative_ride_charge enforces ownership (403 on
    # rider mismatch) and falls back to total_fare for legacy rides predating
    # grand_total. Non-ride PaymentSheet flows keep using body.amount.
    if body.ride_id:
        charge_amount = await _authoritative_ride_charge(body.ride_id, current_user["id"], body.tip_amount)
    else:
        charge_amount = Decimal(str(body.amount))

    try:
        customer_id = await get_or_create_stripe_customer(current_user["id"], stripe_secret)
        amount_cents = dollars_to_cents(charge_amount)

        # EphemeralKey lets the PaymentSheet modal manage the customer's
        # saved cards. api_version must match the version configured on the
        # Stripe webhook endpoint in the dashboard. We pin it to the version
        # bundled with the installed SDK (stripe.api_version) so it stays in
        # sync automatically on SDK upgrades.
        # Current bundled version: 2026-04-22.dahlia (stripe==15.1.0)
        # ACTION REQUIRED on SDK upgrade: verify the Stripe dashboard webhook
        # endpoint API version matches stripe.api_version after upgrading.
        ephemeral_key = stripe.EphemeralKey.create(
            customer=customer_id,
            stripe_version=stripe.api_version,
            api_key=stripe_secret,
        )

        if body.client_idempotency_key:
            idempotency_key = body.client_idempotency_key
        elif body.ride_id:
            # Include the charge amount (cents) so a changed-tip retry gets a
            # distinct key (fresh PI) rather than an IdempotencyError. Same
            # amount → same key → still idempotent.
            idempotency_key = f"ps-{body.ride_id}-{current_user['id']}-{amount_cents}"
        else:
            idempotency_key = f"ps-{current_user['id']}-{int(_time.time() // 60)}"

        intent = stripe.PaymentIntent.create(
            amount=amount_cents,
            currency="cad",
            customer=customer_id,
            automatic_payment_methods={"enabled": True},
            metadata={"user_id": current_user["id"], "ride_id": body.ride_id or ""},
            api_key=stripe_secret,
            idempotency_key=idempotency_key,
        )

        return {
            "paymentIntent": intent.client_secret,
            "ephemeralKey": ephemeral_key.secret,
            "customer": customer_id,
            "publishableKey": stripe_pk,
        }
    except stripe.error.StripeError as e:
        logger.error("Stripe payment-sheet error", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment provider error. Please try again.") from e
    except HTTPException:
        # Intentional 4xx (ownership 403 from _authoritative_ride_charge)
        # must reach the client, not become a 500.
        raise
    except Exception as e:
        logger.error("payment-sheet unexpected error", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e
