import asyncio
from decimal import ROUND_HALF_UP, Decimal
from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

try:
    from .. import db_supabase
    from ..core.config import settings as core_settings
    from ..dependencies import get_current_user
    from ..settings_loader import get_app_settings
    from ..utils.audit_logger import log_user_action as _audit_log_user
    from ..utils.error_handling import (
        ErrorCode,
        PaymentMethodInvalidException,
        SpinrException,
    )
    from ..utils.error_keys import ErrorKeys
    from ..utils.idempotency import idempotent_endpoint
    from ..utils.money import dollars_to_cents
    from ..utils.rate_limiter import payment_action_limit
    from ..utils.stripe_config import STRIPE_API_VERSION
    from ..utils.stripe_mode import is_missing_on_key, key_mode, object_mode, stale_by_mode
except ImportError:
    import db_supabase
    from core.config import settings as core_settings
    from dependencies import get_current_user
    from settings_loader import get_app_settings
    from utils.audit_logger import log_user_action as _audit_log_user
    from utils.error_handling import (
        ErrorCode,
        PaymentMethodInvalidException,
        SpinrException,
    )
    from utils.error_keys import ErrorKeys
    from utils.idempotency import idempotent_endpoint
    from utils.money import dollars_to_cents
    from utils.rate_limiter import payment_action_limit
    from utils.stripe_config import STRIPE_API_VERSION
    from utils.stripe_mode import is_missing_on_key, key_mode, object_mode, stale_by_mode
import logging
from datetime import datetime, timezone

import stripe

logger = logging.getLogger(__name__)
api_router = APIRouter(prefix="/payments", tags=["Payments"])


def _q2(v: Any) -> Decimal:
    """Quantize a money value to 2dp (HALF_UP). Decimal-only — never float."""
    return Decimal(str(v or 0)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


async def _authoritative_ride_charge(ride_id: str, rider_id: str, tip_amount: Decimal) -> Decimal:
    """Server-authoritative amount the rider owes for a ride: grand_total + tip.

    ``grand_total`` already includes area/booking fees and GST/PST; ``total_fare``
    is only the fare-side subtotal. We compute the charge here rather than
    trusting the client-supplied amount so the Stripe (create-intent /
    payment-sheet) paths can never undercharge by omitting fees or tax — the
    same total ``/rides/{id}/process-payment`` settles. Falls back to
    ``total_fare`` only for legacy rides written before ``grand_total`` existed.
    """
    ride = await db_supabase.get_ride(ride_id)
    if not ride:
        raise HTTPException(status_code=404, detail="Ride not found")
    if ride.get("rider_id") != rider_id:
        raise HTTPException(status_code=403, detail="Not authorized to pay for this ride")
    # Explicit None check, not truthiness: a legitimate $0 grand_total (comp /
    # fully-covered ride) must NOT fall through to a non-zero total_fare and
    # overcharge. Only fall back when grand_total was never written (legacy).
    grand_raw = ride.get("grand_total")
    if grand_raw is None:
        grand_raw = ride.get("total_fare", 0)
    grand = _q2(grand_raw)
    return _q2(grand + _q2(tip_amount))


class PaymentIntentRequest(BaseModel):
    """Request body for POST /payments/create-intent."""

    amount: Decimal = Field(..., gt=0, le=100000, decimal_places=2, description="Amount in CAD (1–100000)")
    ride_id: Optional[str] = None
    # Tip is added on top of the ride's grand_total when ride_id is present.
    # For ride payments the server computes the charge as grand_total + tip and
    # ignores `amount` (advisory only) — see _authoritative_ride_charge.
    tip_amount: Decimal = Field(0, ge=0, le=500, decimal_places=2)
    # UUID v4 generated by the mobile client for each new payment attempt.
    # Prevents Stripe idempotency-key collisions when the same user pays
    # the same fare amount on two separate rides within the same 24 h window.
    client_idempotency_key: Optional[str] = None
    payment_method_id: Optional[str] = None


class ConfirmPaymentRequest(BaseModel):
    """Request body for POST /payments/confirm.

    Typed (not a raw dict) so the pi_mock_* production guard and the
    ownership checks below operate on validated, length-bounded strings —
    unknown keys are rejected instead of silently carried along.
    """

    model_config = {"extra": "forbid"}

    payment_intent_id: Optional[str] = Field(None, min_length=1, max_length=255)
    ride_id: Optional[str] = Field(None, min_length=1, max_length=64)


class PaymentSheetRequest(BaseModel):
    """Request body for POST /payments/payment-sheet."""

    amount: Decimal = Field(..., gt=0, le=100000, decimal_places=2, description="Fare amount in CAD")
    ride_id: Optional[str] = None
    # See PaymentIntentRequest.tip_amount — server charges grand_total + tip
    # for ride payments and treats `amount` as advisory.
    tip_amount: Decimal = Field(0, ge=0, le=500, decimal_places=2)
    client_idempotency_key: Optional[str] = None


# ── Stripe identity mode drift (test → live cutover) ──────────────────────
#
# `stripe_secret_key` lives in the app_settings DB table so it can be rotated
# without a redeploy (see CLAUDE.md). Rotating it ACROSS modes
# (`sk_test_…` → `sk_live_…`) silently invalidates every stored
# `users.stripe_customer_id`: Stripe scopes object IDs per mode, so the live
# key cannot see a test-mode customer and answers `resource_missing` on every
# call. Without repair the rider gets a hard 502 on the cards screen forever
# — and cannot add a replacement card either, because attaching one addresses
# the same dead customer.
#
# The rider's test-mode cards are NOT recoverable: they were test PANs and
# never existed as real cards, and Stripe offers no test→live copy path. So
# the honest outcome is a working, empty card list they can add a real card
# to — not a broken screen.
#
# Kill switch: set `stripe_reprovision_stale_ids = false` in app_settings
# (admin-editable, propagates within the 60 s settings cache, no redeploy).
_REPROVISION_FLAG = "stripe_reprovision_stale_ids"


async def _reprovision_stripe_customer(
    user_id: str,
    stale_customer_id: str,
    stripe_secret: str,
    reason: str,
) -> str:
    """Mint a fresh Stripe customer for ``user_id`` and archive the unusable one.

    Only ever called with positive proof that ``stale_customer_id`` is not
    reachable on the running key — either an explicit mode disagreement
    (``stale_by_mode``) or a ``resource_missing`` from Stripe itself
    (``is_missing_on_key``). It is never called on an authentication or
    transient error; ``utils/stripe_mode.py`` documents why that distinction
    is load-bearing (a bad key makes *every* object look missing).
    """
    settings = await get_app_settings()
    if not settings.get(_REPROVISION_FLAG, True):
        # Kill switch engaged: leave the row untouched and fail loudly rather
        # than serving a card list we already know addresses a dead customer.
        logger.error(
            "Stale Stripe customer detected but %s is off — not repairing",
            _REPROVISION_FLAG,
            extra={"user_id": user_id, "reason": reason},
        )
        raise HTTPException(
            status_code=503,
            detail="Your payment profile needs attention. Please contact support.",
        )

    mode = key_mode(stripe_secret)
    customer = await asyncio.to_thread(
        lambda: stripe.Customer.create(
            # PIPEDA (C4): still no email/name to Stripe — only the correlating
            # user_id, plus the superseded ID so the two can be reconciled
            # against the old account without a Spinr-side lookup.
            metadata={"user_id": user_id, "superseded_customer": stale_customer_id},
            api_key=stripe_secret,
            # Deliberately NOT the `cus-create-` key used for a first-time
            # create: replaying that one could hand back the very customer we
            # just proved unusable. Keying on the dead ID makes concurrent
            # healers and retries converge on ONE replacement.
            idempotency_key=f"cus-reprovision-{user_id}-{stale_customer_id}",
        )
    )

    # Conditional write: filtering on the stale value means a concurrent healer
    # that already landed a different customer is not clobbered.
    #
    # `default_payment_method` MUST be cleared in the same write. A `pm_…` is
    # scoped to the customer that owns it, so a token left behind would point
    # settlement (services/payment_service.py:966) and cancellation-fee capture
    # (routes/rides/cancellation.py) at a card that no longer exists — turning
    # a fixed cards screen into failed charges at trip end.
    await db_supabase.update_one(
        "users",
        {"id": user_id, "stripe_customer_id": stale_customer_id},
        {
            "stripe_customer_id": customer.id,
            "stripe_customer_id_mode": mode,
            "stripe_customer_id_superseded": stale_customer_id,
            "stripe_customer_id_superseded_at": datetime.now(timezone.utc).isoformat(),
            "default_payment_method": None,
        },
    )
    # Degraded-but-recovered → warning + metric, per the observability
    # conventions in CLAUDE.md. Stripe IDs are operational identifiers, not
    # PII, so they are safe to log; no email/phone/name appears here.
    logger.warning(
        "Re-provisioned Stripe customer after mode drift",
        extra={
            "user_id": user_id,
            "reason": reason,
            "superseded_customer_id": stale_customer_id,
            "new_customer_id": customer.id,
            "mode": mode,
        },
    )
    _metrics_inc("spinr_payments_stripe_identity_reprovisioned_total", {"surface": "rider", "reason": reason})

    # Re-read so a concurrent healer's winning value is what we return.
    fresh = await db_supabase.get_user_by_id(user_id)
    return (fresh or {}).get("stripe_customer_id") or customer.id


def _metrics_inc(name: str, labels: dict) -> None:
    """Best-effort counter. Metrics must never break a payment path."""
    try:
        try:
            from ..utils import metrics
        except ImportError:
            from utils import metrics  # type: ignore
        metrics.inc(name, labels)
    except Exception:  # pragma: no cover - defensive only
        logger.debug("metric %s not recorded", name, exc_info=True)


async def get_or_create_stripe_customer(user_id: str, stripe_secret: str):
    """Return the user's Stripe customer id, creating it on first use.

    Adds no Stripe round-trip for an existing customer. A row whose stamped
    mode disagrees with the running key is repaired here, from the stamp
    alone; an *unstamped* stale row (everything predating migration 286) is
    repaired the other way, by :func:`with_customer_repair` catching the
    ``resource_missing`` from the call that actually fails.
    """
    user = await db_supabase.get_user_by_id(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    stripe_customer_id = user.get("stripe_customer_id")

    if stripe_customer_id:
        # Cheap path: the row is stamped and the stamp disagrees with the key.
        # No Stripe call is needed to know the id is unusable.
        if stale_by_mode(user.get("stripe_customer_id_mode"), key_mode(stripe_secret)):
            return await _reprovision_stripe_customer(
                user_id, stripe_customer_id, stripe_secret, reason="mode_mismatch"
            )
        return stripe_customer_id

    # PIPEDA (C4): do NOT send the rider's email or legal name to Stripe (a
    # US processor). Neither is required to create a customer — only
    # metadata.user_id is needed to correlate the Stripe customer back to
    # our user. Avoiding the transfer keeps PII inside the Canadian region;
    # contact details can be attached later only if a specific Stripe flow
    # (e.g. a dispute) actually requires them.
    customer = await asyncio.to_thread(
        lambda: stripe.Customer.create(
            metadata={"user_id": user_id},
            api_key=stripe_secret,
            idempotency_key=f"cus-create-{user_id}",
        )
    )
    stripe_customer_id = customer.id
    # Stamp the mode from the object Stripe returned (its own `livemode`), not
    # from the key we sent — evidence over inference. This is what lets a
    # future key rotation be detected without a Stripe round-trip.
    await db_supabase.update_one(
        "users",
        {"id": user_id},
        {
            "stripe_customer_id": stripe_customer_id,
            "stripe_customer_id_mode": object_mode(customer) or key_mode(stripe_secret),
        },
    )
    # Re-read to use the authoritative value in case a concurrent replica wrote first.
    # (The loser's Stripe customer is unused but harmless; deduplication can run offline.)
    fresh = await db_supabase.get_user_by_id(user_id)
    if not fresh:
        raise HTTPException(status_code=404, detail="User not found during Stripe customer creation")
    # Never hand back a falsy customer id: callers pass it straight to Stripe,
    # where `customer=None` silently creates an unattached object rather than
    # erroring. Raising here keeps that invariant in one place instead of
    # repeating a defensive check at each call site.
    persisted = fresh.get("stripe_customer_id")
    if not persisted:
        logger.error("Stripe customer create persisted no id", extra={"user_id": user_id})
        raise HTTPException(status_code=502, detail="Could not set up payments. Please try again.")
    return persisted


async def with_customer_repair(user_id: str, stripe_secret: str, op):
    """Run ``await op(customer_id)``, repairing a stranded customer once.

    The repair trigger is the failure itself: if Stripe answers
    ``resource_missing`` for the customer we addressed, that id is not on this
    key (the test→live rotation case), so we mint a replacement and run ``op``
    against it. Any other error — auth, rate limit, connection, card decline —
    propagates untouched and writes nothing; see ``utils/stripe_mode.py`` for
    why that line matters.

    Costs nothing on the healthy path: no extra round-trip, no extra read.
    """
    customer_id = await get_or_create_stripe_customer(user_id, stripe_secret)
    try:
        return customer_id, await op(customer_id)
    except Exception as e:
        if not is_missing_on_key(e, customer_id):
            raise
        repaired = await _reprovision_stripe_customer(
            user_id, customer_id, stripe_secret, reason="resource_missing"
        )
        # One retry only. If the fresh customer also 404s, something is wrong
        # with the key or the account, not with this row — let it surface.
        return repaired, await op(repaired)


@api_router.post("/create-intent")
@payment_action_limit
@idempotent_endpoint(scope="payment_intent")
async def create_payment_intent(
    body: PaymentIntentRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Create a Stripe payment intent.

    `amount` is validated by Pydantic (positive, ≤ 100000 CAD) before we
    reach Stripe. Rejecting at the boundary gives a 422 response on bad
    input instead of a 500 after Stripe refuses it.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        raise HTTPException(
            status_code=503,
            detail="Payment processing is not configured. Please contact support.",
        )

    try:
        # For ride payments the server is authoritative on the amount: charge
        # grand_total + tip (the full rider-owed total incl. area fees + GST/PST),
        # not the client-supplied figure. This closes an undercharge where the
        # client sent only total_fare (fare minus fees/tax) and the tax went
        # uncollected — and mirrors what /rides/{id}/process-payment settles.
        charge_amount = Decimal(str(body.amount))
        if body.ride_id:
            charge_amount = await _authoritative_ride_charge(body.ride_id, current_user["id"], body.tip_amount)

        # Decimal-safe dollars→cents (HALF_UP). ``int(amount * 100)``
        # would undercharge by 1¢ on values like $0.29, $1.13, $17.81 due
        # to binary-float drift. See backend/utils/money.py.
        amount = dollars_to_cents(charge_amount)

        intent_params = {
            "amount": amount,
            "currency": "cad",
            "automatic_payment_methods": {"enabled": True},
            "metadata": {"user_id": current_user["id"], "ride_id": body.ride_id or ""},
        }

        if body.payment_method_id:
            intent_params["payment_method"] = body.payment_method_id

        # Idempotency key ties this PaymentIntent to a specific ride so a
        # network retry cannot create a duplicate charge (P2-8 / DV-4).
        # Priority: client-supplied UUID (most specific) > ride-scoped key
        # (safe: ride IDs are globally unique) > 1-minute time-bucket per user
        # (last resort when ride_id absent — prevents same-amount collisions
        # that occurred with the old "intent-{user}-{amount}" pattern).
        import time as _time

        if body.client_idempotency_key:
            idempotency_key = body.client_idempotency_key
        elif body.ride_id:
            # Include the charge amount (cents) so that if the rider changes
            # their tip and retries, Stripe sees a distinct key and creates a
            # fresh PaymentIntent instead of raising IdempotencyError on the
            # amount mismatch. Same amount → same key → still idempotent.
            idempotency_key = f"ride-{body.ride_id}-{current_user['id']}-{amount}"
        else:
            idempotency_key = f"intent-{current_user['id']}-{int(_time.time() // 60)}"
        # Sync Stripe SDK: threadpool so the round-trip doesn't block the
        # event loop (idempotency key makes retries safe).
        #
        # Wrapped in the repair helper because this is the authoritative
        # ride-charge path: a rider whose customer was stranded by a key
        # rotation and who never opened the cards screen (so was never healed
        # there) would otherwise hit a hard failure at trip end, with a
        # completed ride and no way to pay for it. The idempotency key carries
        # the customer so the repaired retry cannot collide with the first
        # attempt's key.
        async def _create_intent(cid: str):
            return await asyncio.to_thread(
                lambda: stripe.PaymentIntent.create(
                    **{**intent_params, "customer": cid},
                    api_key=stripe_secret,
                    idempotency_key=f"{idempotency_key}-{cid}",
                )
            )

        _customer_id, intent = await with_customer_repair(current_user["id"], stripe_secret, _create_intent)

        # 3-D Secure / SCA happy-path: PaymentIntent succeeded at the API
        # boundary but Stripe is asking the rider to complete an additional
        # authentication step (3DS challenge). The mobile SDK reads
        # `client_secret` + `next_action` to drive the flow. We surface this
        # as a 402 with `code='action_required'` so the rider app branches
        # into Stripe's handleNextAction() rather than treating it as
        # success and confirming the payment server-side.
        if getattr(intent, "status", None) == "requires_action":
            return JSONResponse(
                status_code=402,
                content={
                    "success": False,
                    "detail": "Additional authentication required",
                    "error": {
                        "code": ErrorCode.PAYMENT_METHOD_INVALID.value,
                        "message": "Additional authentication required",
                        "message_key": ErrorKeys.PAYMENT_METHOD_INVALID,
                        "details": {
                            "code": "action_required",
                            "client_secret": intent.client_secret,
                            "payment_intent_id": intent.id,
                            "next_action": getattr(intent, "next_action", None),
                        },
                    },
                },
            )

        return {
            "client_secret": intent.client_secret,
            "payment_intent_id": intent.id,
            "mock": False,
        }
    except stripe.error.CardError as e:
        # Order matters: CardError must come BEFORE the generic StripeError
        # branch (Python checks except clauses top-down, and CardError is a
        # StripeError subclass). Card-decline / wrong-CVC / expired-card all
        # land here and must surface as 402 so the rider SDK switches to
        # the "try another card" UX. 3-D Secure challenges raised
        # synchronously (rare; the success-path handler above is the common
        # route) appear as code='authentication_required' and we forward
        # that to the SDK as code='action_required'.
        logger.error(f"Stripe CardError on create-intent: {e}", exc_info=True)
        details: Dict[str, Any] = {}
        if getattr(e, "code", None) == "authentication_required":
            details["code"] = "action_required"
        raise PaymentMethodInvalidException(
            message=getattr(e, "user_message", None) or "Card declined",
            message_key=ErrorKeys.PAYMENT_METHOD_INVALID,
            status_code=402,
            action_hint="Add a different card",
            details=details or None,
        ) from e
    except stripe.error.RateLimitError as e:
        # Stripe is throttling us. 429 with Retry-After lets the rider
        # app's Axios interceptor back off rather than retrying instantly.
        # We use SpinrException directly (not RateLimitExceededException)
        # to keep the response shape identical to the OTP-lockout 429
        # handler — same parser on the mobile side.
        logger.error(f"Stripe RateLimitError on create-intent: {e}", exc_info=True)
        raise SpinrException(
            message="Payment provider is rate-limiting requests. Please try again shortly.",
            error_code=ErrorCode.RATE_LIMIT_EXCEEDED,
            status_code=429,
            headers={"Retry-After": "30"},
            action_hint="Try again in a moment",
        ) from e
    except stripe.error.StripeError as e:
        logger.error(f"Stripe API error on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment service unavailable. Please try again.") from e
    except HTTPException:
        # Intentional 4xx (ownership 403, validation 400) from helpers like
        # _authoritative_ride_charge must reach the client, not become a 500.
        raise
    except Exception as e:
        logger.error(f"Unexpected error on create-intent: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/confirm")
@payment_action_limit
@idempotent_endpoint(scope="payment_confirm")
async def confirm_payment(
    body: ConfirmPaymentRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Confirm payment was successful"""
    payment_intent_id = body.payment_intent_id
    ride_id = body.ride_id

    # Mock-payment shortcut is allowed only outside production, OR for an
    # allow-listed app-store reviewer account (so a reviewer can reach a "paid"
    # confirmation without a real charge). Reject everyone else up front —
    # before claiming the ride into payment_status=processing — so a rejected
    # request can't strand the ride. In production any other authenticated rider
    # could otherwise send "pi_mock_*" and settle their own ride for free.
    _is_reviewer = current_user.get("phone") in core_settings.review_login_map()
    if (
        payment_intent_id
        and payment_intent_id.startswith("pi_mock_")
        and core_settings.ENV.lower() == "production"
        and not _is_reviewer
    ):
        logger.error(
            "Rejected mock payment intent %s in production for ride %s",
            payment_intent_id,
            ride_id,
        )
        raise HTTPException(
            status_code=400,
            detail="Mock payments are not supported in production",
        )

    is_mock = bool(payment_intent_id and payment_intent_id.startswith("pi_mock_"))
    # Bound unconditionally so the Stripe call below never references an unbound
    # name; the real value is assigned in the non-mock processor gate, which 503s
    # if it is still empty (so this default never reaches stripe.PaymentIntent).
    stripe_secret = ""

    if ride_id:
        ride = await db_supabase.get_ride(ride_id)
        if not ride:
            raise HTTPException(status_code=404, detail="Ride not found")
        if ride["rider_id"] != current_user["id"]:
            raise HTTPException(status_code=403, detail="forbidden")

        # C-3: Idempotency check — if a prior webhook already settled this payment,
        # return early with a clear signal rather than re-entering the Stripe flow.
        # This covers the case where the rider app retries confirm_payment after a
        # network timeout when the webhook has already processed the payment.
        # HTTP 200 (not 409) because the payment succeeded — this is not an error.
        payment_status = ride.get("payment_status")
        if payment_status in ("paid", "processing"):
            logger.info(
                "confirm_payment: ride %s already in payment_status=%s, returning early (C-3 idempotency)",
                ride_id,
                payment_status,
            )
            return {"status": "already_processed", "payment_status": payment_status}

    # Processor-availability gate (C1): a non-mock confirm with no Stripe secret
    # must NOT settle a ride. The key can be transiently empty during rotation;
    # returning a success shape would mark a ride paid with no real charge.
    # Placed AFTER ownership/idempotency (a non-owner still gets 403) but BEFORE
    # the claim, so a transiently-empty key can't strand the ride in
    # payment_status='processing'. Mirrors create_payment_intent's 503.
    if not is_mock:
        settings = await get_app_settings()
        stripe_secret = settings.get("stripe_secret_key", "")
        if not stripe_secret:
            raise HTTPException(
                status_code=503,
                detail="Payment processing is not configured. Please contact support.",
            )

    if ride_id:
        claimed = await db_supabase.claim_ride_payment_processing(ride_id)
        if not claimed:
            raise HTTPException(status_code=409, detail="payment_already_processing")

    # Mock-payment shortcut (non-production only; production rejected above).
    if is_mock:
        if ride_id:
            _ride = await db_supabase.get_ride(ride_id)
            if not _ride or _ride.get("rider_id") != current_user["id"]:
                raise HTTPException(
                    status_code=403,
                    detail="Not authorized to confirm payment for this ride",
                )
            await db_supabase.update_ride(
                ride_id,
                {"payment_status": "paid", "payment_intent_id": payment_intent_id},
            )
        return {"status": "succeeded", "mock": True}

    # Non-mock path: stripe_secret is guaranteed non-empty (gated above), so we
    # never reach the old success-shaped fallback — a missing processor already
    # raised 503 before the claim.
    try:
        intent = await asyncio.to_thread(
            lambda: stripe.PaymentIntent.retrieve(payment_intent_id, api_key=stripe_secret)
        )

        if intent.metadata.get("user_id") != str(current_user["id"]):
            raise HTTPException(status_code=403, detail="Not authorized to confirm this payment")

        if ride_id:
            _ride = await db_supabase.get_ride(ride_id)
            if not _ride or _ride.get("rider_id") != current_user["id"]:
                raise HTTPException(
                    status_code=403,
                    detail="Not authorized to confirm payment for this ride",
                )

            # SECURITY (C1): ownership alone is insufficient — a rider owns
            # many PaymentIntents. Bind the PI to THIS ride and verify it
            # actually covers the owed total, or a rider could confirm a
            # cheap / other-ride intent against an expensive ride and underpay.
            pi_ride_id = (intent.metadata or {}).get("ride_id")
            if pi_ride_id and pi_ride_id != ride_id:
                logger.error(
                    "[confirm][security] PI %s metadata ride_id=%s != ride %s",
                    payment_intent_id,
                    pi_ride_id,
                    ride_id,
                )
                raise HTTPException(status_code=403, detail="Payment does not match this ride")

            # Only a genuinely succeeded charge can mark a ride paid, and only
            # when the captured amount covers the authoritative owed total
            # (grand_total). amount_received is 0 until the PI succeeds.
            if intent.status == "succeeded":
                _grand = _ride.get("grand_total")
                if _grand is None:
                    _grand = _ride.get("total_fare", 0)
                owed_cents = int((_q2(_grand) * 100).to_integral_value())
                received = int(getattr(intent, "amount_received", 0) or 0)
                if received < owed_cents:
                    logger.error(
                        "[confirm][security] underpay ride=%s pi=%s received=%d owed=%d",
                        ride_id,
                        payment_intent_id,
                        received,
                        owed_cents,
                    )
                    raise HTTPException(
                        status_code=402,
                        detail={
                            "code": "AMOUNT_MISMATCH",
                            "message": "Payment amount does not cover the fare.",
                        },
                    )

            await db_supabase.update_ride(
                ride_id,
                {
                    "payment_status": intent.status,
                    "payment_intent_id": payment_intent_id,
                },
            )

        return {"status": intent.status, "mock": False}
    except HTTPException:
        # Ownership 403s above must reach the client, not become a 500.
        raise
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/setup-intent")
@payment_action_limit
async def create_setup_intent(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Create a SetupIntent to save a new payment method"""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        return {"client_secret": "mock_setup_secret", "mock": True}

    try:
        import time as _time

        async def _create_si(cid: str):
            return await asyncio.to_thread(
                lambda: stripe.SetupIntent.create(
                    customer=cid,
                    payment_method_types=["card"],
                    api_key=stripe_secret,
                    idempotency_key=f"setup-intent-{current_user['id']}-{cid}-{int(_time.time() // 60)}",
                )
            )

        # Repairs a customer stranded by a test→live key rotation before the
        # rider is handed a client_secret that could never confirm.
        customer_id, setup_intent = await with_customer_repair(current_user["id"], stripe_secret, _create_si)

        return {
            "client_secret": setup_intent.client_secret,
            "setup_intent_id": setup_intent.id,
            "customer_id": customer_id,
            "mock": False,
        }
    except HTTPException:
        # Deliberate status codes raised inside the try — the customer-setup
        # 502 and the re-provision kill switch's 503 — must reach the client
        # as themselves, not be relabelled 500 by the catch-all below.
        raise
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.get("/methods")
@payment_action_limit
async def get_payment_methods(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Get saved payment methods for the user"""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        return {"methods": [], "mock": True}

    try:
        user = await db_supabase.get_user_by_id(current_user["id"])
        stripe_customer_id = user.get("stripe_customer_id") if user else None

        if not stripe_customer_id:
            return {"methods": [], "mock": False}

        # Repair-on-failure: a customer stranded by a test→live key rotation
        # would otherwise raise `resource_missing` here and 500 forever.
        async def _list(cid: str):
            return await asyncio.to_thread(
                lambda: stripe.PaymentMethod.list(customer=cid, type="card", api_key=stripe_secret)
            )

        _, methods = await with_customer_repair(current_user["id"], stripe_secret, _list)

        return {
            "methods": [
                {
                    "id": m.id,
                    "brand": m.card.brand,
                    "last4": m.card.last4,
                    "exp_month": m.card.exp_month,
                    "exp_year": m.card.exp_year,
                }
                for m in methods.data
            ],
            "mock": False,
        }
    except HTTPException:
        # Deliberate status codes raised inside the try (e.g. the 503 the
        # re-provision kill switch raises) must reach the client as themselves,
        # not be relabelled 500 by the catch-all below.
        raise
    except Exception as e:
        logger.error(f"Stripe error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


# ─── Cards CRUD via Stripe ───


@api_router.get("/cards")
@payment_action_limit
async def get_cards(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Get user's saved cards from Stripe. Last4, brand, expiry all from Stripe."""
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        # The Stripe key lives in the app_settings DB table (not env), so startup
        # cannot fail-fast on it. In production an empty key is a misconfiguration,
        # NOT demo mode — never hand a real rider the demo card (a pm_demo_card
        # would later fail at settlement once the key is restored). Surface 503 so
        # the client retries and ops notice.
        if core_settings.ENV.lower() == "production":
            logger.error("get_cards: stripe_secret_key empty in production — refusing to serve demo card")
            raise HTTPException(status_code=503, detail="Payments temporarily unavailable. Please try again.")
        # Demo/local/staging mode (Stripe intentionally unconfigured): return a
        # single selectable demo card so the booking flow has a payment method to
        # attach. Settlement goes through charge_ride's "unconfigured" path, which
        # marks the ride paid without a real charge.
        return [
            {
                "id": "pm_demo_card",
                "brand": "Demo",
                "last4": "0000",
                "exp_month": 12,
                "exp_year": 2099,
                "is_default": True,
                "cardholder_name": None,
            }
        ]

    try:

        async def _list(cid: str):
            return await asyncio.to_thread(
                lambda: stripe.PaymentMethod.list(customer=cid, type="card", api_key=stripe_secret)
            )

        # Repair-on-failure: after a test→live key rotation the stored customer
        # is invisible to the live key. Rather than 502ing the cards screen
        # forever, mint a live customer and list against it — which correctly
        # returns an empty list the rider can add a real card to. Their
        # test-mode cards are not recoverable; they were never real cards.
        _, methods = await with_customer_repair(current_user["id"], stripe_secret, _list)
        user = await db_supabase.get_user_by_id(current_user["id"])
        default_pm = user.get("default_payment_method") if user else None
        return [
            {
                "id": m.id,
                "brand": m.card.brand.capitalize(),
                "last4": m.card.last4,
                "exp_month": m.card.exp_month,
                "exp_year": m.card.exp_year,
                "is_default": m.id == default_pm,
                # Cardholder name entered at add-time (Stripe billing_details).
                # May be absent for cards saved via flows that don't collect it.
                "cardholder_name": (getattr(m, "billing_details", None) and m.billing_details.name) or None,
            }
            for m in methods.data
        ]
    except HTTPException:
        # Preserve deliberate status codes raised inside the try (the
        # re-provision kill switch's 503) instead of relabelling them 502.
        raise
    except Exception as e:
        # C7: do NOT mask a Stripe outage as "no cards" — that's the log-and-
        # continue-on-payment-error anti-pattern CLAUDE.md forbids, and it makes
        # a rider think their saved card vanished. Surface 502 so the client retries.
        logger.error(f"Get cards error: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Could not load your saved cards. Please try again.") from e


class AddCardRequest(BaseModel):
    """Add-card request body.

    Accepts only a Stripe `payment_method_id` created client-side via
    Stripe.js or @stripe/stripe-react-native. Raw card fields (PAN, CVC,
    expiry) must NEVER flow through the backend — accepting them puts
    the server in PCI-DSS SAQ-D scope. See AUDIT C-PAY-01.
    """

    payment_method_id: str = Field(..., min_length=1, max_length=128)


# Field names that indicate the caller sent raw card data (PAN/CVV/expiry).
# If ANY of these are present in the request body, we refuse to process
# the request at all — before any logging, before JSON parsing by pydantic,
# before touching Stripe. This is the PCI-DSS perimeter.
_RAW_CARD_FIELDS = {
    "card_number",
    "cardNumber",
    "card_no",
    "number",
    "pan",
    "primary_account_number",
    "cvv",
    "cvv2",
    "cvc",
    "cvc2",
    "security_code",
    "card_security_code",
    "expiry",
    "expiration",
    "expiration_date",
    "exp_month",
    "exp_year",
}


@api_router.post("/cards")
@payment_action_limit
async def add_card(request: Request = None, current_user: dict = Depends(get_current_user)):
    """Add a saved card. Requires client-side tokenization.

    Contract:
      - Body must be ``{"payment_method_id": "pm_..."}``.
      - Body must NOT contain any raw-card fields (PAN, CVC, expiry).
      - If stripe_secret_key is unset (demo mode), a fake record is
        returned with a random last4 — the payment_method_id is still
        required for contract parity so the mobile app integrates with
        a single API shape across environments.

    PCI-DSS note: we deliberately raise a plain 400 BEFORE reading the
    full JSON for logging/metrics so an attacker probing the endpoint
    with a PAN does not get it persisted in access logs. The error
    response intentionally does NOT echo the offending keys back.
    """
    # Parse once; reject immediately if the body shape hints at raw card data.
    try:
        data = await request.json()
    except Exception as exc:
        raise HTTPException(status_code=400, detail="Invalid JSON body") from exc

    if not isinstance(data, dict):
        raise HTTPException(status_code=400, detail="Body must be a JSON object")

    forbidden = _RAW_CARD_FIELDS.intersection(data.keys())
    if forbidden:
        # Log that a raw-card POST was attempted but DO NOT log the keys'
        # values. The client needs tokenization; tell them where to look.
        logger.error(
            f"Rejected raw-card POST to /payments/cards from user={current_user.get('id')}: {sorted(forbidden)} present"
        )
        raise HTTPException(
            status_code=400,
            detail=(
                "Raw card data is not accepted. Tokenize card details "
                "client-side using Stripe.js / @stripe/stripe-react-native "
                "and submit only {'payment_method_id': 'pm_...'}."
            ),
        )

    # Validate the allowed shape. Pydantic rejects missing / wrong types with 422.
    try:
        body = AddCardRequest(**data)
    except Exception as exc:
        # B-P3-leak-cleanup: don't interpolate the Pydantic exception
        # repr (which can include field paths and request structure
        # hints). 400 is a 4xx so the framework sanitiser does not
        # rescue this — manual cleanup matters. Body-shape errors
        # should reach clients via FastAPI's RequestValidationError
        # path normally; this except block is the fallback for the
        # ad-hoc dict-driven payload here.
        logger.error("AddCardRequest validation failed", exc_info=exc)
        raise HTTPException(
            status_code=400,
            detail="Invalid request payload.",
        ) from exc

    payment_method_id = body.payment_method_id

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    if not stripe_secret:
        # Demo mode — fabricate a response. Requires payment_method_id for
        # shape parity with production so mobile has one integration path.
        logger.info(f"[DEMO] Card added via {payment_method_id[:8]}...")
        return {
            "id": payment_method_id,
            "brand": "Visa",
            "last4": "4242",
            "exp_month": 12,
            "exp_year": 2030,
            "is_default": True,
        }

    try:
        # Attach the client-tokenized PaymentMethod to the customer.
        # The PAN never touched our server — the token came from Stripe.js.
        #
        # Wrapped in the repair helper because this is the endpoint a rider
        # reaches when trying to recover from the cutover: attaching to a
        # customer the live key cannot see fails `resource_missing`, which
        # without repair leaves them permanently unable to add ANY card.
        async def _attach(cid: str):
            return await asyncio.to_thread(
                lambda: stripe.PaymentMethod.attach(payment_method_id, customer=cid, api_key=stripe_secret)
            )

        customer_id, pm = await with_customer_repair(current_user["id"], stripe_secret, _attach)

        # Confirm with SetupIntent — saves card for future off-session use.

        si = await asyncio.to_thread(
            lambda: stripe.SetupIntent.create(
                customer=customer_id,
                payment_method=pm.id,
                confirm=True,
                automatic_payment_methods={"enabled": True, "allow_redirects": "never"},
                api_key=stripe_secret,
                idempotency_key=f"setup-card-{current_user['id']}-{pm.id}",
            )
        )

        # Set as default if first card
        user = await db_supabase.get_user_by_id(current_user["id"])
        if not user.get("default_payment_method"):
            await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": pm.id})
            await asyncio.to_thread(
                lambda: stripe.Customer.modify(
                    customer_id,
                    invoice_settings={"default_payment_method": pm.id},
                    api_key=stripe_secret,
                )
            )

        logger.info(f"Card added: {pm.card.brand} ****{pm.card.last4} | SetupIntent: {si.id} ({si.status})")

        return {
            "id": pm.id,
            "brand": pm.card.brand.capitalize(),
            "last4": pm.card.last4,
            "exp_month": pm.card.exp_month,
            "exp_year": pm.card.exp_year,
            "is_default": not bool(user.get("default_payment_method")),
            "setup_intent_id": si.id,
            "setup_intent_status": si.status,
        }
    except stripe.error.CardError as e:
        raise PaymentMethodInvalidException(
            message=e.user_message or "Card declined",
            message_key=ErrorKeys.PAYMENT_METHOD_INVALID,
            action_hint="Add a different card",
        ) from e
    except stripe.error.StripeError as e:
        logger.error(f"Stripe API error on add-card: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment service unavailable. Please try again.") from e
    except HTTPException:
        # Preserve deliberate status codes raised inside the try (the
        # re-provision kill switch's 503).
        raise
    except Exception as e:
        logger.error(f"Unexpected error on add-card: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e


@api_router.post("/cards/{card_id}/default")
@payment_action_limit
async def set_default_card(
    card_id: str,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Set card as default. Updates both our DB and Stripe customer.

    C7: Stripe is updated FIRST; the DB default is only written once Stripe
    accepts it, so a Stripe failure can't leave our DB pointing at a default the
    payment processor doesn't know about. On Stripe error we surface 502 (not a
    silent success) so the client retries.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    user = await db_supabase.get_user_by_id(current_user["id"])
    if stripe_secret:
        try:
            cid = user.get("stripe_customer_id") if user else None
            if cid:
                # WS-18: verify the card belongs to this customer before
                # promoting it to default. Stripe scopes the modify to the
                # customer, but an explicit ownership check prevents a
                # confusing error surface and guards the non-Stripe fallback.
                methods = await asyncio.to_thread(
                    lambda: stripe.PaymentMethod.list(customer=cid, type="card", api_key=stripe_secret)
                )
                if card_id not in [m.id for m in methods.data]:
                    raise HTTPException(status_code=404, detail="Card not found")
                await asyncio.to_thread(
                    lambda: stripe.Customer.modify(
                        cid,
                        invoice_settings={"default_payment_method": card_id},
                        api_key=stripe_secret,
                    )
                )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"Stripe set default failed for card {card_id}: {e}", exc_info=True)
            raise HTTPException(status_code=502, detail="Could not update your default card. Please try again.") from e
    else:
        # WS-18: without Stripe, verify card_id matches the user's existing
        # payment method. Accepting arbitrary strings here would let any
        # caller write garbage into their own default_payment_method field.
        if not user or user.get("default_payment_method") != card_id:
            saved = user.get("saved_payment_methods") if user else None
            if not saved or card_id not in (saved if isinstance(saved, list) else []):
                raise HTTPException(status_code=404, detail="Card not found")

    await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": card_id})

    asyncio.create_task(
        _audit_log_user(
            current_user,
            "default_payment_method_set",
            "users",
            current_user["id"],
            {"card_id": card_id},
        )
    )
    return {"success": True}


@api_router.delete("/cards/{card_id}")
@payment_action_limit
async def delete_card(
    card_id: str,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Detach card from Stripe and re-point the default if needed.

    C7: the Stripe detach must SUCCEED before we mutate our DB. Previously a
    failed detach was logged-and-ignored, then the DB default was cleared anyway
    — leaving the card live in Stripe but gone from the UI. Now a failed detach
    raises 502 and the DB is left untouched.

    Last-card guard: the user must always keep at least one card on file, so
    removing their only card is refused with 409 — they add another card first.

    Default reassignment: when the removed card was the default (and, per the
    guard above, at least one other card remains) the most recently added
    remaining card is auto-promoted to default in both Stripe and our DB, so the
    user is never left with saved cards but no default to charge.
    """
    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")

    # Read the user once up front so we know whether this is the default card
    # BEFORE mutating anything in Stripe.
    user = await db_supabase.get_user_by_id(current_user["id"])
    is_default = bool(user and user.get("default_payment_method") == card_id)
    customer_id = user.get("stripe_customer_id") if user else None

    # Enumerate saved cards up front — used both to block removing the last card
    # and to pick the replacement default. Stripe returns most-recent-first.
    saved_ids: list[str] = []
    if stripe_secret and customer_id:
        try:
            methods = await asyncio.to_thread(
                lambda: stripe.PaymentMethod.list(customer=customer_id, type="card", api_key=stripe_secret)
            )
            saved_ids = [m.id for m in methods.data]
        except Exception as e:
            logger.error(f"delete_card: could not list cards ({card_id}): {e}", exc_info=True)
            raise HTTPException(status_code=502, detail="Could not remove your card. Please try again.") from e

        # Keep at least one card on file.
        if len(saved_ids) <= 1:
            raise HTTPException(
                status_code=409,
                detail="You need at least one card on file. Add another card before removing this one.",
            )

    # WS-18: verify the card belongs to this user before detaching.
    # Without this, an attacker who knows another user's pm_... ID can
    # detach it using the platform secret key.
    if stripe_secret:
        if card_id not in saved_ids:
            raise HTTPException(status_code=404, detail="Card not found")
        try:
            await asyncio.to_thread(lambda: stripe.PaymentMethod.detach(card_id, api_key=stripe_secret))
        except Exception as e:
            logger.error(f"Stripe detach failed for card {card_id}: {e}", exc_info=True)
            raise HTTPException(status_code=502, detail="Could not remove your card. Please try again.") from e

    if not is_default:
        return {"success": True}

    # The default card was removed — promote the most recently added remaining
    # card (guard above guarantees at least one exists when Stripe is configured).
    new_default: str | None = next((cid for cid in saved_ids if cid != card_id), None)
    if new_default and stripe_secret and customer_id:
        try:
            await asyncio.to_thread(
                lambda: stripe.Customer.modify(
                    customer_id,
                    invoice_settings={"default_payment_method": new_default},
                    api_key=stripe_secret,
                )
            )
        except Exception as e:
            logger.error(f"delete_card: could not set new default {new_default} in Stripe: {e}", exc_info=True)
            raise HTTPException(status_code=502, detail="Could not remove your card. Please try again.") from e

    # Point our DB at the promoted card (or clear it when Stripe is unconfigured).
    await db_supabase.update_one("users", {"id": current_user["id"]}, {"default_payment_method": new_default})

    return {"success": True}


@api_router.post("/payment-sheet")
@payment_action_limit
async def create_payment_sheet(
    body: PaymentSheetRequest,
    request: Request = None,
    current_user: dict = Depends(get_current_user),
):
    """Return the three secrets needed to initialise Stripe PaymentSheet.

    The mobile client calls initPaymentSheet({ paymentIntent, ephemeralKey,
    customer }) then presentPaymentSheet() to complete the payment in a
    pre-built Stripe modal that supports Google Pay and Apple Pay without
    any card-form UI on our side.

    Returns:
        paymentIntent:  PaymentIntent client_secret
        ephemeralKey:   EphemeralKey secret (scoped to this customer)
        customer:       Stripe customer ID
        publishableKey: App should already have this; included for convenience
    """
    import time as _time

    settings = await get_app_settings()
    stripe_secret = settings.get("stripe_secret_key", "")
    stripe_pk = settings.get("stripe_publishable_key", "")

    if not stripe_secret:
        raise HTTPException(
            status_code=503,
            detail="Payment processing is not configured. Please contact support.",
        )

    # CS-002: For ride payments use the server-authoritative charge
    # (grand_total + tip) rather than trusting body.amount. body.amount is
    # advisory only — a client can send a lower value to underpay area fees,
    # GST/PST, or tip. _authoritative_ride_charge enforces ownership (403 on
    # rider mismatch) and falls back to total_fare for legacy rides predating
    # grand_total. Non-ride PaymentSheet flows keep using body.amount.
    if body.ride_id:
        charge_amount = await _authoritative_ride_charge(body.ride_id, current_user["id"], body.tip_amount)
    else:
        charge_amount = Decimal(str(body.amount))

    try:
        amount_cents = dollars_to_cents(charge_amount)

        # EphemeralKey lets the PaymentSheet modal manage the customer's
        # saved cards. stripe_version must match the version configured on the
        # Stripe webhook endpoint in the dashboard. Use the single pinned
        # STRIPE_API_VERSION from utils/stripe_config — NOT stripe.api_version,
        # which only equals the pin after configure_stripe() has run and
        # otherwise silently falls back to the SDK's bundled version.
        # ACTION REQUIRED when bumping STRIPE_API_VERSION: update the Stripe
        # dashboard webhook endpoint API version to match.
        #
        # EphemeralKey is the first customer-addressed call in this handler, so
        # it is where a customer stranded by a test→live key rotation surfaces.
        # Repairing here means the PaymentSheet opens (with no saved cards)
        # instead of the rider hitting a dead end at payment time.
        async def _ephemeral(cid: str):
            return await asyncio.to_thread(
                lambda: stripe.EphemeralKey.create(
                    customer=cid,
                    stripe_version=STRIPE_API_VERSION,
                    api_key=stripe_secret,
                )
            )

        customer_id, ephemeral_key = await with_customer_repair(current_user["id"], stripe_secret, _ephemeral)

        if body.client_idempotency_key:
            idempotency_key = body.client_idempotency_key
        elif body.ride_id:
            # Include the charge amount (cents) so a changed-tip retry gets a
            # distinct key (fresh PI) rather than an IdempotencyError. Same
            # amount → same key → still idempotent.
            idempotency_key = f"ps-{body.ride_id}-{current_user['id']}-{amount_cents}"
        else:
            idempotency_key = f"ps-{current_user['id']}-{int(_time.time() // 60)}"

        intent = await asyncio.to_thread(
            lambda: stripe.PaymentIntent.create(
                amount=amount_cents,
                currency="cad",
                customer=customer_id,
                automatic_payment_methods={"enabled": True},
                metadata={"user_id": current_user["id"], "ride_id": body.ride_id or ""},
                api_key=stripe_secret,
                idempotency_key=idempotency_key,
            )
        )

        return {
            "paymentIntent": intent.client_secret,
            "ephemeralKey": ephemeral_key.secret,
            "customer": customer_id,
            "publishableKey": stripe_pk,
        }
    except stripe.error.StripeError as e:
        logger.error("Stripe payment-sheet error", exc_info=True)
        raise HTTPException(status_code=502, detail="Payment provider error. Please try again.") from e
    except HTTPException:
        # Intentional 4xx (ownership 403 from _authoritative_ride_charge)
        # must reach the client, not become a 500.
        raise
    except Exception as e:
        logger.error("payment-sheet unexpected error", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred. Please try again.") from e
