"""Supabase database access layer.

Shared infrastructure (run_sync, circuit breaker, generic CRUD, cache)
lives in repositories/_base.py.  This module re-exports everything from
_base so the 40+ existing callers continue to resolve, and adds
domain-specific helpers that will migrate to individual repository
modules in subsequent phases.
"""

try:
    from .repositories._base import (  # noqa: F401 — re-exported
        _DB_EXECUTOR,
        _DRIVER_BY_USER_CACHE_TTL_SECONDS,
        _DRIVER_CACHE_TTL_SECONDS,
        _NEGATIVE_CACHE_SENTINEL,
        _USER_CACHE_TTL_SECONDS,
        DatabaseError,
        DuplicateRecordError,
        RetryPolicy,
        ServiceUnavailableException,
        _apply_filters,
        _breaker,
        _build_or_clause,
        _build_or_clause_term,
        _driver_by_user_cache_key,
        _driver_cache_key,
        _metric_prefix_for_key,
        _postgrest_pattern,
        _pre_invalidate_for_table,
        _read_cached_row,
        _rows_from_res,
        _serialize_for_api,
        _single_row_from_res,
        _user_cache_key,
        _write_cached_row,
        count_documents,
        delete_many,
        delete_one,
        find_one,
        get_rows,
        insert_many,
        insert_many_ignore_conflicts,
        insert_one,
        invalidate_driver_cache,
        invalidate_user_cache,
        ping,
        rpc,
        run_sync,
        supabase,
        update_one,
    )
except ImportError:
    from repositories._base import (  # type: ignore  # noqa: F401
        _DB_EXECUTOR,
        _DRIVER_BY_USER_CACHE_TTL_SECONDS,
        _DRIVER_CACHE_TTL_SECONDS,
        _NEGATIVE_CACHE_SENTINEL,
        _USER_CACHE_TTL_SECONDS,
        DatabaseError,
        DuplicateRecordError,
        RetryPolicy,
        ServiceUnavailableException,
        _apply_filters,
        _breaker,
        _build_or_clause,
        _build_or_clause_term,
        _driver_by_user_cache_key,
        _driver_cache_key,
        _metric_prefix_for_key,
        _postgrest_pattern,
        _pre_invalidate_for_table,
        _read_cached_row,
        _rows_from_res,
        _serialize_for_api,
        _single_row_from_res,
        _user_cache_key,
        _write_cached_row,
        count_documents,
        delete_many,
        delete_one,
        find_one,
        get_rows,
        insert_many,
        insert_many_ignore_conflicts,
        insert_one,
        invalidate_driver_cache,
        invalidate_user_cache,
        ping,
        rpc,
        run_sync,
        supabase,
        update_one,
    )

try:
    from .repositories.corporate_repo import (  # noqa: F401 — re-exported
        accept_member_invite,
        add_allowed_domain,
        count_pending_signups_for_user,
        create_active_member,
        create_kyb_upload_url,
        delete_allowed_domain,
        delete_corporate_account,
        ensure_corporate_wallet,
        find_companies_by_email_domain,
        get_all_corporate_accounts,
        get_allowance_request_by_id,
        get_corporate_account_by_id,
        get_corporate_member_by_id,
        get_corporate_members_for_user,
        get_corporate_policy,
        get_corporate_wallet_by_company,
        get_default_payment_method,
        get_member_allowance,
        get_member_by_invite_token,
        insert_allowance_request,
        insert_corporate_account,
        insert_corporate_member_invite,
        kyb_object_exists,
        list_active_memberships_for_user,
        list_allowances_due_for_reset,
        list_allowed_domains,
        list_company_allowance_requests,
        list_company_allowances,
        list_company_members,
        list_company_ride_payment_sources,
        list_corporate_accounts_filtered,
        list_pending_allowance_requests_for_member,
        list_wallet_transactions,
        list_wallets_low_balance_no_autotopup,
        list_wallets_needing_autotopup,
        mark_low_balance_notified,
        record_kyb_decision,
        reset_allowance_period,
        set_kyb_document,
        sum_autotopups_today,
        update_allowance_request,
        update_corporate_account,
        update_corporate_account_status,
        update_corporate_member,
        update_corporate_stripe_customer_id,
        update_corporate_wallet_config,
        upsert_corporate_policy,
        upsert_member_allowance,
    )
except ImportError:
    from repositories.corporate_repo import (  # type: ignore  # noqa: F401
        accept_member_invite,
        add_allowed_domain,
        count_pending_signups_for_user,
        create_active_member,
        create_kyb_upload_url,
        delete_allowed_domain,
        delete_corporate_account,
        ensure_corporate_wallet,
        find_companies_by_email_domain,
        get_all_corporate_accounts,
        get_allowance_request_by_id,
        get_corporate_account_by_id,
        get_corporate_member_by_id,
        get_corporate_members_for_user,
        get_corporate_policy,
        get_corporate_wallet_by_company,
        get_default_payment_method,
        get_member_allowance,
        get_member_by_invite_token,
        insert_allowance_request,
        insert_corporate_account,
        insert_corporate_member_invite,
        kyb_object_exists,
        list_active_memberships_for_user,
        list_allowances_due_for_reset,
        list_allowed_domains,
        list_company_allowance_requests,
        list_company_allowances,
        list_company_members,
        list_company_ride_payment_sources,
        list_corporate_accounts_filtered,
        list_pending_allowance_requests_for_member,
        list_wallet_transactions,
        list_wallets_low_balance_no_autotopup,
        list_wallets_needing_autotopup,
        mark_low_balance_notified,
        record_kyb_decision,
        reset_allowance_period,
        set_kyb_document,
        sum_autotopups_today,
        update_allowance_request,
        update_corporate_account,
        update_corporate_account_status,
        update_corporate_member,
        update_corporate_stripe_customer_id,
        update_corporate_wallet_config,
        upsert_corporate_policy,
        upsert_member_allowance,
    )

try:
    from .repositories.auth_repo import (  # noqa: F401 — re-exported
        create_user,
        delete_otp_record,
        get_otp_record,
        get_otp_record_by_phone,
        get_user_by_id,
        get_user_by_phone,
        insert_otp_record,
        verify_otp_record,
    )
except ImportError:
    from repositories.auth_repo import (  # type: ignore  # noqa: F401
        create_user,
        delete_otp_record,
        get_otp_record,
        get_otp_record_by_phone,
        get_user_by_id,
        get_user_by_phone,
        insert_otp_record,
        verify_otp_record,
    )

try:
    from .repositories.driver_repo import (  # noqa: F401 — re-exported
        claim_driver_atomic,
        claim_ride_atomic,
        find_nearby_drivers,
        get_driver_by_id,
        get_driver_by_user_id_cached,
        get_driver_status_by_user,
        get_service_area_for_point,
        match_and_claim_driver,
        set_driver_available,
        update_driver_location,
    )
except ImportError:
    from repositories.driver_repo import (  # type: ignore  # noqa: F401
        claim_driver_atomic,
        claim_ride_atomic,
        find_nearby_drivers,
        get_driver_by_id,
        get_driver_by_user_id_cached,
        get_driver_status_by_user,
        get_service_area_for_point,
        match_and_claim_driver,
        set_driver_available,
        update_driver_location,
    )

try:
    from .repositories.ride_repo import (  # noqa: F401 — re-exported
        claim_ride_payment_processing,
        create_complaint,
        create_flag,
        create_lost_and_found,
        get_flags_for_target,
        get_live_ride_data,
        get_ride,
        get_ride_count_by_date_range,
        get_ride_details_enriched,
        get_ride_location_trail,
        get_rides_for_driver,
        get_rides_for_user,
        get_user_status,
        insert_ride,
        resolve_complaint,
        update_lost_and_found,
        update_ride,
    )
except ImportError:
    from repositories.ride_repo import (  # type: ignore  # noqa: F401
        claim_ride_payment_processing,
        create_complaint,
        create_flag,
        create_lost_and_found,
        get_flags_for_target,
        get_live_ride_data,
        get_ride,
        get_ride_count_by_date_range,
        get_ride_details_enriched,
        get_ride_location_trail,
        get_rides_for_driver,
        get_rides_for_user,
        get_user_status,
        insert_ride,
        resolve_complaint,
        update_lost_and_found,
        update_ride,
    )

try:
    from .repositories.wallet_repo import (  # noqa: F401 — re-exported
        claim_promo_user_slot,
        claim_stripe_event,
        fare_split_pay_share,
        increment_promo_uses,
        mark_stripe_event_processed,
        release_promo_user_slot,
        unclaim_stripe_event,
        wallet_apply_credit,
        wallet_apply_delta,
        wallet_increment_balance,
        wallet_pay_for_ride,
        wallet_transfer,
    )
except ImportError:
    from repositories.wallet_repo import (  # type: ignore  # noqa: F401
        claim_promo_user_slot,
        claim_stripe_event,
        fare_split_pay_share,
        increment_promo_uses,
        mark_stripe_event_processed,
        release_promo_user_slot,
        unclaim_stripe_event,
        wallet_apply_credit,
        wallet_apply_delta,
        wallet_increment_balance,
        wallet_pay_for_ride,
        wallet_transfer,
    )
