"""
Single source of truth for app settings.
Settings are stored as one row: id='app_settings' with flat keys.
All readers use get_app_settings() for consistent defaults and shape.
"""

import time
from typing import Any, Dict, Optional, Tuple

try:
    from . import db_supabase
    from .schemas import AppSettings
except ImportError:
    import db_supabase
    from schemas import AppSettings

_SETTINGS_TTL = 60  # seconds — allows admin changes to propagate within 1 minute
_settings_cache: Optional[Tuple[float, Dict[str, Any]]] = None


def _defaults_dict() -> Dict[str, Any]:
    """Return default values from AppSettings schema."""
    return AppSettings().model_dump()


async def get_app_settings() -> Dict[str, Any]:
    """
    Load app settings from DB (single row id='app_settings') and merge with
    schema defaults so every caller gets the same keys. Use this everywhere
    instead of (lambda _r: _r[0] if _r else None)(db_supabase.get_rows("settings", {'id': 'app_settings'}, limit=1)).

    Results are cached in-process for _SETTINGS_TTL seconds to avoid a DB
    round-trip on every ride creation and dispatch call.
    """
    global _settings_cache
    now = time.monotonic()
    if _settings_cache is not None:
        cached_at, cached_val = _settings_cache
        if now - cached_at < _SETTINGS_TTL:
            return cached_val

    defaults = _defaults_dict()
    row = (lambda _r: _r[0] if _r else None)(await db_supabase.get_rows("settings", {"id": "app_settings"}, limit=1))
    if not row:
        result = defaults
    else:
        # Merge: row overrides defaults; include any extra keys from admin (heat_map_*, app_name, etc.)
        result = {**defaults}
        for k, v in row.items():
            if k == "id":
                continue
            result[k] = v

    _settings_cache = (now, result)
    return result


def get_cached_app_settings() -> Optional[Dict[str, Any]]:
    """The last-loaded settings if still within the TTL, else None. Never loads.

    Sync counterpart to :func:`get_app_settings`, for the PDF/Excel/Word report
    builders. fpdf2 and openpyxl are synchronous, so those render paths cannot
    await a settings read — which is why company identity used to be hardcoded
    there, and why changing the company address meant editing code.

    Deliberately never triggers a load and never blocks: a sync render must not
    do I/O it cannot await. Returning None lets the caller fall back.

    In a live process the cache is effectively always warm — every ride, fare,
    email and dispatch call reads settings, all sharing this 60 s cache — so a
    report generated by a running server sees current values. The cold case is
    real but narrow (first request after a restart), and it degrades to the
    module constants rather than to anything wrong.
    """
    if _settings_cache is None:
        return None
    cached_at, cached_val = _settings_cache
    if time.monotonic() - cached_at >= _SETTINGS_TTL:
        return None
    return cached_val
