"""
Unit tests for backend/utils/insurance_periods.py and the open_period
call-sites in backend/routes/drivers.py.

Coverage:
    1. open_period closes any existing open row via update_one.
    2. open_period inserts the new period row with correct fields.
    3. open_period works when there is no existing open row (no update_one call).
    4. open_period with period=2 and no ride_id: row is still inserted (non-fatal).
    5. open_period swallows DB errors — never raises to the caller.
    6. go-online (update_driver_status is_online=True) calls open_period(period=1).
    7. go-offline (update_driver_status is_online=False) calls open_period(period=0).
    8. complete_ride calls open_period(period=1) after the ride is completed.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DRIVER_ID = "driver-abc-123"
RIDE_ID = "ride-xyz-456"
TABLE = "driver_insurance_periods"


# ---------------------------------------------------------------------------
# Tests for open_period utility (utils/insurance_periods.py)
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_open_period_closes_existing_open_row():
    """When an open row exists it must be closed via update_one before insert."""
    open_row = {"id": "period-row-old", "driver_id": DRIVER_ID, "period": 1, "ended_at": None}

    mock_get_rows = AsyncMock(return_value=[open_row])
    mock_update_one = AsyncMock(return_value=None)
    mock_insert_one = AsyncMock(return_value={"id": "period-row-new"})

    with (
        patch("utils.insurance_periods.get_rows", mock_get_rows),
        patch("utils.insurance_periods.update_one", mock_update_one),
        patch("utils.insurance_periods.insert_one", mock_insert_one),
    ):
        from utils.insurance_periods import open_period

        await open_period(DRIVER_ID, 1)

    # Must have queried for open rows for this driver.
    mock_get_rows.assert_awaited_once_with(TABLE, {"driver_id": DRIVER_ID, "ended_at": None}, limit=5)

    # Must have closed the existing open row.
    mock_update_one.assert_awaited_once()
    _, update_filters, update_payload = mock_update_one.call_args[0]
    assert update_filters == {"id": "period-row-old"}
    assert "ended_at" in update_payload


@pytest.mark.anyio
async def test_open_period_inserts_new_row():
    """After closing existing rows, open_period inserts the new period row."""
    open_row = {"id": "period-row-old", "driver_id": DRIVER_ID, "period": 1, "ended_at": None}

    mock_get_rows = AsyncMock(return_value=[open_row])
    mock_update_one = AsyncMock(return_value=None)
    mock_insert_one = AsyncMock(return_value={"id": "period-row-new"})

    with (
        patch("utils.insurance_periods.get_rows", mock_get_rows),
        patch("utils.insurance_periods.update_one", mock_update_one),
        patch("utils.insurance_periods.insert_one", mock_insert_one),
    ):
        from utils.insurance_periods import open_period

        await open_period(DRIVER_ID, 2, ride_id=RIDE_ID)

    mock_insert_one.assert_awaited_once()
    insert_table, insert_payload = mock_insert_one.call_args[0]
    assert insert_table == TABLE
    assert insert_payload["driver_id"] == DRIVER_ID
    assert insert_payload["period"] == 2
    assert insert_payload["ride_id"] == RIDE_ID
    assert "started_at" in insert_payload
    assert "id" in insert_payload  # uuid generated by open_period


@pytest.mark.anyio
async def test_open_period_with_no_existing_row():
    """When no open row exists, open_period skips update_one and still inserts."""
    mock_get_rows = AsyncMock(return_value=[])
    mock_update_one = AsyncMock(return_value=None)
    mock_insert_one = AsyncMock(return_value={"id": "period-row-new"})

    with (
        patch("utils.insurance_periods.get_rows", mock_get_rows),
        patch("utils.insurance_periods.update_one", mock_update_one),
        patch("utils.insurance_periods.insert_one", mock_insert_one),
    ):
        from utils.insurance_periods import open_period

        await open_period(DRIVER_ID, 0)

    mock_update_one.assert_not_awaited()

    mock_insert_one.assert_awaited_once()
    _, insert_payload = mock_insert_one.call_args[0]
    assert insert_payload["period"] == 0
    assert insert_payload["driver_id"] == DRIVER_ID


@pytest.mark.anyio
async def test_open_period_period_2_no_ride_id_still_inserts():
    """period=2 with ride_id=None is non-fatal — row is inserted with ride_id=None."""
    mock_get_rows = AsyncMock(return_value=[])
    mock_update_one = AsyncMock(return_value=None)
    mock_insert_one = AsyncMock(return_value={"id": "period-row-new"})

    with (
        patch("utils.insurance_periods.get_rows", mock_get_rows),
        patch("utils.insurance_periods.update_one", mock_update_one),
        patch("utils.insurance_periods.insert_one", mock_insert_one),
    ):
        from utils.insurance_periods import open_period

        # Must not raise even though ride_id is absent.
        await open_period(DRIVER_ID, 2, ride_id=None)

    # Row must still be inserted (non-fatal).
    mock_insert_one.assert_awaited_once()
    _, insert_payload = mock_insert_one.call_args[0]
    assert insert_payload["period"] == 2
    assert insert_payload["ride_id"] is None


@pytest.mark.anyio
async def test_open_period_db_error_does_not_raise():
    """If get_rows raises, open_period logs the error and does NOT propagate."""
    mock_get_rows = AsyncMock(side_effect=RuntimeError("DB connection refused"))

    with (
        patch("utils.insurance_periods.get_rows", mock_get_rows),
        patch("utils.insurance_periods.logger") as mock_logger,
    ):
        from utils.insurance_periods import open_period

        # Must complete without raising.
        await open_period(DRIVER_ID, 1)

    mock_logger.error.assert_called_once()
    error_first_arg = mock_logger.error.call_args[0][0]
    assert "failed" in error_first_arg.lower() or "INSURANCE" in error_first_arg


# ---------------------------------------------------------------------------
# Tests for drivers.py call-sites
# ---------------------------------------------------------------------------

DRIVER_USER_ID = "user-driver-001"
DRIVER_ROW = {
    "id": DRIVER_ID,
    "user_id": DRIVER_USER_ID,
    "name": "Test Driver",
    "status": "active",
    "is_verified": True,
    "is_online": False,
    "is_available": False,
}
DRIVER_ROW_ONLINE = {**DRIVER_ROW, "is_online": True, "is_available": True}


@pytest.mark.anyio
async def test_period_transition_go_online():
    """Going online must call open_period(driver_id, period=1)."""
    from backend.routes import drivers as drv_mod

    mock_open_period = AsyncMock()

    with (
        patch(
            "backend.routes.drivers.db_supabase.get_driver_by_id",
            AsyncMock(side_effect=[DRIVER_ROW, DRIVER_ROW_ONLINE]),
        ),
        patch("backend.routes.drivers.db_supabase.get_rows", AsyncMock(return_value=[])),
        patch("backend.routes.drivers.db_supabase.update_one", AsyncMock()),
        patch("backend.routes.drivers.mark_present", AsyncMock()),
        patch("backend.routes.drivers.clear_presence", AsyncMock()),
        # Patch the source module so the lazy inline import picks up the mock.
        patch("utils.insurance_periods.open_period", mock_open_period),
    ):
        result = await drv_mod.update_driver_status(
            driver_id=DRIVER_ID,
            is_online=True,
            current_user={"id": DRIVER_USER_ID},
        )

    assert result["success"] is True
    mock_open_period.assert_awaited_once_with(DRIVER_ID, period=1)


@pytest.mark.anyio
async def test_period_transition_go_offline():
    """Going offline must call open_period(driver_id, period=0)."""
    from backend.routes import drivers as drv_mod

    mock_open_period = AsyncMock()
    driver_offline = {**DRIVER_ROW, "is_online": False, "is_available": False}

    with (
        patch(
            "backend.routes.drivers.db_supabase.get_driver_by_id",
            AsyncMock(side_effect=[DRIVER_ROW_ONLINE, driver_offline]),
        ),
        patch("backend.routes.drivers.db_supabase.get_rows", AsyncMock(return_value=[])),
        patch("backend.routes.drivers.db_supabase.update_one", AsyncMock()),
        patch("backend.routes.drivers.mark_present", AsyncMock()),
        patch("backend.routes.drivers.clear_presence", AsyncMock()),
        patch("utils.insurance_periods.open_period", mock_open_period),
    ):
        result = await drv_mod.update_driver_status(
            driver_id=DRIVER_ID,
            is_online=False,
            current_user={"id": DRIVER_USER_ID},
        )

    assert result["success"] is True
    mock_open_period.assert_awaited_once_with(DRIVER_ID, period=0)


@pytest.mark.anyio
async def test_period_transition_complete_ride():
    """Completing a ride must call open_period(driver_id, period=1) — driver back to available."""
    from backend.routes import drivers as drv_mod

    mock_open_period = AsyncMock()

    ride_row = {
        "id": RIDE_ID,
        "driver_id": DRIVER_ID,
        "rider_id": "rider-001",
        "status": "in_progress",
        "total_fare": "14.50",
        "pickup_address": "123 Main St",
        "dropoff_address": "456 Elm Ave",
        "created_at": "2026-05-06T10:00:00+00:00",
        "updated_at": "2026-05-06T10:30:00+00:00",
    }
    completed_ride = {**ride_row, "status": "completed"}

    with (
        patch(
            "backend.routes.drivers.db_supabase.get_rows",
            AsyncMock(
                side_effect=[
                    [DRIVER_ROW],  # driver lookup by user_id
                    [ride_row],  # ride lookup for this driver
                    [],  # GPS breadcrumbs (driver_location_history)
                ]
            ),
        ),
        patch("backend.routes.drivers.db_supabase.update_ride", AsyncMock(return_value=completed_ride)),
        patch("backend.routes.drivers.db_supabase.get_ride", AsyncMock(return_value=completed_ride)),
        patch(
            "backend.routes.drivers.manager",
            MagicMock(
                send_personal_message=AsyncMock(),
                broadcast_ride_status=AsyncMock(),
                broadcast_to_admins=AsyncMock(),
            ),
        ),
        patch("backend.routes.drivers.send_push_notification", AsyncMock()),
        patch("utils.insurance_periods.open_period", mock_open_period),
    ):
        await drv_mod.complete_ride(
            ride_id=RIDE_ID,
            current_user={"id": DRIVER_USER_ID},
        )

    # Driver returns to period 1 (available) after completing the ride.
    mock_open_period.assert_awaited_once_with(DRIVER_ID, period=1)
