-- 335_referral_payout_velocity_cap_setting.sql
--
-- Rollback:
--   ALTER TABLE public.settings
--       DROP COLUMN IF EXISTS referral_payout_velocity_cap_per_day;
--   Reverting removes the admin's ability to change the cap threshold; the
--   code falls back to schemas.py AppSettings' default (5) when the column
--   or row is absent, so the fraud guard itself keeps working either way —
--   this migration only makes the threshold persistable/admin-tunable.
--
-- Why this migration exists
-- --------------------------
-- `settings` stores one row (id='app_settings') with FLAT columns — no JSON
-- catch-all. PUT /api/admin/settings builds its payload straight from
-- SettingsUpdateRequest with no column allowlist (see migration 313's longer
-- writeup of this failure mode): a field the API accepts but this table
-- lacks 500s the ENTIRE settings save with PGRST204 the first time an admin
-- tries to change it, taking every other field in the same request down
-- with it. routes/admin/settings.py::SettingsUpdateRequest now accepts
-- referral_payout_velocity_cap_per_day (ranked blocker #6 / audit finding
-- N2, 2026-08-19 — the referral-fraud fix in utils/referral_payout.py), so
-- this column must exist before that field is ever saved.
--
-- Default matches schemas.py AppSettings.referral_payout_velocity_cap_per_day
-- (5) exactly, so applying this changes no behaviour: the cap the code has
-- effectively been enforcing since the fix shipped becomes persistable, not
-- newly effective.
--
-- Additive only: nullable-with-default column, PG11+ applies it as catalog
-- metadata (no table rewrite). `settings` is a single-row config table
-- regardless.

ALTER TABLE public.settings
    ADD COLUMN IF NOT EXISTS referral_payout_velocity_cap_per_day INTEGER NOT NULL DEFAULT 5;
