// Barrel re-export for the admin-dashboard API surface. The implementation
// lives in per-domain modules under src/lib/api/ (see src/lib/api/client.ts
// for the shared fetch client); this file exists only so the many existing
// `import { ... } from "@/lib/api"` call sites across the app don't need to
// change. Add new endpoints to the relevant domain module and re-export them
// here rather than growing this file directly.
export { API_BASE, RateLimitError, request } from "./api/client";
export {
    getDriverDocuments,
    downloadDriverDocument,
    reviewDocument,
    adminUploadDriverDocument,
    getDriverNotes,
    addDriverNote,
    deleteDriverNote,
} from "./api/driver-documents";
export type {
    RejectTemplate,
    ReviewDocumentOptions,
    AdminUploadDocumentInput,
} from "./api/driver-documents";
export {
    getDriverAppeals,
    getDriverAppealStats,
    resolveDriverAppeal,
} from "./api/driver-appeals";
export type { DriverAppeal, DriverAppealStats } from "./api/driver-appeals";
export {
    getRides,
    exportRides,
    getRideDetails,
    getRideTrend,
    getRideStats,
    getRideFinancials,
    getRideLocationTrail,
    getLiveRideData,
    getRideInvoice,
    getRideRouteMapDataUrl,
    flagRideParticipant,
    createRideComplaint,
    resolveComplaint,
    reportLostItem,
    resolveLostItem,
    sendRideInvoice,
    sendPayableRideInvoice,
    getFlags,
    deactivateFlag,
    deleteFlag,
    getLostAndFoundItems,
    updateLostItem,
    deleteLostItem,
    deleteDispute,
    getComplaints,
    deleteComplaint,
} from "./api/rides";
export type { RideListOpts, RideFinancialsPeriod } from "./api/rides";
export {
    getDrivers,
    adminSearchDrivers,
    adminSearchUsers,
    getDriverRides,
    getDriverDailyActivity,
    getDriverDistanceTravelled,
    getDriverDistanceLogs,
    fetchDriverDistanceExport,
    getDriverLiveStats,
    getDriverReferrals,
    getDriverTraining,
    getReferralLeaderboard,
    getRiderReferralLeaderboard,
    getReferralAnalytics,
    getFailedReferralClaims,
    requeueFailedReferral,
    getReferralPairs,
    getDriverPayoutsSummary,
    refreshAllDriverStripeKyc,
    refreshAllDriverStripePayouts,
    refreshDriverStripeKyc,
    refreshDriverStripePayouts,
    recomputeStatementTotals,
    revealDriverSin,
    getDriverStatements,
    downloadDriverStatement,
    emailDriverStatement,
    getDriverStats,
    updateDriver,
    generateDecalPdf,
} from "./api/drivers";
export type {
    DriverLiveStats,
    DriverReferee,
    DriverReferralSummary,
    DriverTrainingCourse,
    DriverTrainingCertificate,
    DriverTrainingQuizAttempt,
    DriverTrainingCommunication,
    DriverTraining,
    ReferralLeader,
    ReferralLeaderboard,
    ReferralAnalytics,
    FailedReferralClaim,
    ReferralPair,
    DriverPayoutSummary,
    RevealSinResponse,
    DriverStatement,
    DriverStatementPeriodType,
    StatementSelection,
} from "./api/drivers";
export {
    getCorporateAccounts,
    listCorporateAccounts,
    reviewKyb,
    getCorporateAccount,
    changeCompanyStatus,
    fetchKybDocumentBlob,
    createCorporateAccount,
    updateCorporateAccount,
    deleteCorporateAccount,
    getCorporateWallet,
    updateWalletConfig,
    walletTopupIntent,
    walletAdjust,
    getWalletRiskPortfolio,
    getKybReverificationDue,
    getCorporateSubscriptionPlans,
    getCompanySubscription,
    assignCompanySubscription,
    cancelCompanySubscription,
    listCompanyMembers,
    inviteCompanyMember,
    removeCompanyMember,
    getMemberAllowance,
    putMemberAllowance,
    listCompanyAllowanceRequests,
    decideAllowanceRequest,
    updateCompanyMember,
    getCompanyPolicy,
    putCompanyPolicy,
    patchCompanyPolicy,
    listAllowedDomains,
    addAllowedDomain,
    removeAllowedDomain,
    getCompanyBillingSummary,
    getCompanyBillingStatement,
    getCompanyBillingTransactions,
} from "./api/corporate";
export type {
    CompanyStatus,
    SizeTier,
    CorporateAccount,
    WalletTxn,
    CorporateWallet,
    WalletConfigPatch,
    WalletRiskFlag,
    WalletRiskEntry,
    WalletRiskPortfolio,
    KybReverificationCompany,
    KybReverificationDue,
    CorporateSubscriptionStatus,
    CorporateSubscriptionPlan,
    CorporateSubscription,
    CompanySubscriptionResponse,
    CorporateMemberRole,
    CorporateMemberStatus,
    AllowanceTypeValue,
    CorporateMember,
    CorporateAllowance,
    AllowanceRequestRow,
    PaymentSourcePolicy,
    TimeWindowPolicy,
    CorporatePolicy,
    AllowedDomainRow,
    BillingMemberBreakdown,
    BillingSummary,
    BillingLineItem,
    BillingStatement,
    BillingTransaction,
    BillingTransactionsPage,
} from "./api/corporate";
export {
    getEarnings,
    getEarningsRides,
    getEarningsOverview,
    getSubscriptionStats,
} from "./api/earnings";
export type {
    EarningsRide,
    EarningsRidesResponse,
    EarningsPeriod,
    MetricWithDelta,
    EarningsOverview,
} from "./api/earnings";
export {
    loginAdmin,
    loginAdminSession,
    mfaChallenge,
    mfaStatus,
    mfaEnroll,
    mfaConfirm,
    mfaDisable,
    sendOtp,
    logoutAllAdmin,
} from "./api/auth";
export type {
    AuthResponse,
    AdminLoginResponse,
    AdminMfaRequired,
    AdminMfaEnrollmentRequired,
    AdminLoginResult,
    MfaConfirmResponse,
} from "./api/auth";
export { getStats } from "./api/dashboard";
export {
    getEmailDeliverability,
    getSettings,
    updateSettings,
    getAiCatalog,
    adminAiChat,
    getAdminAiConversations,
    getAdminAiMessages,
} from "./api/settings-ai";
export type {
    AiCatalogModel,
    AiCatalogProvider,
    AdminAiChatResponse,
} from "./api/settings-ai";
export {
    getServiceAreas,
    getVenues,
    createVenue,
    updateVenue,
    deleteVenue,
    createServiceArea,
    updateServiceArea,
    getAreaHeatmapConfig,
    deleteServiceArea,
    getIncentives,
    createIncentive,
    updateIncentive,
    toggleIncentive,
    deleteIncentive,
    getSurgeStatus,
    resetSurgeToAuto,
    getVehicleTypes,
    createVehicleType,
    updateVehicleType,
    deleteVehicleType,
    adminUploadVehicleIllustration,
    adminUploadVehicleMarker,
    adminUploadRideOfferSound,
    getFareConfigs,
    createFareConfig,
    updateFareConfig,
    deleteFareConfig,
    updateSurge,
    getPendingExportApprovals,
    approveExportRequest,
    denyExportRequest,
} from "./api/pricing";
export type {
    VenuePickupPoint,
    Venue,
    VenueUpsert,
    ExportApprovalRequest,
    AreaHeatmapConfig,
    AreaHeatmapConfigSpec,
} from "./api/pricing";
export {
    adminValidateDriverImport,
    adminCommitDriverImport,
    adminValidateBookingImport,
    adminCommitBookingImport,
    adminDiscoverStripeDriverAccounts,
    adminValidateStripeImport,
    adminCommitStripeImport,
    adminStripeImportStatus,
    adminUpdateDriverStripeAccount,
    adminValidateRiderImport,
    adminCommitRiderImport,
    adminRegenerateImportedSnapshots,
} from "./api/imports";
export type {
    DriverImportReportItem,
    DriverImportReport,
    DriverImportCommitResult,
    DriverImportOptions,
    BookingImportReportItem,
    BookingImportCounts,
    BookingImportReport,
    BookingImportCommitResult,
    BookingImportFiles,
    BookingImportOptions,
    StripeDiscoveryMatch,
    StripeDiscoveryReport,
    StripeImportKind,
    StripeImportReportItem,
    StripeImportNeedsUpdateItem,
    StripeImportReport,
    StripeImportCommitResult,
    StripeImportStatus,
    StripeDriverAccountUpdateResult,
    RiderImportReportItem,
    RiderImportDuplicate,
    RiderImportReport,
    RiderImportCommitResult,
    SnapshotRegenerateResult,
} from "./api/imports";
export {
    getCloudMessages,
    sendCloudMessage,
    getCloudMessageStats,
    deleteCloudMessage,
    getCloudMessageAudiencePreview,
    getMarketingSuppressions,
    addMarketingSuppression,
    deleteMarketingSuppression,
    getPromoUsage,
    getPromoStats,
} from "./api/marketing";
export {
    getUsers,
    getUsersPaginated,
    getUserDetails,
    updateUserStatus,
    updateUserFlags,
    exportUsers,
    logPiiReveal,
    getUserWallet,
    creditUserWallet,
    debitUserWallet,
    backfillStripeCustomerEmails,
} from "./api/users-wallet";
export {
    getPromotions,
    createPromotion,
    updatePromotion,
    deletePromotion,
    getDisputes,
    getDisputeStats,
    getDisputeDetails,
    createDispute,
    updateDispute,
    getChargebacks,
    downloadDisputeEvidencePack,
    submitDisputeEvidence,
    getSafetyIncidents,
    getSafetyIncident,
    updateSafetyIncident,
    createSafetyIncident,
    mergeSafetyIncident,
    getTickets,
    getTicketDetails,
    createTicket,
    updateTicket,
    replyToTicket,
    closeTicket,
    deleteTicket,
} from "./api/safety-disputes";
export type {
    SafetyStatus,
    SafetySeverity,
    SafetyRole,
    SafetyIncident,
    SafetyIncidentListResponse,
    SafetyIncidentDetail,
    SafetyIncidentPhoto,
    Chargeback,
    SubmitDisputeEvidenceResult,
} from "./api/safety-disputes";
export type { LegalDocType } from "./api/content-area";
export {
    getFaqs,
    createFaq,
    updateFaq,
    deleteFaq,
    getLegalDocuments,
    upsertLegalDocument,
    getAreaFees,
    createAreaFee,
    updateAreaFee,
    deleteAreaFee,
    getAreaTax,
    updateAreaTax,
    getVehiclePricing,
    assignDriverArea,
    driverAction,
    getDriverVehicleHistory,
    reviewDriverPhoto,
    uploadDriverPhoto,
    overrideDriverStatus,
    exportDrivers,
} from "./api/content-area";
export { getHeatMapData, getHeatMapSettings, updateHeatMapSettings } from "./api/heatmap";
export type { HeatMapData, HeatMapSettings } from "./api/heatmap";
export {
    getStaff,
    createStaff,
    updateStaff,
    deleteStaff,
    resetStaffMfa,
    getStaffModules,
    getSubscriptionPlans,
    createSubscriptionPlan,
    updateSubscriptionPlan,
    deleteSubscriptionPlan,
    getDriverSubscriptions,
    getAdminSubscriptionPayments,
    downloadSubscriptionInvoice,
    resendAdminSubscriptionInvoice,
    updateSubscriptionTaxConfig,
    getAuditLogs,
    getAuditLogTopActors,
    type AuditLogEntry,
    getQuests,
    createQuest,
    updateQuest,
    getQuestParticipants,
} from "./api/staff-subscriptions";
export {
    getAnalyticsOverview,
    getDashboardOverview,
    getCancellationBreakdown,
    getDriverAcceptanceRates,
    getDriverOfferStats,
    getDriverOfferTrends,
    getDemandForecast,
    getDemandForecastSummary,
    getSurgeHistory,
    getPayouts,
    getPayoutById,
    getPayoutStats,
    closePayoutPeriod,
    getPayoutsOverview,
    getAutoPayoutBatches,
    getBlockedPayoutDrivers,
    resolveDispute,
} from "./api/analytics-payouts";
export type {
    PayoutsOverview,
    ClosePayoutPeriodResponse,
    AutoPayoutBatch,
    BlockedDriver,
} from "./api/analytics-payouts";
export {
    getActiveRides,
    getMonitoringDrivers,
    getMonitoringRides,
    adminCancelRide,
    adminCompleteRide,
    adminPlacesAutocomplete,
    adminPlacesDetails,
    adminFareEstimate,
    adminPromoPreview,
    adminListVehicleTypes,
    adminCreateRide,
    getRedisHealth,
    getWebsocketHealth,
    getRedisConnectivity,
    getInfrastructureStats,
    flushRedisPrefix,
} from "./api/live-monitoring";
export type {
    AdminPlaceBias,
    AdminFareEstimateResponse,
    AdminVehicleType,
    RedisStats,
    RedisPrefixCount,
    RedisHealthResponse,
    InfrastructureStats,
    WebsocketHealth,
    RedisConnectivityProbe,
} from "./api/live-monitoring";
export {
    getDocumentRequirements,
    createDocumentRequirement,
    updateDocumentRequirement,
    deleteDocumentRequirement,
    getPendingDocuments,
    retryPayout,
    bulkRetryPayouts,
} from "./api/document-requirements";
export type {
    BulkRetryPayoutsRequest,
    BulkRetryPayoutsResponse,
} from "./api/document-requirements";
export {
    getZohoConfig,
    updateZohoConfig,
    testZohoConnection,
    syncDeskTickets,
    getDeskDashboard,
    getDeskTrends,
    getDeskTickets,
    createDeskTicket,
    searchDeskTickets,
    getDeskTicket,
    getDeskTicketThreads,
    getDeskThread,
    replyDeskTicket,
    commentDeskTicket,
    updateDeskTicket,
    updateDeskTicketTags,
    getDeskAgents,
    getDeskDepartments,
    getDeskServiceAreas,
    getDeskTicketServiceArea,
    setDeskTicketServiceArea,
    aiSuggestDeskReply,
} from "./api/zoho-desk";
export type {
    ZohoConfigStatus,
    ZohoConfigUpdate,
    ZohoTicketsResponse,
    ZohoDashboard,
    ZohoTrends,
    CreateDeskTicket,
    DeskServiceArea,
    DeskTicketServiceArea,
} from "./api/zoho-desk";
export {
    searchDataTransferEntities,
    exportDataTransferEntities,
    adminValidateDataTransferImport,
    adminCommitDataTransferImport,
    generateSgiForm,
    downloadSgiSupportingDocuments,
    downloadSgiSubmissionPackage,
    downloadGstPstRemittance,
    downloadDriverRoster,
    downloadT4aFilerHandoff,
    downloadInsuranceBillingSgi,
    downloadInsuranceBillingKnightArcher,
    downloadAirportTrips,
    listDataTransferJobs,
    getDataTransferJob,
    regenerateDataTransferJobDownload,
    getSgiRemovalQueue,
} from "./api/data-transfer";
export type {
    DataTransferEntityRow,
    DataTransferSearchResult,
    DataTransferSearchParams,
    DataTransferExportFormat,
    DataTransferExportEntityRef,
    DataTransferExportQueuedResult,
    ExportApprovalRequiredResult,
    DataTransferExportScopeOptions,
    DataTransferImportReportItem,
    DataTransferImportReport,
    DataTransferImportCommitResult,
    SgiFormType,
    SgiSupportingDocumentsResult,
    SgiPackageResult,
    SgiRemovalQueue,
    SgiRemovalQueueEntry,
    ComplianceReportFormat,
    DataTransferJob,
} from "./api/data-transfer";
export {
    getSentryConfig,
    getSentryIssues,
    getSentryIssueDetail,
    updateSentryIssueStatus,
    SENTRY_PER_SURFACE_LIMIT,
} from "./api/sentry";
export type {
    SentrySurface,
    SentryIssueStatus,
    SentryIssue,
    SentrySurfaceConfig,
    SentryConfig,
    SentrySurfaceError,
    SentryIssuesResponse,
    SentryStackFrame,
    SentryException,
    SentryTag,
    SentryIssueDetail,
    SentryStatusUpdateResponse,
} from "./api/sentry";
export {
    getApprovalQueue,
    getExpiringDocs,
    nudgeDriverExpiry,
    getDriverActivity,
} from "./api/driver-queue";
export type {
    ApprovalQueueItem,
    ApprovalQueueResponse,
    ExpiringDocItem,
} from "./api/driver-queue";
