"""Token-based APNs HTTP/2 client for iOS Live Activity pushes (Phase 3).

ActivityKit Live Activity updates do NOT ride the FCM path (FCM cannot carry the
``liveactivity`` push type), so they go **directly** to Apple over HTTP/2 with a
provider **token** (.p8 key, ES256 JWT) — see docs/live-ride-activity-plan.md §4.

Voltra renders the Live Activity UI in JavaScript, so the pushed ``content-state``
is one field — ``uiJsonData`` — a pre-rendered UI blob, NOT a struct of our data
fields. Our backend is Python, so we use **pre-rendered templates**: a build step
(rider-app/scripts/render-voltra-templates.mjs) renders the activity component
over a (status × eta-bucket) grid into ``voltra_templates.json``; here we index it
by ``(status, eta_bucket)`` and push the matching blob. Missing template → push
skipped (logged ``warning``). The ``_render_ui_json`` body is the single seam to
swap for a Node-sidecar renderer if template fidelity proves insufficient.

APNs credentials (.p8 key, key_id, team_id, bundle_id) live in the ``app_settings``
table (rotate without redeploy); the feature ships **dark** until they're set.

Best-effort: never raises. ``send_apns_live_activity`` returns ``(ok, dead_token)``
so the caller can retire a row whose token APNs reports dead.
"""

from __future__ import annotations

import json
import logging
import os
import time
from typing import Optional, Tuple

try:
    import httpx
    import jwt
except ImportError:  # pragma: no cover - deps are in requirements.txt
    httpx = None  # type: ignore
    jwt = None  # type: ignore

try:
    from ..settings_loader import get_app_settings
except ImportError:  # pragma: no cover - top-level execution fallback
    from settings_loader import get_app_settings  # type: ignore

logger = logging.getLogger(__name__)

_PROD_HOST = "https://api.push.apple.com"
_SANDBOX_HOST = "https://api.sandbox.push.apple.com"

# Apple accepts a provider token for 20–60 min; refresh well inside that window.
_TOKEN_TTL_SECONDS = 50 * 60
_token_cache: dict[str, Tuple[str, float]] = {}  # {key_id: (jwt, issued_at)}

# Reused HTTP/2 connection pool (Apple wants long-lived HTTP/2 connections).
_client: Optional["httpx.AsyncClient"] = None

# Pre-rendered Voltra UI templates, generated by the rider build step. Lives
# alongside this module so the backend bundles it. Loaded + cached on first use.
_TEMPLATES_PATH = os.path.join(os.path.dirname(__file__), "voltra_templates.json")
_templates: Optional[dict] = None
_config_warned = False


# --------------------------------------------------------------------------- #
# config (app_settings)
# --------------------------------------------------------------------------- #


async def _load_apns_config() -> Optional[dict]:
    """APNs creds from app_settings, or None (logged once) if not configured.

    Normalises the PEM's line endings and validates it looks like a private key
    so a mis-pasted .p8 fails loudly once, not per-push.
    """
    global _config_warned
    try:
        s = await get_app_settings()
    except Exception:
        logger.error("apns: failed to load app_settings", exc_info=True)
        return None
    key_id = (s.get("apns_key_id") or "").strip()
    team_id = (s.get("apns_team_id") or "").strip()
    bundle_id = (s.get("apns_bundle_id") or "").strip()
    p8 = (s.get("apns_p8_key") or "").replace("\r\n", "\n").strip()
    if not (key_id and team_id and bundle_id and p8):
        if not _config_warned:
            logger.warning("apns: Live Activity push not configured (set apns_* in admin settings)")
            _config_warned = True
        return None
    if "BEGIN PRIVATE KEY" not in p8:
        logger.error("apns: .p8 key malformed — re-paste in admin → Settings")
        return None
    return {"key_id": key_id, "team_id": team_id, "bundle_id": bundle_id, "p8": p8}


def _provider_jwt(p8_key: str, key_id: str, team_id: str) -> str:
    """ES256-signed APNs provider JWT, cached per key_id until near expiry."""
    cached = _token_cache.get(key_id)
    now = time.time()
    if cached and (now - cached[1]) < _TOKEN_TTL_SECONDS:
        return cached[0]
    token = jwt.encode(
        {"iss": team_id, "iat": int(now)},
        p8_key,
        algorithm="ES256",
        headers={"kid": key_id, "alg": "ES256"},
    )
    _token_cache[key_id] = (token, now)
    return token


# --------------------------------------------------------------------------- #
# template render (the Option-A swap seam)
# --------------------------------------------------------------------------- #


def _eta_bucket(eta_minutes: Optional[object]) -> str:
    """Coarse ETA bucket so a continuously-shrinking ETA needs few pushes (the
    on-device Voltra.Timer counts down between buckets). None → 'none'."""
    try:
        n = int(eta_minutes) if eta_minutes is not None else None
    except (TypeError, ValueError):
        n = None
    if n is None:
        return "none"
    if n < 2:
        return "lt2"
    if n < 5:
        return "lt5"
    if n < 10:
        return "lt10"
    if n < 20:
        return "lt20"
    return "gte20"


def _load_templates() -> dict:
    global _templates
    if _templates is None:
        try:
            with open(_TEMPLATES_PATH, encoding="utf-8") as f:
                _templates = json.load(f) or {}
        except (FileNotFoundError, ValueError):
            _templates = {}
    return _templates


def _render_ui_json(content: dict, event: str) -> Optional[str]:
    """Index the pre-rendered templates by (status, eta_bucket). Returns the
    uiJsonData blob, or None (push skipped) if no matching template exists."""
    status = content.get("status") or ""
    key = f"{status}:{_eta_bucket(content.get('eta_minutes'))}"
    tpl = _load_templates()
    return tpl.get(key) or tpl.get(f"{status}:none")


# --------------------------------------------------------------------------- #
# send
# --------------------------------------------------------------------------- #


def _get_client() -> "httpx.AsyncClient":
    global _client
    if _client is None:
        _client = httpx.AsyncClient(http2=True, timeout=10.0)
    return _client


async def aclose() -> None:
    """Close the shared client (call from app shutdown). Safe if never opened."""
    global _client
    if _client is not None:
        try:
            await _client.aclose()
        finally:
            _client = None


def _build_aps(ui_json: str, event: str) -> dict:
    aps: dict = {
        "event": "end" if event == "end" else "update",
        "content-state": {"uiJsonData": ui_json},
        "timestamp": int(time.time()),
    }
    if event == "end":
        # Brief lingering "Trip complete"/"Ride cancelled" then dismiss.
        aps["dismissal-date"] = int(time.time()) + 5
    return {"aps": aps}


async def send_apns_live_activity(
    push_token: str,
    content: dict,
    event: str,
    *,
    priority: int = 10,
    use_sandbox: Optional[bool] = None,
) -> Tuple[bool, bool]:
    """Send one Live Activity APNs push (token auth, HTTP/2).

    Returns ``(ok, dead_token)``. ``dead_token`` True means APNs reported the
    token unregistered/bad (410 / 400 BadDeviceToken) and the caller should end
    the activity row so no replica retries it. Never raises.
    """
    if httpx is None or jwt is None:
        return False, False
    if not push_token:
        return False, False
    cfg = await _load_apns_config()
    if not cfg:
        return False, False
    ui_json = _render_ui_json(content, event)
    if not ui_json:
        logger.warning("apns: no Voltra template for status=%s — push skipped", content.get("status"))
        return False, False

    if use_sandbox is None:
        try:
            from ..core.config import settings as _settings
        except ImportError:  # pragma: no cover
            from core.config import settings as _settings  # type: ignore
        use_sandbox = _settings.ENV.lower() != "production"

    host = _SANDBOX_HOST if use_sandbox else _PROD_HOST
    url = f"{host}/3/device/{push_token}"
    topic = f"{cfg['bundle_id']}.push-type.liveactivity"

    async def _post() -> "httpx.Response":
        headers = {
            "authorization": f"bearer {_provider_jwt(cfg['p8'], cfg['key_id'], cfg['team_id'])}",
            "apns-topic": topic,
            "apns-push-type": "liveactivity",
            "apns-priority": str(priority),
            "apns-expiration": str(int(time.time()) + 3600),
        }
        return await _get_client().post(url, headers=headers, json=_build_aps(ui_json, event))

    try:
        resp = await _post()
        if resp.status_code == 200:
            return True, False
        reason = _reason(resp)
        # Expired/invalid provider token → bust the JWT cache and retry once.
        if resp.status_code == 403 and reason in ("ExpiredProviderToken", "InvalidProviderToken"):
            _token_cache.pop(cfg["key_id"], None)
            resp = await _post()
            if resp.status_code == 200:
                return True, False
            reason = _reason(resp)
        dead = resp.status_code == 410 or (resp.status_code == 400 and reason == "BadDeviceToken")
        logger.warning("apns: live-activity push failed status=%s reason=%s", resp.status_code, reason)
        return False, dead
    except Exception:
        logger.error("apns: live-activity push errored", exc_info=True)
        return False, False


def _reason(resp: "httpx.Response") -> Optional[str]:
    try:
        return resp.json().get("reason")
    except Exception:
        return None
