"""Shared Spinr branding for admin-generated reports (PDF/Excel/Word/CSV).

Two categories of report exist and must never be confused:

- "branded": Spinr's own layout (logo, brand color, font) — used for reports
  we design ourselves (GST/PST remittance, insurance-period audit, DSAR
  lookup). Free to restyle.
- "fixed_format": a regulator's own document (e.g. SGI D00032/D00033,
  Knight Archer, a future province's equivalent) that must be reproduced
  in the exact required layout — never wrap these in Spinr branding, since
  the filled document itself gets submitted to the regulator/insurer.

REPORT_FORMAT_REGISTRY is the single source of truth for which mode a given
report type uses. Register new report types here rather than branching on
name strings at each call site.

Province/regulator letterhead fields are read from the `provinces` table
(migration 259) rather than hardcoded, so this module works for any Canadian
province Spinr expands into — not just Saskatchewan.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal, TypedDict

BRAND_RGB = (238, 43, 43)  # #ee2b2b — matches utils/receipt_pdf.py's _BRAND
BRAND_HEX = "EE2B2B"
BRAND_FONT = "Helvetica"  # fpdf2 core font name; closest match to product UI font

_ASSET_DIR = Path(__file__).resolve().parents[1] / "static" / "branding"
LOGO_PATH = _ASSET_DIR / "spinr_logo.png"

# Mirrors services/data_transfer/tabular_writer.py's _sanitize_csv_cell
# (OWASP CSV-injection guard). Duplicated rather than imported: importing
# tabular_writer pulls in services/__init__.py's full service-layer import
# chain (dispatch, settings, supabase client, ...) just for a 5-line helper.
_CSV_INJECTION_LEADS = ("=", "+", "-", "@", "\t", "\r")


def _sanitize_csv_cell(value):
    if isinstance(value, str) and value.startswith(_CSV_INJECTION_LEADS):
        return "'" + value
    return value


def has_logo_asset() -> bool:
    """True once the real logo file has been dropped into static/branding/.

    Until then, PDF/Excel/Word branded-report helpers fall back to a text
    wordmark rendered in BRAND_RGB/BRAND_FONT instead of failing.
    """
    return LOGO_PATH.is_file()


ReportMode = Literal["branded", "fixed_format"]


class ReportRegistration(TypedDict):
    mode: ReportMode
    description: str


REPORT_FORMAT_REGISTRY: dict[str, ReportRegistration] = {
    # Fixed-format: real regulator/insurer documents. Generated by
    # services/data_transfer/sgi_form_filler.py, which fills the actual SGI
    # AcroForm PDFs and must never be re-styled with Spinr branding.
    "sgi_driver_details": {
        "mode": "fixed_format",
        "description": "SGI D00032 Passenger for Hire – Driver Details",
    },
    "sgi_vehicle_details": {
        "mode": "fixed_format",
        "description": "SGI D00033 Transportation Network Company – Vehicle Details",
    },
    # Branded: Spinr-designed reports.
    "gst_pst_remittance": {
        "mode": "branded",
        "description": "GST/PST tax remittance summary",
    },
    "insurance_period_audit": {
        "mode": "branded",
        "description": "Driver insurance-period regulatory audit export",
    },
    "dsar_lookup": {
        "mode": "branded",
        "description": "Admin lookup of a rider/driver's self-service DSAR export status",
    },
}


def report_mode(report_type: str) -> ReportMode:
    """Look up whether `report_type` should be Spinr-branded or left in its
    fixed regulator/insurer format. Raises KeyError for unregistered types
    rather than silently defaulting — an unregistered compliance report is a
    bug, not a case to guess at."""
    return REPORT_FORMAT_REGISTRY[report_type]["mode"]


def pdf_safe(text: str) -> str:
    """fpdf2's core fonts (Helvetica etc.) only support Latin-1 — any
    caller text with an em dash, curly quote, warning glyph, or other
    common-but-non-Latin-1 character crashes FPDFUnicodeEncodingException
    at render time instead of failing at build time. Normalize the
    characters our own report text actually uses, then fall back to '?'
    for anything else so an unexpected character degrades a report instead
    of crashing it outright."""
    text = text.replace("—", "-").replace("–", "-").replace("’", "'").replace("⚠", "!")
    return text.encode("latin-1", errors="replace").decode("latin-1")


def new_branded_pdf(title: str, subtitle: str = ""):
    """Return an fpdf2 FPDF instance, portrait A4, with the standard Spinr
    branded header band already drawn (mirrors utils/receipt_pdf.py's
    header). Caller starts writing content at the current cursor position
    (y ~36mm) after this returns.

    Only for report_type entries registered as "branded" in
    REPORT_FORMAT_REGISTRY — fixed_format reports (SGI etc.) must never call
    this; they fill the regulator's own template via sgi_form_filler.
    """
    from fpdf import FPDF  # type: ignore[import-untyped]

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    left = 15

    pdf.set_fill_color(*BRAND_RGB)
    pdf.rect(0, 0, 210, 28, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(left, 8)
    if has_logo_asset():
        pdf.image(str(LOGO_PATH), x=left, y=6, h=14)
        pdf.set_xy(left + 40, 8)
    pdf.set_font(BRAND_FONT, "B", 18)
    pdf.cell(0, 8, pdf_safe(title), ln=True)
    pdf.set_x(left)
    if subtitle:
        pdf.set_font(BRAND_FONT, "", 10)
        pdf.cell(0, 6, pdf_safe(subtitle), ln=True)

    pdf.set_y(36)
    pdf.set_text_color(0, 0, 0)
    return pdf


def new_branded_workbook(title: str, subtitle: str = ""):
    """Return (Workbook, Worksheet) with a Spinr-branded title block already
    written: row 1 = title (brand color, bold), row 2 = subtitle (grey,
    optional), row 3 = blank spacer. Caller starts writing its header row at
    row 4.

    Only for report_type entries registered as "branded" — fixed_format
    reports never go through openpyxl branding; they fill the regulator's
    own template.
    """
    from openpyxl import Workbook  # noqa: PLC0415 — optional dep, only needed for this format
    from openpyxl.styles import Font

    wb = Workbook()
    ws = wb.active
    ws.title = "report"

    brand_hex = BRAND_HEX
    ws["A1"] = title
    ws["A1"].font = Font(name=BRAND_FONT, bold=True, size=14, color=brand_hex)
    if subtitle:
        ws["A2"] = subtitle
        ws["A2"].font = Font(name=BRAND_FONT, size=10, color="8C8C8C")
    return wb, ws


def write_branded_table(ws, fieldnames: list[str], rows: list[dict], start_row: int = 4) -> None:
    """Write a header row (brand-color fill, white bold text) at `start_row`
    followed by one row per dict in `rows`, using the same CSV-injection-safe
    cell sanitization as services/data_transfer/tabular_writer.py so a value
    round-tripped through either export path renders identically in Excel."""
    from openpyxl.styles import Font, PatternFill

    header_fill = PatternFill(start_color=BRAND_HEX, end_color=BRAND_HEX, fill_type="solid")
    header_font = Font(name=BRAND_FONT, bold=True, color="FFFFFF")

    for col, name in enumerate(fieldnames, start=1):
        cell = ws.cell(row=start_row, column=col, value=name)
        cell.fill = header_fill
        cell.font = header_font

    for r, row in enumerate(rows, start=start_row + 1):
        for col, name in enumerate(fieldnames, start=1):
            ws.cell(row=r, column=col, value=_sanitize_csv_cell(row.get(name)))


def new_branded_document(title: str, subtitle: str = ""):
    """Return a python-docx Document with a Spinr-branded title block
    already written: a heading in the brand color, an optional grey
    subtitle line, then a blank paragraph spacer. Caller appends its own
    content (paragraphs, tables) after this returns.

    Only for report_type entries registered as "branded" — fixed_format
    reports never go through python-docx branding.
    """
    from docx import Document
    from docx.shared import Pt, RGBColor

    brand_color = RGBColor(*BRAND_RGB)

    doc = Document()
    heading = doc.add_heading(title, level=1)
    for run in heading.runs:
        run.font.color.rgb = brand_color
        run.font.name = BRAND_FONT

    if subtitle:
        sub = doc.add_paragraph(subtitle)
        sub.runs[0].font.size = Pt(10)
        sub.runs[0].font.color.rgb = RGBColor(0x8C, 0x8C, 0x8C)

    doc.add_paragraph("")
    return doc


def add_branded_table(doc, fieldnames: list[str], rows: list[dict]) -> None:
    """Append a table to a python-docx Document: header row (brand-color
    shaded cells, bold white text) followed by one row per dict in `rows`.
    Cell values are not CSV-sanitized (Word has no formula-injection risk
    the way CSV/Excel do when opened by a spreadsheet app)."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import RGBColor

    table = doc.add_table(rows=1, cols=len(fieldnames))
    table.style = "Table Grid"
    header_cells = table.rows[0].cells
    for col, name in enumerate(fieldnames):
        header_cells[col].text = name
        run = header_cells[col].paragraphs[0].runs[0]
        run.font.bold = True
        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        shading = OxmlElement("w:shd")
        shading.set(qn("w:fill"), BRAND_HEX)
        header_cells[col]._tc.get_or_add_tcPr().append(shading)

    for row in rows:
        cells = table.add_row().cells
        for col, name in enumerate(fieldnames):
            cells[col].text = str(row.get(name, "") if row.get(name) is not None else "")


def render_branded_pdf_footer(pdf, province_letterhead: dict | None = None) -> None:
    """Draw a small grey footer with province/regulator letterhead info
    (from the `provinces` table, e.g. {"name": "Saskatchewan",
    "default_regulatory_authority": "SGI"}) plus a generation timestamp
    placeholder the caller fills in. No-op if letterhead is not supplied —
    callers pass None for reports that aren't province-scoped (e.g. a
    company-wide DSAR lookup)."""
    if not province_letterhead:
        return
    pdf.set_font(BRAND_FONT, "", 7)
    pdf.set_text_color(140, 140, 140)
    name = province_letterhead.get("name", "")
    authority = province_letterhead.get("default_regulatory_authority", "")
    line = f"Spinr Mobility Inc. — {name}" + (f" — regulator of record: {authority}" if authority else "")
    pdf.set_y(-15)
    pdf.cell(0, 5, pdf_safe(line), align="C")
