"""Shared Spinr branding for admin-generated reports (PDF/Excel/Word/CSV).

Two categories of report exist and must never be confused:

- "branded": Spinr's own layout (logo, brand color, font) — used for reports
  we design ourselves (GST/PST remittance, insurance-period audit, DSAR
  lookup). Free to restyle.
- "fixed_format": a regulator's own document (e.g. SGI D00032/D00033,
  Knight Archer, a future province's equivalent) that must be reproduced
  in the exact required layout — never wrap these in Spinr branding, since
  the filled document itself gets submitted to the regulator/insurer.

REPORT_FORMAT_REGISTRY is the single source of truth for which mode a given
report type uses. Register new report types here rather than branching on
name strings at each call site.

Province/regulator letterhead fields are read from the `provinces` table
(migration 259) rather than hardcoded, so this module works for any Canadian
province Spinr expands into — not just Saskatchewan.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal, TypedDict

BRAND_RGB = (238, 43, 43)  # #ee2b2b — matches utils/receipt_pdf.py's _BRAND
BRAND_HEX = "EE2B2B"
BRAND_FONT = "Helvetica"  # fpdf2 core font name; closest match to product UI font

_ASSET_DIR = Path(__file__).resolve().parents[1] / "static" / "branding"
LOGO_PATH = _ASSET_DIR / "spinr_logo.png"


def has_logo_asset() -> bool:
    """True once the real logo file has been dropped into static/branding/.

    Until then, PDF/Excel/Word branded-report helpers fall back to a text
    wordmark rendered in BRAND_RGB/BRAND_FONT instead of failing.
    """
    return LOGO_PATH.is_file()


ReportMode = Literal["branded", "fixed_format"]


class ReportRegistration(TypedDict):
    mode: ReportMode
    description: str


REPORT_FORMAT_REGISTRY: dict[str, ReportRegistration] = {
    # Fixed-format: real regulator/insurer documents. Generated by
    # services/data_transfer/sgi_form_filler.py, which fills the actual SGI
    # AcroForm PDFs and must never be re-styled with Spinr branding.
    "sgi_driver_details": {
        "mode": "fixed_format",
        "description": "SGI D00032 Passenger for Hire – Driver Details",
    },
    "sgi_vehicle_details": {
        "mode": "fixed_format",
        "description": "SGI D00033 Transportation Network Company – Vehicle Details",
    },
    # Branded: Spinr-designed reports.
    "gst_pst_remittance": {
        "mode": "branded",
        "description": "GST/PST tax remittance summary",
    },
    "insurance_period_audit": {
        "mode": "branded",
        "description": "Driver insurance-period regulatory audit export",
    },
    "dsar_lookup": {
        "mode": "branded",
        "description": "Admin lookup of a rider/driver's self-service DSAR export status",
    },
}


def report_mode(report_type: str) -> ReportMode:
    """Look up whether `report_type` should be Spinr-branded or left in its
    fixed regulator/insurer format. Raises KeyError for unregistered types
    rather than silently defaulting — an unregistered compliance report is a
    bug, not a case to guess at."""
    return REPORT_FORMAT_REGISTRY[report_type]["mode"]
