"""Shared Spinr branding for admin-generated reports (PDF/Excel/Word/CSV).

Two categories of report exist and must never be confused:

- "branded": Spinr's own layout (logo, brand color, font) — used for reports
  we design ourselves (GST/PST remittance, insurance-period audit, DSAR
  lookup). Free to restyle.
- "fixed_format": a regulator's own document (e.g. SGI D00032/D00033,
  Knight Archer, a future province's equivalent) that must be reproduced
  in the exact required layout — never wrap these in Spinr branding, since
  the filled document itself gets submitted to the regulator/insurer.

REPORT_FORMAT_REGISTRY is the single source of truth for which mode a given
report type uses. Register new report types here rather than branching on
name strings at each call site.

Province/regulator letterhead fields are read from the `provinces` table
(migration 259) rather than hardcoded, so this module works for any Canadian
province Spinr expands into — not just Saskatchewan.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal, TypedDict

BRAND_RGB = (238, 43, 43)  # #ee2b2b — matches utils/receipt_pdf.py's _BRAND
BRAND_HEX = "EE2B2B"
BRAND_FONT = "Helvetica"  # fpdf2 core font name; closest match to product UI font

# Report palette: brand red is an accent (thin rule, table-header underline),
# never a full-bleed block — a solid red banner read as an alert/warning
# rather than a professional document header (user feedback on the first
# design pass). Body text is dark charcoal, not pure black, matching how
# print-oriented reports usually read as less harsh.
INK_RGB = (33, 33, 33)  # near-black body/heading text
MUTED_RGB = (110, 110, 110)  # grey subtitle/footer text
MUTED_HEX = "6E6E6E"
HEADER_BG_RGB = (245, 245, 245)  # light grey table-header fill
HEADER_BG_HEX = "F5F5F5"
RULE_RGB = (224, 224, 224)  # light grey divider lines

_ASSET_DIR = Path(__file__).resolve().parents[1] / "static" / "branding"
LOGO_PATH = _ASSET_DIR / "spinr_logo.png"

# Same company identity line used in the rider receipt footer
# (utils/receipt_pdf.py's "Spinr Technologies Inc. - Saskatoon, SK") — kept
# identical here (previously this module's own footer said "Spinr Mobility
# Inc." instead, a naming inconsistency between two Spinr-generated PDFs).
COMPANY_LINE = "Spinr Technologies Inc. - Saskatoon, SK"
COMPANY_CONTACT_LINE = "support@spinr.ca - www.spinr.ca"

# Mirrors services/data_transfer/tabular_writer.py's _sanitize_csv_cell
# (OWASP CSV-injection guard). Duplicated rather than imported: importing
# tabular_writer pulls in services/__init__.py's full service-layer import
# chain (dispatch, settings, supabase client, ...) just for a 5-line helper.
_CSV_INJECTION_LEADS = ("=", "+", "-", "@", "\t", "\r")


def _sanitize_csv_cell(value):
    if isinstance(value, str) and value.startswith(_CSV_INJECTION_LEADS):
        return "'" + value
    return value


def has_logo_asset() -> bool:
    """True once the real logo file has been dropped into static/branding/.

    Until then, PDF/Excel/Word branded-report helpers fall back to a text
    wordmark rendered in BRAND_RGB/BRAND_FONT instead of failing.
    """
    return LOGO_PATH.is_file()


ReportMode = Literal["branded", "fixed_format"]


class ReportRegistration(TypedDict):
    mode: ReportMode
    description: str


REPORT_FORMAT_REGISTRY: dict[str, ReportRegistration] = {
    # Fixed-format: real regulator/insurer documents. Generated by
    # services/data_transfer/sgi_form_filler.py, which fills the actual SGI
    # AcroForm PDFs and must never be re-styled with Spinr branding.
    "sgi_driver_details": {
        "mode": "fixed_format",
        "description": "SGI D00032 Passenger for Hire – Driver Details",
    },
    "sgi_vehicle_details": {
        "mode": "fixed_format",
        "description": "SGI D00033 Transportation Network Company – Vehicle Details",
    },
    # Branded: Spinr-designed reports.
    "gst_pst_remittance": {
        "mode": "branded",
        "description": "GST/PST tax remittance summary",
    },
    "insurance_period_audit": {
        "mode": "branded",
        "description": "Driver insurance-period regulatory audit export",
    },
    "dsar_lookup": {
        "mode": "branded",
        "description": "Admin lookup of a rider/driver's self-service DSAR export status",
    },
    "t4a_filer_handoff": {
        "mode": "branded",
        "description": "Per-driver annual earnings + Stripe-verified address for a third-party T4A filer (never includes SIN)",
    },
    "insurance_usage_billing": {
        "mode": "branded",
        "description": "Per-driver insured kilometres (Period 2+3) and billed amount, for reconciling the insurer's usage-based-insurance invoice",
    },
    "airport_trips": {
        "mode": "branded",
        "description": "Completed rides with an airport pickup or dropoff, for airport ground-transportation program reporting",
    },
}


def report_mode(report_type: str) -> ReportMode:
    """Look up whether `report_type` should be Spinr-branded or left in its
    fixed regulator/insurer format. Raises KeyError for unregistered types
    rather than silently defaulting — an unregistered compliance report is a
    bug, not a case to guess at."""
    return REPORT_FORMAT_REGISTRY[report_type]["mode"]


def pdf_safe(text: str) -> str:
    """fpdf2's core fonts (Helvetica etc.) only support Latin-1 — any
    caller text with an em dash, curly quote, warning glyph, or other
    common-but-non-Latin-1 character crashes FPDFUnicodeEncodingException
    at render time instead of failing at build time. Normalize the
    characters our own report text actually uses, then fall back to '?'
    for anything else so an unexpected character degrades a report instead
    of crashing it outright."""
    text = text.replace("—", "-").replace("–", "-").replace("’", "'").replace("⚠", "!")
    return text.encode("latin-1", errors="replace").decode("latin-1")


def period_label(start_date, end_date) -> str:
    """Render a report's covered date range as ``Period: YYYY-MM-DD to
    YYYY-MM-DD`` — a labeled range reads as a document property; a bare
    "2026-06-30 to 2026-07-30" with no label looks like an unfinished
    sentence at the top of a report. `start_date`/`end_date` accept either
    `datetime`/`date` objects or pre-formatted strings."""
    start = start_date.date().isoformat() if hasattr(start_date, "date") else str(start_date)
    end = end_date.date().isoformat() if hasattr(end_date, "date") else str(end_date)
    return f"Period: {start} to {end}"


def format_report_timestamp(value: "str | None", *, empty: str = "") -> str:
    """Render a DB timestamp column (raw ISO 8601, e.g.
    ``2026-07-29T14:32:10.123456+00:00``) as ``2026-07-29 14:32 UTC`` for a
    report cell — human-readable with a real space between date and time,
    no sub-second precision, and the offset collapsed to a fixed "UTC"
    label (every value in this codebase is already UTC per CLAUDE.md's
    observability conventions; a raw ``+00:00`` reads as visual noise next
    to a plain date).

    Several compliance reports (insurance-period audit's started_at/
    ended_at, Knight Archer's onboarded_at) previously passed the raw ISO
    string straight into the report cell — displaying as one unbroken
    run of digits/punctuation with no date/time separation, which is what
    prompted this helper. Falls back to the raw string for a value that
    isn't ISO-parseable, rather than hiding a real data problem behind a
    blank cell.
    """
    if not value:
        return empty
    try:
        from datetime import datetime as _datetime

        dt = _datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return str(value)
    return dt.strftime("%Y-%m-%d %H:%M") + " UTC"


def new_branded_pdf(title: str, subtitle: "str | list[str]" = "", landscape: bool = False):
    """Return an fpdf2 FPDF instance (A4, portrait unless landscape=True)
    with the standard Spinr branded header already drawn: a thin red accent
    rule at the very top, the logo, dark title text, and a grey subtitle —
    not a full-bleed color block, which reads as an alert banner rather
    than a document header. Caller starts writing content at the current
    cursor position (below the header block) after this returns.

    `subtitle` may be a single string or a list of lines — e.g. a date
    range on one line and per-tax-type totals on a second, rather than
    cramming "2026-06-29 to 2026-07-29 — Total GST $17.91, Total PST
    $0.00, Total HST $0.00" onto one crowded line (the original design,
    reported as reading unprofessionally). Each line gets its own row;
    the header block (and the divider rule under it) grows to fit.

    Pass landscape=True for tables with several columns or long cell
    values (e.g. UUIDs, ISO timestamps) — portrait's ~180mm usable width
    is too narrow for those without wrapping every cell.

    Only for report_type entries registered as "branded" in
    REPORT_FORMAT_REGISTRY — fixed_format reports (SGI etc.) must never call
    this; they fill the regulator's own template via sgi_form_filler.
    """
    from fpdf import FPDF  # type: ignore[import-untyped]

    subtitle_lines = [subtitle] if isinstance(subtitle, str) else list(subtitle)
    subtitle_lines = [line for line in subtitle_lines if line]

    pdf = FPDF(orientation="L" if landscape else "P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    left = 15
    page_w = pdf.w

    # Thin brand-red accent rule across the top edge — the only full-width
    # color in the header, everything else is white background / dark text.
    pdf.set_fill_color(*BRAND_RGB)
    pdf.rect(0, 0, page_w, 3, "F")

    # Logo height matched to the title's cap-height (17pt bold ≈ 6mm caps)
    # plus headroom, rather than the earlier 11mm, which rendered visibly
    # smaller than the title text next to it.
    pdf.set_xy(left, 8)
    if has_logo_asset():
        pdf.image(str(LOGO_PATH), x=left, y=8, h=14)
        pdf.set_xy(left + 36, 11)
    pdf.set_text_color(*INK_RGB)
    pdf.set_font(BRAND_FONT, "B", 17)
    pdf.cell(0, 8, pdf_safe(title), ln=True)
    pdf.set_x(left + (36 if has_logo_asset() else 0))
    pdf.set_text_color(*MUTED_RGB)
    pdf.set_font(BRAND_FONT, "", 10)
    for line in subtitle_lines:
        pdf.set_x(left + (36 if has_logo_asset() else 0))
        pdf.cell(0, 6, pdf_safe(line), ln=True)

    # Divider rule under the header block — grows with the number of
    # subtitle lines instead of a fixed y=30 that a 2-line subtitle would
    # overrun into.
    divider_y = 24 + max(1, len(subtitle_lines)) * 6
    pdf.set_draw_color(*RULE_RGB)
    pdf.line(left, divider_y, page_w - left, divider_y)

    pdf.set_y(divider_y + 6)
    pdf.set_text_color(*INK_RGB)
    # Reset fill from the top accent rule — otherwise fpdf2's Table API
    # (render_pdf_table) would inherit brand red as every cell's
    # background, including data rows that should stay white.
    pdf.set_fill_color(255, 255, 255)
    return pdf


def new_branded_workbook(title: str, subtitle: "str | list[str]" = ""):
    """Return (Workbook, Worksheet) with a Spinr-branded title block:
    the logo image (if the asset exists) anchored at A1, title (dark,
    bold) and subtitle (grey) in the columns beside it, then a thin
    brand-red rule under row 4. Caller starts writing its header row at
    DEFAULT_TABLE_START_ROW (row 6) — logo image height needs more
    vertical room than plain text did.

    `subtitle` may be a single string or a list of lines (see
    new_branded_pdf's docstring for why) — each line gets its own row
    starting at row 2, so the accent rule (row 4) and table start
    (DEFAULT_TABLE_START_ROW) still line up as long as at most 2 lines
    are passed (the only caller today uses at most 2).

    Only for report_type entries registered as "branded" — fixed_format
    reports never go through openpyxl branding; they fill the regulator's
    own template.
    """
    from openpyxl import Workbook  # noqa: PLC0415 — optional dep, only needed for this format
    from openpyxl.styles import Font, PatternFill

    wb = Workbook()
    ws = wb.active
    ws.title = "report"

    title_col = "A"
    if has_logo_asset():
        from openpyxl.drawing.image import Image as XLImage

        img = XLImage(str(LOGO_PATH))
        # 48px (was 40px) to match the title's visual weight — the smaller
        # size read as an afterthought next to 14pt bold title text.
        target_h = 48
        scale = target_h / img.height
        img.height = target_h
        img.width = int(img.width * scale)
        img.anchor = "A1"
        ws.add_image(img)
        ws.row_dimensions[1].height = 36
        ws.row_dimensions[2].height = 36
        title_col = "C"  # leave room beside the logo image

    ws[f"{title_col}1"] = title
    ws[f"{title_col}1"].font = Font(name=BRAND_FONT, bold=True, size=14, color="212121")
    subtitle_lines = [subtitle] if isinstance(subtitle, str) else list(subtitle)
    subtitle_lines = [line for line in subtitle_lines if line]
    for i, line in enumerate(subtitle_lines[:2]):
        cell = ws[f"{title_col}{2 + i}"]
        cell.value = line
        cell.font = Font(name=BRAND_FONT, size=10, color=MUTED_HEX)

    # Thin brand-red accent rule under the header block (row 4), matching
    # the PDF/Word header treatment — accent only, not a full color block.
    rule_fill = PatternFill(start_color=BRAND_HEX, end_color=BRAND_HEX, fill_type="solid")
    for col in range(1, 9):
        ws.cell(row=4, column=col).fill = rule_fill
    ws.row_dimensions[4].height = 2
    return wb, ws


DEFAULT_TABLE_START_ROW = 6


def write_branded_table(ws, fieldnames: list[str], rows: list[dict], start_row: int = DEFAULT_TABLE_START_ROW) -> None:
    """Write a header row (light-grey fill, dark bold text — not a full
    brand-red block) at `start_row` followed by one row per dict in `rows`,
    using the same CSV-injection-safe cell sanitization as
    services/data_transfer/tabular_writer.py so a value round-tripped
    through either export path renders identically in Excel."""
    from openpyxl.styles import Font, PatternFill

    header_fill = PatternFill(start_color=HEADER_BG_HEX, end_color=HEADER_BG_HEX, fill_type="solid")
    header_font = Font(name=BRAND_FONT, bold=True, color="212121")

    for col, name in enumerate(fieldnames, start=1):
        cell = ws.cell(row=start_row, column=col, value=name.replace("_", " ").title())
        cell.fill = header_fill
        cell.font = header_font

    for r, row in enumerate(rows, start=start_row + 1):
        for col, name in enumerate(fieldnames, start=1):
            ws.cell(row=r, column=col, value=_sanitize_csv_cell(row.get(name)))


def new_branded_document(title: str, subtitle: "str | list[str]" = ""):
    """Return a python-docx Document with a Spinr-branded title block: the
    logo image (if the asset exists), a dark heading (not brand-red — a
    full-color heading read as an alert rather than a document title), an
    optional grey subtitle (one or more lines — see new_branded_pdf's
    docstring for why), a thin brand-red accent rule, then a blank
    paragraph spacer. Caller appends its own content (paragraphs, tables)
    after this returns.

    Only for report_type entries registered as "branded" — fixed_format
    reports never go through python-docx branding.
    """
    from docx import Document
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Inches, Pt, RGBColor

    doc = Document()

    if has_logo_asset():
        logo_para = doc.add_paragraph()
        # 0.42in (was 0.35in) to match the heading's visual weight.
        logo_para.add_run().add_picture(str(LOGO_PATH), height=Inches(0.42))

    heading = doc.add_heading(title, level=1)
    for run in heading.runs:
        run.font.color.rgb = RGBColor(*INK_RGB)
        run.font.name = BRAND_FONT

    subtitle_lines = [subtitle] if isinstance(subtitle, str) else list(subtitle)
    for line in subtitle_lines:
        if not line:
            continue
        sub = doc.add_paragraph(line)
        sub.runs[0].font.size = Pt(10)
        sub.runs[0].font.color.rgb = RGBColor(*MUTED_RGB)

    # Thin brand-red accent rule via a paragraph bottom-border (python-docx
    # has no table/rule primitive) — deliberately NOT a 1-cell table, which
    # would pollute doc.tables[0] ahead of the caller's own data table.
    rule_para = doc.add_paragraph()
    p_pr = rule_para._p.get_or_add_pPr()
    p_bdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "18")  # eighths of a point; ~2.25pt rule
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), BRAND_HEX)
    p_bdr.append(bottom)
    p_pr.append(p_bdr)

    doc.add_paragraph("")
    return doc


def add_branded_table(doc, fieldnames: list[str], rows: list[dict]) -> None:
    """Append a table to a python-docx Document: header row (light-grey
    shading, dark bold text — not a full brand-red block) followed by one
    row per dict in `rows`. Cell values are not CSV-sanitized (Word has no
    formula-injection risk the way CSV/Excel do when opened by a
    spreadsheet app)."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import RGBColor

    table = doc.add_table(rows=1, cols=len(fieldnames))
    table.style = "Table Grid"
    header_cells = table.rows[0].cells
    for col, name in enumerate(fieldnames):
        header_cells[col].text = name.replace("_", " ").title()
        run = header_cells[col].paragraphs[0].runs[0]
        run.font.bold = True
        run.font.color.rgb = RGBColor(*INK_RGB)
        shading = OxmlElement("w:shd")
        shading.set(qn("w:fill"), HEADER_BG_HEX)
        header_cells[col]._tc.get_or_add_tcPr().append(shading)

    for row in rows:
        cells = table.add_row().cells
        for col, name in enumerate(fieldnames):
            cells[col].text = str(row.get(name, "") if row.get(name) is not None else "")


def render_pdf_table(
    pdf,
    fieldnames: list[str],
    rows: list[dict],
    col_widths: list[float] | None = None,
    font_size: int = 8,
) -> None:
    """Render a table into a branded PDF using fpdf2's native Table API,
    which wraps long cell text and syncs row heights automatically —
    unlike hand-rolled fixed-width pdf.cell() calls, which clip/overlap
    instead of wrapping when content (UUIDs, ISO timestamps, long labels)
    exceeds the column width.

    col_widths are relative ratios (not absolute mm) across the fieldnames,
    e.g. [2, 3, 2, 2, 2, 2] to give column 2 more room than the others;
    omit for equal-width columns.
    """
    from fpdf.fonts import FontFace  # type: ignore[import-untyped]

    header_names = [pdf_safe(name.replace("_", " ").title()) for name in fieldnames]
    pdf.set_font(BRAND_FONT, "", font_size)
    pdf.set_text_color(*INK_RGB)
    # Light grey header (not full brand-red) with dark bold text — a
    # professional table header, not an alert banner; matches the toned-down
    # header treatment in new_branded_pdf().
    headings_style = FontFace(emphasis="BOLD", color=INK_RGB, fill_color=HEADER_BG_RGB)
    with pdf.table(
        col_widths=col_widths,
        text_align="LEFT",
        headings_style=headings_style,
    ) as table:
        header_row = table.row()
        for name in header_names:
            header_row.cell(name)
        for row in rows:
            data_row = table.row()
            for name in fieldnames:
                data_row.cell(pdf_safe(str(row.get(name, ""))))


def render_branded_pdf_footer(pdf, province_letterhead: dict | None = None) -> None:
    """Draw a small grey footer at the bottom of the current page: the
    company identity/contact line (always shown — registered address and
    contact info is expected on every generated document, not just
    province-scoped ones) plus an optional province/regulator letterhead
    line (from the `provinces` table, e.g. {"name": "Saskatchewan",
    "default_regulatory_authority": "SGI"}) when the report is
    province-scoped. Pass province_letterhead=None for reports that aren't
    province-scoped (e.g. a company-wide DSAR lookup) — the company line
    still renders."""
    pdf.set_font(BRAND_FONT, "", 7)
    pdf.set_text_color(*MUTED_RGB)
    pdf.set_y(-18)
    pdf.cell(0, 4.5, pdf_safe(f"{COMPANY_LINE}  |  {COMPANY_CONTACT_LINE}"), align="C", ln=True)
    if province_letterhead:
        name = province_letterhead.get("name", "")
        authority = province_letterhead.get("default_regulatory_authority", "")
        line = f"Province: {name}" + (f"  |  Regulator of record: {authority}" if authority else "")
        pdf.set_x(15)
        pdf.cell(0, 4.5, pdf_safe(line), align="C")
