const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Creates the Android ride-offer channel natively, with its sound routed to the
// RING volume stream (AudioAttributes.USAGE_NOTIFICATION_RINGTONE) instead of
// the NOTIFICATION stream.
//
// Why: while the app is open, the offer tone is the in-app MP3 loop
// (hooks/useRideOfferSound.ts), which plays on the MEDIA stream. Once the app
// is minimised or killed, expo-audio pauses that player and the OS notification
// takes over the ring (services/notifeeService.ts). Notifee's createChannel
// always builds the channel's AudioAttributes with USAGE_NOTIFICATION and has no
// option to change it, so the minimised offer played at the phone's
// "Notifications" volume. On many devices (Samsung in particular) that slider
// sits well below media/ring, and drivers reported a loud offer in-app but a
// barely audible one when minimised (vibration was fine — it ignores volume).
// Ring volume is what an incoming phone call uses, which matches the
// CATEGORY_CALL "incoming call" style this notification already uses.
//
// Why native, and in Application.onCreate: Android channel sound settings are
// immutable once a channel exists, so ride-offers-v4 must be created with the
// right AudioAttributes BEFORE anything in JS can touch that id. onCreate runs
// before any JS, including the headless launch Firebase does for a data-only
// offer push while the app is killed. notifeeService.ts only posts to v4 when
// it finds the channel already present, and never creates v4 itself — so a
// binary without this plugin (or where this code failed) keeps using the
// Notifee-created ride-offers-v3 exactly as before, instead of JS locking v4 in
// with the quiet notification stream forever.
//
// Must run after withRideOfferSound (which copies ride_offer.mp3 into
// res/raw). The Kotlin side looks the resource up by name and skips channel
// creation if it is missing, so a missing file degrades to v3, never to a
// silent v4.
//
// Native change — ships in an EAS build, not an OTA update.

const CHANNEL_ID = 'ride-offers-v4';
const KOTLIN_CLASS = 'RideOfferRingChannel';
const CALL_MARKER = `${KOTLIN_CLASS}.ensure(this)`;

function buildKotlinSource(packageName) {
    return `package ${packageName}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.ContentResolver
import android.content.Context
import android.graphics.Color
import android.media.AudioAttributes
import android.net.Uri
import android.os.Build
import android.util.Log

// Generated by plugins/withRideOfferRingChannel.js — edit the plugin, not this file.
object ${KOTLIN_CLASS} {
    const val CHANNEL_ID = "${CHANNEL_ID}"
    private const val TAG = "${KOTLIN_CLASS}"

    fun ensure(context: Context) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        try {
            val manager = context.getSystemService(NotificationManager::class.java) ?: return
            // Immutable once created; the driver's own per-channel changes
            // (Settings -> Notifications) must survive every cold start.
            if (manager.getNotificationChannel(CHANNEL_ID) != null) return

            val soundId = context.resources.getIdentifier("ride_offer", "raw", context.packageName)
            if (soundId == 0) {
                // Without the sound this channel would ring the default tone at
                // best. Skip it: notifeeService.ts falls back to ride-offers-v3.
                Log.e(TAG, "res/raw/ride_offer missing — ring-volume ride-offer channel NOT created")
                return
            }
            val soundUri = Uri.parse(
                ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + context.packageName + "/" + soundId
            )
            val audioAttributes = AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()

            // Mirrors the ride-offers-v3 settings in services/notifeeService.ts;
            // the only intended difference is the RINGTONE audio usage.
            val channel = NotificationChannel(CHANNEL_ID, "Ride Offers", NotificationManager.IMPORTANCE_HIGH).apply {
                description = "New ride requests — rings at call volume like an incoming call"
                setSound(soundUri, audioAttributes)
                enableVibration(true)
                vibrationPattern = longArrayOf(0, 300, 500, 300, 500)
                enableLights(true)
                lightColor = Color.GREEN
                setBypassDnd(true)
                lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            }
            manager.createNotificationChannel(channel)
        } catch (e: Exception) {
            // Never crash app start over this — notifeeService.ts falls back
            // to ride-offers-v3 when this channel does not exist.
            Log.e(TAG, "failed to create ring-volume ride-offer channel", e)
        }
    }
}
`;
}

// Inserts the ensure() call right after super.onCreate() in MainApplication's
// onCreate. Throws when the anchor is missing: a template change must fail the
// build loudly rather than ship a binary where offers silently stay quiet.
function injectEnsureCall(contents, language) {
    if (contents.includes(CALL_MARKER)) return contents;
    if (language !== 'kt') {
        throw new Error(`[withRideOfferRingChannel] expected a Kotlin MainApplication, got '${language}'`);
    }
    const anchor = /(override fun onCreate\(\)\s*\{\s*\n(\s*)super\.onCreate\(\)[^\n]*\n)/;
    const match = contents.match(anchor);
    if (!match) {
        throw new Error('[withRideOfferRingChannel] could not find super.onCreate() in MainApplication.onCreate');
    }
    const indent = match[2];
    return contents.replace(anchor, `$1${indent}${CALL_MARKER}\n`);
}

function withRideOfferRingChannelSource(config) {
    return withDangerousMod(config, [
        'android',
        (cfg) => {
            const packageName = cfg.android && cfg.android.package;
            if (!packageName) {
                throw new Error('[withRideOfferRingChannel] android.package is not set');
            }
            const dir = path.join(
                cfg.modRequest.platformProjectRoot,
                'app/src/main/java',
                ...packageName.split('.'),
            );
            fs.mkdirSync(dir, { recursive: true });
            fs.writeFileSync(path.join(dir, `${KOTLIN_CLASS}.kt`), buildKotlinSource(packageName));
            return cfg;
        },
    ]);
}

function withRideOfferRingChannelCall(config) {
    return withMainApplication(config, (cfg) => {
        cfg.modResults.contents = injectEnsureCall(cfg.modResults.contents, cfg.modResults.language);
        return cfg;
    });
}

const withRideOfferRingChannel = (config) =>
    withRideOfferRingChannelCall(withRideOfferRingChannelSource(config));

module.exports = withRideOfferRingChannel;
module.exports.CHANNEL_ID = CHANNEL_ID;
module.exports.buildKotlinSource = buildKotlinSource;
module.exports.injectEnsureCall = injectEnsureCall;
