const {
  withEntitlementsPlist,
  withInfoPlist,
  withAndroidManifest,
  withDangerousMod,
  withXcodeProject,
  IOSConfig,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// ─────────────────────────────────────────────────────────────────────────────
// CarPlay (iOS) + Android Auto config plugin for the Spinr driver app.
//
// SPIKE STATUS — this wires the native scaffolding @g4rb4g3/react-native-carplay
// needs, but it MUST be proven by an EAS dev build before anything relies on it.
// The two things most likely to need a tweak on first build:
//   1. the CarSceneDelegate import path (static-lib vs use_frameworks linkage),
//   2. the dual-scene Info.plist not disturbing the phone app's cold start.
// See docs/carplay-android-auto.md → "Spike checklist".
//
// Why the iOS side is small:
//   We declare ONLY the CarPlay scene (CPTemplateApplicationSceneSessionRole-
//   Application), not a phone UIWindowScene. The existing AppDelegate-based phone
//   window is left untouched, which keeps the blast radius off the phone app's
//   launch path. iOS instantiates CarSceneDelegate for the car scene via the
//   Info.plist role→delegate mapping (no AppDelegate change required).
//
// Why the Android side is tiny:
//   The fork's OWN AndroidManifest already declares the CarAppService, the
//   androidx.car.app.category.NAVIGATION intent filter, the car-app permissions
//   and minCarApiLevel — the manifest merger pulls those in. The fork's service
//   is `foregroundServiceType="location"`, so we only ensure the two
//   foreground-service-location permissions exist (idempotent; expo-location may
//   already declare FOREGROUND_SERVICE).
// ─────────────────────────────────────────────────────────────────────────────

const CARPLAY_ENTITLEMENT = 'com.apple.developer.carplay-driving-task';
const CAR_SCENE_DELEGATE = 'CarSceneDelegate';

// The managed CarPlay "Driving Task" entitlement only signs successfully once
// Apple has GRANTED it AND the App ID / provisioning profile include it. Until
// then, adding it unconditionally makes every signed iOS build fail code-signing
// with a profile-entitlement mismatch. So it is OFF by default and opt-in via env
// once provisioning is ready:  `SPINR_CARPLAY_ENTITLEMENT=1 npx expo prebuild`
// (or set it in the EAS build profile's `env`). The CarPlay scene manifest +
// CarSceneDelegate stay unconditional — they compile/sign fine without the
// entitlement; only the entitlement itself trips signing.
const ENABLE_CARPLAY_ENTITLEMENT = process.env.SPINR_CARPLAY_ENTITLEMENT === '1';

// Android permissions for the car app. The fork's OWN AndroidManifest already
// declares the CarAppService + these car-app template permissions + minCarApiLevel,
// and AGP merges a library module's manifest into the app — so the service is
// exposed without us re-declaring it (re-declaring the <service> would risk a
// duplicate-node merge conflict). We still declare the template permissions
// explicitly as belt-and-suspenders (uses-permission dedupes on merge — same
// approach as withNotifeePermissions.js), alongside the foreground-service-location
// perms the fork's `foregroundServiceType="location"` service needs.
const ANDROID_PERMISSIONS = [
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_LOCATION',
  'androidx.car.app.NAVIGATION_TEMPLATES',
  'androidx.car.app.MAP_TEMPLATES',
  'androidx.car.app.ACCESS_SURFACE',
];

const CAR_SCENE_DELEGATE_H = `// AUTO-GENERATED by plugins/withCarIntegration.js — do not edit by hand.
#import <UIKit/UIKit.h>
#import <CarPlay/CarPlay.h>

@interface ${CAR_SCENE_DELEGATE} : UIResponder <CPTemplateApplicationSceneDelegate>
@end
`;

// The __has_include guard covers both static-library and use_frameworks linkage,
// since the Spinr Podfile linkage can flip when Firebase / other pods toggle it.
const CAR_SCENE_DELEGATE_M = `// AUTO-GENERATED by plugins/withCarIntegration.js — do not edit by hand.
#import "${CAR_SCENE_DELEGATE}.h"

#if __has_include(<react_native_carplay/RNCarPlay.h>)
#import <react_native_carplay/RNCarPlay.h>
#elif __has_include("RNCarPlay.h")
#import "RNCarPlay.h"
#else
@import react_native_carplay;
#endif

@implementation ${CAR_SCENE_DELEGATE}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
   didConnectInterfaceController:(CPInterfaceController *)interfaceController
                        toWindow:(CPWindow *)window {
  [RNCarPlay connectWithInterfaceController:interfaceController window:window];
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
didDisconnectInterfaceController:(CPInterfaceController *)interfaceController
                      fromWindow:(CPWindow *)window {
  [RNCarPlay disconnect];
}

@end
`;

function withCarPlayEntitlement(config) {
  // Opt-in only — see ENABLE_CARPLAY_ENTITLEMENT above. Skipping it leaves iOS
  // builds signable before Apple grants the managed entitlement.
  if (!ENABLE_CARPLAY_ENTITLEMENT) return config;
  return withEntitlementsPlist(config, (cfg) => {
    cfg.modResults[CARPLAY_ENTITLEMENT] = true;
    return cfg;
  });
}

function withCarPlaySceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    const plist = cfg.modResults;
    const manifest = plist.UIApplicationSceneManifest || {};
    manifest.UIApplicationSupportsMultipleScenes = true;
    const sceneConfigs = manifest.UISceneConfigurations || {};
    sceneConfigs.CPTemplateApplicationSceneSessionRoleApplication = [
      {
        UISceneConfigurationName: 'CarPlay',
        UISceneDelegateClassName: CAR_SCENE_DELEGATE,
      },
    ];
    manifest.UISceneConfigurations = sceneConfigs;
    plist.UIApplicationSceneManifest = manifest;
    return cfg;
  });
}

function withCarSceneDelegateFile(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const { projectName, platformProjectRoot } = cfg.modRequest;
      const iosDir = path.join(platformProjectRoot, projectName);
      fs.mkdirSync(iosDir, { recursive: true });
      fs.writeFileSync(path.join(iosDir, `${CAR_SCENE_DELEGATE}.h`), CAR_SCENE_DELEGATE_H);
      fs.writeFileSync(path.join(iosDir, `${CAR_SCENE_DELEGATE}.m`), CAR_SCENE_DELEGATE_M);
      return cfg;
    },
  ]);
}

function withCarSceneDelegateInXcode(config) {
  return withXcodeProject(config, (cfg) => {
    const { projectName } = cfg.modRequest;
    const relPath = `${projectName}/${CAR_SCENE_DELEGATE}.m`;
    const project = cfg.modResults;
    const alreadyAdded =
      typeof project.hasFile === 'function' ? project.hasFile(relPath) : false;
    if (!alreadyAdded) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: relPath,
        groupName: projectName,
        project,
      });
    }
    return cfg;
  });
}

function withAndroidAutoPermissions(config) {
  return withAndroidManifest(config, (cfg) => {
    const { manifest } = cfg.modResults;
    manifest['uses-permission'] = manifest['uses-permission'] || [];
    const existing = new Set(
      manifest['uses-permission']
        .map((p) => p && p.$ && p.$['android:name'])
        .filter(Boolean)
    );
    for (const name of ANDROID_PERMISSIONS) {
      if (!existing.has(name)) {
        manifest['uses-permission'].push({ $: { 'android:name': name } });
      }
    }
    return cfg;
  });
}

const withCarIntegration = (config) => {
  // iOS — CarPlay
  config = withCarPlayEntitlement(config);
  config = withCarPlaySceneManifest(config);
  config = withCarSceneDelegateFile(config);
  config = withCarSceneDelegateInXcode(config);
  // Android — Android Auto (the fork's manifest supplies the CarAppService; we add
  // the car-app + foreground-service permissions defensively)
  config = withAndroidAutoPermissions(config);
  return config;
};

module.exports = withCarIntegration;
