const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Removes the Android ride-offers-v4 channel created by an earlier revision of
// this plugin.
//
// That revision created the channel with AudioAttributes.USAGE_NOTIFICATION_RINGTONE
// so a minimised offer would play at ring volume. On device Android treats that
// usage as a phone ringtone and does not show a shade or heads-up notification
// (full-screen intent is not granted to this app). Drivers with the app open
// still heard the in-app MP3; drivers with the app minimised got nothing.
// Channel settings are immutable, so the bad channel has to be deleted, not
// edited. notifeeService.ts posts on ride-offers-v3 and also deletes v4 from JS.
// This native delete runs in Application.onCreate so a cold start, including
// the headless FCM launch, drops v4 before any offer is posted.
//
// Native change — ships in an EAS build, not an OTA update. The JS delete in
// notifeeService.ts covers a binary that still contains the old create code.

const CHANNEL_ID = 'ride-offers-v4';
const KOTLIN_CLASS = 'RideOfferRingChannel';
const CALL_MARKER = `${KOTLIN_CLASS}.ensure(this)`;

function buildKotlinSource(packageName) {
    return `package ${packageName}

import android.app.NotificationManager
import android.content.Context
import android.os.Build
import android.util.Log

// Generated by plugins/withRideOfferRingChannel.js — edit the plugin, not this file.
object ${KOTLIN_CLASS} {
    const val CHANNEL_ID = "${CHANNEL_ID}"
    private const val TAG = "${KOTLIN_CLASS}"

    fun ensure(context: Context) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        try {
            val manager = context.getSystemService(NotificationManager::class.java) ?: return
            // Immutable, and this usage hides the notification. Delete it so
            // the Notifee v3 channel is the one offers post to.
            if (manager.getNotificationChannel(CHANNEL_ID) != null) {
                manager.deleteNotificationChannel(CHANNEL_ID)
            }
        } catch (e: Exception) {
            // Never crash app start over this — notifeeService.ts also deletes
            // this channel and posts on ride-offers-v3.
            Log.e(TAG, "failed to remove ring-volume ride-offer channel", e)
        }
    }
}
`;
}

// Inserts the ensure() call right after super.onCreate() in MainApplication's
// onCreate. Throws when the anchor is missing: a template change must fail the
// build loudly rather than ship a binary where offers silently stay quiet.
function injectEnsureCall(contents, language) {
    if (contents.includes(CALL_MARKER)) return contents;
    if (language !== 'kt') {
        throw new Error(`[withRideOfferRingChannel] expected a Kotlin MainApplication, got '${language}'`);
    }
    const anchor = /(override fun onCreate\(\)\s*\{\s*\n(\s*)super\.onCreate\(\)[^\n]*\n)/;
    const match = contents.match(anchor);
    if (!match) {
        throw new Error('[withRideOfferRingChannel] could not find super.onCreate() in MainApplication.onCreate');
    }
    const indent = match[2];
    return contents.replace(anchor, `$1${indent}${CALL_MARKER}\n`);
}

function withRideOfferRingChannelSource(config) {
    return withDangerousMod(config, [
        'android',
        (cfg) => {
            const packageName = cfg.android && cfg.android.package;
            if (!packageName) {
                throw new Error('[withRideOfferRingChannel] android.package is not set');
            }
            const dir = path.join(
                cfg.modRequest.platformProjectRoot,
                'app/src/main/java',
                ...packageName.split('.'),
            );
            fs.mkdirSync(dir, { recursive: true });
            fs.writeFileSync(path.join(dir, `${KOTLIN_CLASS}.kt`), buildKotlinSource(packageName));
            return cfg;
        },
    ]);
}

function withRideOfferRingChannelCall(config) {
    return withMainApplication(config, (cfg) => {
        cfg.modResults.contents = injectEnsureCall(cfg.modResults.contents, cfg.modResults.language);
        return cfg;
    });
}

const withRideOfferRingChannel = (config) =>
    withRideOfferRingChannelCall(withRideOfferRingChannelSource(config));

module.exports = withRideOfferRingChannel;
module.exports.CHANNEL_ID = CHANNEL_ID;
module.exports.buildKotlinSource = buildKotlinSource;
module.exports.injectEnsureCall = injectEnsureCall;
