const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Two native ride-offer channel jobs in Application.onCreate, before any JS
// (including the headless FCM launch) can post an offer:
//
// 1. Creates ride-offers-alarm-v1, whose sound plays on the ALARM stream
//    (AudioAttributes.USAGE_ALARM). The alarm stream is not muted by silent or
//    vibrate ringer mode, follows the alarm volume slider, and Do Not Disturb
//    lets alarm sound through by default (the card under DND still depends on
//    DND access, which this app does not request). Notifee's createChannel always uses the
//    notification stream and cannot set AudioAttributes, so this has to be
//    native. notifeeService.ts posts to it only when the offer carries
//    ring_mode=alarm (settings flag ride_offer_alarm_channel_enabled,
//    migration 471) AND this channel exists and is not blocked; otherwise it
//    posts on ride-offers-v3 as before. JS never creates this channel.
//    Unverified on hardware when written: the v4 ringtone attempt below hid
//    the minimised offer, so this needs a device test (debug-ride-offer with
//    ring_mode=alarm) before the flag is turned on.
//
// 2. Removes the Android ride-offers-v4 channel created by an earlier revision
//    of this plugin.
//
// That revision created the channel with AudioAttributes.USAGE_NOTIFICATION_RINGTONE
// so a minimised offer would play at ring volume. On device Android treats that
// usage as a phone ringtone and does not show a shade or heads-up notification
// (full-screen intent is not granted to this app). Drivers with the app open
// still heard the in-app MP3; drivers with the app minimised got nothing.
// Channel settings are immutable, so the bad channel has to be deleted, not
// edited. notifeeService.ts posts on ride-offers-v3 and also deletes v4 from JS.
// This native delete runs in Application.onCreate so a cold start, including
// the headless FCM launch, drops v4 before any offer is posted.
//
// Native change — ships in an EAS build, not an OTA update. The JS delete in
// notifeeService.ts covers a binary that still contains the old create code.

const CHANNEL_ID = 'ride-offers-v4';
const ALARM_CHANNEL_ID = 'ride-offers-alarm-v1';
const KOTLIN_CLASS = 'RideOfferRingChannel';
const CALL_MARKER = `${KOTLIN_CLASS}.ensure(this)`;

function buildKotlinSource(packageName) {
    return `package ${packageName}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.ContentResolver
import android.content.Context
import android.graphics.Color
import android.media.AudioAttributes
import android.net.Uri
import android.os.Build
import android.util.Log

// Generated by plugins/withRideOfferRingChannel.js — edit the plugin, not this file.
object ${KOTLIN_CLASS} {
    const val CHANNEL_ID = "${CHANNEL_ID}"
    const val ALARM_CHANNEL_ID = "${ALARM_CHANNEL_ID}"
    private const val TAG = "${KOTLIN_CLASS}"

    fun ensure(context: Context) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        val manager = context.getSystemService(NotificationManager::class.java) ?: return
        removeRingChannel(manager)
        createAlarmChannel(context, manager)
    }

    private fun removeRingChannel(manager: NotificationManager) {
        try {
            // Immutable, and this usage hides the notification. Delete it so
            // the Notifee v3 channel is the one offers post to.
            if (manager.getNotificationChannel(CHANNEL_ID) != null) {
                manager.deleteNotificationChannel(CHANNEL_ID)
            }
        } catch (e: Exception) {
            // Never crash app start over this — notifeeService.ts also deletes
            // this channel and posts on ride-offers-v3.
            Log.e(TAG, "failed to remove ring-volume ride-offer channel", e)
        }
    }

    private fun createAlarmChannel(context: Context, manager: NotificationManager) {
        try {
            // Immutable once created; the driver's own per-channel changes
            // (Settings -> Notifications) must survive every cold start.
            if (manager.getNotificationChannel(ALARM_CHANNEL_ID) != null) return

            val soundId = context.resources.getIdentifier("ride_offer", "raw", context.packageName)
            if (soundId == 0) {
                // Without the sound this channel would ring the default tone at
                // best. Skip it: notifeeService.ts falls back to ride-offers-v3.
                Log.e(TAG, "res/raw/ride_offer missing — alarm-volume ride-offer channel NOT created")
                return
            }
            val soundUri = Uri.parse(
                ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + context.packageName + "/" + soundId
            )
            val audioAttributes = AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_ALARM)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()

            // Mirrors ride-offers-v3 in services/notifeeService.ts; the only
            // intended difference is the ALARM audio usage.
            val channel = NotificationChannel(ALARM_CHANNEL_ID, "Ride Offers (loud)", NotificationManager.IMPORTANCE_HIGH).apply {
                description = "New ride requests at alarm volume — rings even when the phone is on silent"
                setSound(soundUri, audioAttributes)
                enableVibration(true)
                vibrationPattern = longArrayOf(0, 300, 500, 300, 500)
                enableLights(true)
                lightColor = Color.GREEN
                setBypassDnd(true)
                lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            }
            manager.createNotificationChannel(channel)
        } catch (e: Exception) {
            // Never crash app start over this — notifeeService.ts falls back
            // to ride-offers-v3 when this channel does not exist.
            Log.e(TAG, "failed to create alarm-volume ride-offer channel", e)
        }
    }
}
`;
}

// Inserts the ensure() call right after super.onCreate() in MainApplication's
// onCreate. Throws when the anchor is missing: a template change must fail the
// build loudly rather than ship a binary where offers silently stay quiet.
function injectEnsureCall(contents, language) {
    if (contents.includes(CALL_MARKER)) return contents;
    if (language !== 'kt') {
        throw new Error(`[withRideOfferRingChannel] expected a Kotlin MainApplication, got '${language}'`);
    }
    const anchor = /(override fun onCreate\(\)\s*\{\s*\n(\s*)super\.onCreate\(\)[^\n]*\n)/;
    const match = contents.match(anchor);
    if (!match) {
        throw new Error('[withRideOfferRingChannel] could not find super.onCreate() in MainApplication.onCreate');
    }
    const indent = match[2];
    return contents.replace(anchor, `$1${indent}${CALL_MARKER}\n`);
}

function withRideOfferRingChannelSource(config) {
    return withDangerousMod(config, [
        'android',
        (cfg) => {
            const packageName = cfg.android && cfg.android.package;
            if (!packageName) {
                throw new Error('[withRideOfferRingChannel] android.package is not set');
            }
            const dir = path.join(
                cfg.modRequest.platformProjectRoot,
                'app/src/main/java',
                ...packageName.split('.'),
            );
            fs.mkdirSync(dir, { recursive: true });
            fs.writeFileSync(path.join(dir, `${KOTLIN_CLASS}.kt`), buildKotlinSource(packageName));
            return cfg;
        },
    ]);
}

function withRideOfferRingChannelCall(config) {
    return withMainApplication(config, (cfg) => {
        cfg.modResults.contents = injectEnsureCall(cfg.modResults.contents, cfg.modResults.language);
        return cfg;
    });
}

const withRideOfferRingChannel = (config) =>
    withRideOfferRingChannelCall(withRideOfferRingChannelSource(config));

module.exports = withRideOfferRingChannel;
module.exports.CHANNEL_ID = CHANNEL_ID;
module.exports.ALARM_CHANNEL_ID = ALARM_CHANNEL_ID;
module.exports.buildKotlinSource = buildKotlinSource;
module.exports.injectEnsureCall = injectEnsureCall;
