# fly.toml app configuration file generated for spinrvm on 2026-09-10T20:06:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spinrvm'
primary_region = 'yyz'
kill_signal = 'SIGINT'
kill_timeout = '15s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  ENV = 'production'
  HERMES_PUBLIC_URL = 'https://hermes-spinr.fly.dev'
  LOG_LEVEL = 'info'
  PORT = '8585'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 300
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
