/**
 * Display-only location for the Android Auto map, when the phone app is closed.
 *
 * ─── The problem ────────────────────────────────────────────────────────────
 * Android Auto starts the app's JS context, not its phone UI. In that state the
 * process is, as far as Android is concerned, backgrounded — and a backgrounded
 * app with no foreground service gets its foreground location updates throttled
 * hard. `useCarLocation`'s watchPositionAsync goes quiet for minutes at a time,
 * so the car marker sits where the driver was, not where they are. That is the
 * "it shows where I started" report, and no amount of re-requesting inside the
 * hook fixes it, because the throttle is applied to the process, not the call.
 *
 * Google Maps and Waze solve this the same way: a foreground service. This is
 * ours, and it is deliberately the smallest possible one.
 *
 * ─── What makes this different from utils/backgroundLocation.ts ─────────────
 * That module exists to feed DISPATCH: it records durable trip samples to SQLite
 * and uploads them to /drivers/location-batch. Reusing it here would have been
 * wrong twice over:
 *
 *   1. `startBackgroundLocation()` calls requestBackgroundPermissionsAsync() when
 *      permission is missing. A permission dialog raised from a head unit, at
 *      driving speed, is not acceptable. This module NEVER prompts — if the
 *      permission is not already held, it declines to start and the existing
 *      in-hook watcher stands.
 *   2. Its task handler POSTs the driver's position. An OFFLINE driver — one who
 *      has not gone on shift — must not have their location transmitted just
 *      because they plugged their phone into a car. PIPEDA data minimisation is
 *      explicit that every field is tied to a stated purpose, and "draw a map for
 *      the person holding the phone" does not justify egress.
 *
 * So this handler makes NO network call of any kind. It publishes to
 * carFixChannel, which updates the in-memory marker and the device-local
 * `spinr_driver_last_location` cache. Nothing leaves the device, and nothing
 * here touches `is_online`, so no insurance-period transition is implied: an
 * offline driver watching this map stays in Period 0.
 *
 * ─── One service, never two ─────────────────────────────────────────────────
 * expo-location mints a separate LocationTaskService instance per task name
 * (`LocationTaskService.kt`: `mServiceId = sServiceId++`, channel `appId:taskName`),
 * so running this alongside `spinr-background-location` would put TWO permanent
 * Spinr notifications in the driver's shade. It therefore refuses to start while
 * that one is running — and in that case it isn't needed anyway, because that
 * task publishes to the same channel.
 */
import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';
import { recordNonFatal } from '../../utils/crashlytics';
import { checkLocationIntegrity } from '../../utils/locationIntegrity';
import {
  FOREGROUND_NOTIFICATION_COLOR,
  isBackgroundLocationRunning,
  isSessionEnded,
} from '../../utils/backgroundLocation';
import { publishCarFix } from './carFixChannel';

export const CAR_LOCATION_TASK = 'spinr-car-location';

type CarLocationTaskData = { locations: Location.LocationObject[] };

/**
 * Why a driver's marker is or isn't live, for the debug fact and the logs.
 * `piggyback` is a success, not a failure — the online driver's existing service
 * is already feeding the same channel.
 */
export type CarLocationStart =
  /** Foreground service running — the good case. Notification visible. */
  | 'started'
  /** Registered WITHOUT a foreground service, because Android refused one. */
  | 'started-no-notification'
  | 'already-running'
  | 'piggyback'
  | 'no-permission'
  | 'session-ended'
  /** Android refused the foreground service AND the fallback also failed. */
  | 'fgs-refused'
  | 'unavailable';

/**
 * Whether a thrown error is Android refusing a background foreground-service start.
 *
 * expo-location raises this from `LocationModule.kt:327` whenever
 * `AppForegroundedSingleton.isForegrounded` is false — and that singleton is set
 * ONLY by Activity lifecycle hooks (`LocationModule.kt:374-380`). An Android Auto
 * car-only launch creates no Activity, so on the exact path this module exists
 * for, the refusal is not an edge case: it is the guaranteed outcome.
 *
 * Matched on the derived code AND the message text, because the code string is
 * generated by expo-modules from the Kotlin class name and is not part of any
 * public contract we can pin.
 */
function isForegroundServiceRefusal(e: unknown): boolean {
  const err = e as { code?: unknown; message?: unknown };
  const code = String(err?.code ?? '');
  const message = String(err?.message ?? '');
  if (/FOREGROUND_SERVICE_START_NOT_ALLOWED/i.test(code)) return true;
  return /foreground service/i.test(message) && /background/i.test(message);
}

/**
 * One report per process, not per attempt. `startCarLocationService` is called on
 * every connect AND on carSession's 60s tick, so an unguarded report would emit
 * ~60 Crashlytics events per driver per hour of driving.
 */
let refusalReported = false;

/** @internal Test-only. */
export function _resetCarLocationTelemetry(): void {
  refusalReported = false;
}

export async function handleCarLocationTask({
  data,
  error,
}: {
  data?: CarLocationTaskData;
  error?: { message?: string } | null;
}): Promise<void> {
  if (error) {
    // No Sentry: this fires on transient sensor loss (tunnel, garage) and would
    // be pure noise. The marker simply holds its last position.
    console.warn('[CarLocation] task error:', error.message);
    return;
  }
  const locations = data?.locations ?? [];
  // Only the newest sample matters. This drives a map marker, not a route
  // history — replaying a deferred batch would rewind the marker across
  // positions the driver has already left.
  const latest = locations[locations.length - 1];
  if (!latest?.coords) return;

  // Same trust gate as the dispatch watcher. Display-only or not, a mock-location
  // app should not be able to drive where Spinr says the driver is — including in
  // the shared last-location cache that the phone dashboard reads back.
  const integrity = checkLocationIntegrity(latest);
  if (!integrity.trusted) {
    console.warn(`[CarLocation] dropped untrusted sample: ${integrity.reason}`);
    return;
  }

  publishCarFix({
    latitude: latest.coords.latitude,
    longitude: latest.coords.longitude,
    heading: latest.coords.heading ?? null,
  });
}

TaskManager.defineTask<CarLocationTaskData>(CAR_LOCATION_TASK, handleCarLocationTask);

/**
 * Start the display-only service. Safe to call repeatedly; never throws.
 *
 * Deliberately silent about failure at the call site — every negative outcome
 * leaves the driver exactly where they were before (the in-hook foreground
 * watcher plus its staleness watchdog), which is today's behaviour. Losing the
 * upgrade is not worth an alert on a screen someone is driving in front of.
 */
/**
 * The location request itself. Shared by both start modes so the ONLY difference
 * between them is the `foregroundService` block — nothing about accuracy or
 * cadence silently changes when we fall back.
 */
const BASE_OPTIONS: Location.LocationTaskOptions = {
  // Matches the car surface's own watcher: High because Balanced can fall
  // back to network positioning, which carries no bearing — and without a
  // bearing the car marker has nothing to rotate to.
  accuracy: Location.Accuracy.High,
  timeInterval: 2_000,
  distanceInterval: 5,
  // No deferredUpdatesInterval: batching is for upload efficiency, and there
  // is no upload here. A marker wants each fix as it lands.
  pausesUpdatesAutomatically: false,
  activityType: Location.ActivityType.AutomotiveNavigation,
  showsBackgroundLocationIndicator: true,
};

const FOREGROUND_SERVICE_OPTIONS: Location.LocationTaskOptions = {
  ...BASE_OPTIONS,
  foregroundService: {
    notificationTitle: 'Spinr',
    notificationBody: 'Showing your location on the car screen',
    notificationColor: FOREGROUND_NOTIFICATION_COLOR,
    // The car screen is gone once the app is; so is the reason for this.
    killServiceOnDestroy: true,
  },
};

/**
 * How the task is currently registered, so the 60s re-assert can tell
 * "nothing to do" from "running, but degraded and worth upgrading".
 */
let currentMode: 'none' | 'foreground-service' | 'no-notification' = 'none';

/** @internal Test-only. */
export function _carLocationMode(): typeof currentMode {
  return currentMode;
}

/**
 * Start the display-only service. Safe to call repeatedly; never throws.
 *
 * Deliberately silent about failure at the call site — every negative outcome
 * leaves the driver exactly where they were before (the in-hook foreground
 * watcher plus its staleness watchdog), which is today's behaviour. Losing the
 * upgrade is not worth an alert on a screen someone is driving in front of.
 */
export async function startCarLocationService(): Promise<CarLocationStart> {
  try {
    // A signed-out device must not run a location service at all, for any reason.
    if (await isSessionEnded()) return 'session-ended';

    const alreadyRunning = await Location.hasStartedLocationUpdatesAsync(CAR_LOCATION_TASK);
    // Running WITH a notification is finished business. Running without one is
    // not: Android refuses a background foreground-service start, but it stops
    // refusing the moment the phone app is foregrounded, so every re-assert is
    // a chance to upgrade. startLocationUpdatesAsync on a live task replaces its
    // options in place (same mechanism updateBackgroundLocationCadence relies
    // on), so the upgrade needs no stop/start and never drops a fix.
    if (alreadyRunning && currentMode !== 'no-notification') return 'already-running';

    // The online driver's dispatch service is already up and already publishing
    // to carFixChannel — a second service would only add a second notification.
    if (await isBackgroundLocationRunning()) return 'piggyback';

    // NEVER request. See the file header.
    const { status } = await Location.getBackgroundPermissionsAsync();
    if (status !== 'granted') return 'no-permission';

    try {
      await Location.startLocationUpdatesAsync(CAR_LOCATION_TASK, FOREGROUND_SERVICE_OPTIONS);
      currentMode = 'foreground-service';
      return 'started';
    } catch (e) {
      if (!isForegroundServiceRefusal(e)) throw e;

      // The expected outcome on a car-only launch — see isForegroundServiceRefusal.
      //
      // Register the SAME task without the foregroundService block instead of
      // giving up. expo-location only throws when that block is present
      // (LocationModule.kt:327), and the consumer still calls
      // requestLocationUpdates either way — only maybeStartForegroundService is
      // gated. So this yields a live task with no notification.
      //
      // Whether Android then throttles it depends on our process importance
      // while Android Auto has our CarAppService bound, which is not knowable
      // from source. That is exactly what the fix-rate telemetry in carSession
      // measures. Worst case it is throttled and we are no worse off than
      // before this module existed; best case the marker is live and the driver
      // never sees a notification at all.
      if (!refusalReported) {
        refusalReported = true;
        recordNonFatal(e, {
          domain: 'drivers',
          module: 'androidAuto',
          reason: 'foreground_service_start_refused',
        });
      }
      try {
        await Location.startLocationUpdatesAsync(CAR_LOCATION_TASK, BASE_OPTIONS);
        currentMode = 'no-notification';
        console.warn('[CarLocation] foreground service refused — running without a notification');
        return 'started-no-notification';
      } catch (fallbackError) {
        console.warn('[CarLocation] fallback registration also failed:', fallbackError);
        return 'fgs-refused';
      }
    }
  } catch (e) {
    // Anything else — permission revoked mid-call, native module absent.
    console.warn('[CarLocation] could not start display service:', e);
    return 'unavailable';
  }
}

/**
 * Stop it. Unconditional and silent — `stopLocationUpdatesAsync` throws when the
 * task was never started, which is the normal case on most disconnects.
 */
export async function stopCarLocationService(): Promise<void> {
  currentMode = 'none';
  try {
    await Location.stopLocationUpdatesAsync(CAR_LOCATION_TASK);
    console.log('[CarLocation] display service stopped');
  } catch {
    // Not running — nothing to do.
  }
}
