import React, { useEffect, useRef, useState } from 'react';
import { View, Image, Platform } from 'react-native';
import { AnimatedRegion, Marker } from 'react-native-maps';

import {
    CarMarkerVariant,
    resolveCarMarkerVariant,
    VARIANT_SIZE_FACTOR,
} from './carMarkerVariant';

interface CarMarkerProps {
    coordinate: {
        latitude: number;
        longitude: number;
    };
    heading?: number | null;
    /**
     * Vehicle type NAME (e.g. from `vehicle_types.name` / estimate
     * `vehicle_type.name`) used to pick the marker art. Free-form — it is
     * keyword-matched via `resolveCarMarkerVariant`. Omit for the default
     * sedan.
     */
    vehicleType?: string | null;
    size?: number;
    zIndex?: number;
    identifier?: string;
}

export type { CarMarkerVariant } from './carMarkerVariant';
export { resolveCarMarkerVariant } from './carMarkerVariant';

// Metro needs static require() calls, so each variant is listed explicitly.
const CAR_MARKER_IMAGES: Record<CarMarkerVariant, ReturnType<typeof require>> = {
    sedan: require('../assets/car_marker_sedan.png'),
    suv: require('../assets/car_marker_suv.png'),
    lux: require('../assets/car_marker_lux.png'),
};

// Position updates arrive every ~3-10 s (WS pings / GPS watch). Glide the car
// between fixes over the observed gap so it moves like Uber/Lyft instead of
// teleporting, but clamp so a delayed ping doesn't produce a minutes-long crawl.
const MIN_ANIM_MS = 300;
const MAX_ANIM_MS = 3000;
// Beyond this jump (stale fix after backgrounding, ride handoff) snap instantly —
// gliding across half the city looks worse than a jump.
const SNAP_DISTANCE_M = 500;
// Ignore sub-3m jitter when deriving the fallback bearing from movement.
const MIN_BEARING_MOVE_M = 3;

function distanceMeters(lat1: number, lng1: number, lat2: number, lng2: number): number {
    const R = 6371000;
    const toRad = (d: number) => (d * Math.PI) / 180;
    const dLat = toRad(lat2 - lat1);
    const dLng = toRad(lng2 - lng1);
    const a =
        Math.sin(dLat / 2) ** 2 +
        Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
    return 2 * R * Math.asin(Math.sqrt(a));
}

function bearingDegrees(lat1: number, lng1: number, lat2: number, lng2: number): number {
    const toRad = (d: number) => (d * Math.PI) / 180;
    const dLng = toRad(lng2 - lng1);
    const y = Math.sin(dLng) * Math.cos(toRad(lat2));
    const x =
        Math.cos(toRad(lat1)) * Math.sin(toRad(lat2)) -
        Math.sin(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.cos(dLng);
    return ((Math.atan2(y, x) * 180) / Math.PI + 360) % 360;
}

/**
 * Top-down car marker using the transparent PNGs from shared/assets.
 *
 * Vehicle classes: `vehicleType` (a vehicle_types.name) picks one of three
 * art variants — white sedan (default), boxy SUV with roof rails, or black
 * lux car — generated by shared/assets/generate_car_markers.py.
 *
 * Renders the car image via a child <View><Image/></View> (not the native
 * `image` prop) so `size` controls the rendered dimensions — the native
 * prop renders at the PNG's physical size which is far too large.
 *
 * Transparent backgrounds are set on every wrapper layer (and on the Marker
 * itself) to kill the default Android callout-style bubble that
 * react-native-maps otherwise draws around custom child views.
 *
 * Snapshot lifecycle: `tracksViewChanges` stays true until the car PNG has
 * actually decoded (Image onLoad) plus a short settle delay, then flips false
 * for perf. The previous fixed 800 ms timer raced slow image decodes (cold
 * start, low-end Android, map remounts) and could permanently snapshot an
 * empty view — an invisible car. A hard cap stops per-frame re-snapshots if
 * onLoad never fires; a late onLoad re-arms one final snapshot.
 *
 * Movement: position changes animate (AnimatedRegion timing on iOS,
 * animateMarkerToCoordinate on Android) so the car glides between GPS fixes.
 * When `heading` is missing/invalid (expo-location reports -1 standing still)
 * the car keeps its last bearing derived from the direction of travel.
 */
const CarMarkerComponent: React.FC<CarMarkerProps> = ({
    coordinate,
    heading,
    vehicleType,
    size = 40,
    zIndex = 1,
    identifier,
}) => {
    const variant = resolveCarMarkerVariant(vehicleType);
    const renderSize = Math.round(size * VARIANT_SIZE_FACTOR[variant]);
    const markerRef = useRef<any>(null);
    const animatedRegion = useRef(
        new AnimatedRegion({
            latitude: coordinate.latitude,
            longitude: coordinate.longitude,
            latitudeDelta: 0,
            longitudeDelta: 0,
        }),
    ).current;
    const prevCoordRef = useRef(coordinate);
    const lastFixTsRef = useRef(Date.now());

    // Last known direction of travel — used when the GPS heading is absent.
    const [travelBearing, setTravelBearing] = useState(0);

    useEffect(() => {
        const prev = prevCoordRef.current;
        if (
            prev.latitude === coordinate.latitude &&
            prev.longitude === coordinate.longitude
        ) {
            return;
        }
        const now = Date.now();
        const movedM = distanceMeters(
            prev.latitude, prev.longitude,
            coordinate.latitude, coordinate.longitude,
        );
        const duration =
            movedM > SNAP_DISTANCE_M
                ? 1
                : Math.min(Math.max(now - lastFixTsRef.current, MIN_ANIM_MS), MAX_ANIM_MS);
        prevCoordRef.current = coordinate;
        lastFixTsRef.current = now;

        if (movedM >= MIN_BEARING_MOVE_M) {
            setTravelBearing(
                bearingDegrees(prev.latitude, prev.longitude, coordinate.latitude, coordinate.longitude),
            );
        }

        if (Platform.OS === 'android') {
            const node = markerRef.current?.getNode?.() ?? markerRef.current;
            node?.animateMarkerToCoordinate?.(coordinate, duration);
        } else {
            animatedRegion
                .timing({
                    latitude: coordinate.latitude,
                    longitude: coordinate.longitude,
                    duration,
                    useNativeDriver: false,
                } as any)
                .start();
        }
        // animatedRegion is a stable ref.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [coordinate.latitude, coordinate.longitude]);

    // expo-location uses -1 for "heading unknown"; treat any negative or null
    // value as missing and fall back to the direction of travel.
    const rotation =
        heading != null && Number.isFinite(heading) && heading >= 0 ? heading : travelBearing;

    const [tracksViewChanges, setTracksViewChanges] = useState(true);
    const settleTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    useEffect(() => {
        // Hard cap: never re-snapshot indefinitely even if onLoad is lost.
        const cap = setTimeout(() => setTracksViewChanges(false), 5000);
        return () => {
            clearTimeout(cap);
            if (settleTimerRef.current) clearTimeout(settleTimerRef.current);
        };
    }, []);
    const handleImageLoaded = () => {
        // Image bitmap is decoded — keep tracking through one more frame so the
        // native Marker snapshot contains the car, then stop for perf.
        setTracksViewChanges(true);
        if (settleTimerRef.current) clearTimeout(settleTimerRef.current);
        settleTimerRef.current = setTimeout(() => setTracksViewChanges(false), 350);
    };

    return (
        <Marker.Animated
            ref={markerRef}
            coordinate={animatedRegion as any}
            anchor={{ x: 0.5, y: 0.5 }}
            flat
            rotation={rotation}
            tracksViewChanges={tracksViewChanges}
            zIndex={zIndex}
            identifier={identifier}
            style={{ backgroundColor: 'transparent' }}
        >
            <View
                style={{
                    width: renderSize,
                    height: renderSize,
                    backgroundColor: 'transparent',
                    alignItems: 'center',
                    justifyContent: 'center',
                }}
            >
                {/* A late vehicleType (data arriving after the snapshot froze)
                    swaps the source; the new image's onLoad re-arms one final
                    snapshot via handleImageLoaded, so the swap still paints. */}
                <Image
                    source={CAR_MARKER_IMAGES[variant]}
                    onLoad={handleImageLoaded}
                    style={{
                        width: renderSize,
                        height: renderSize,
                        resizeMode: 'contain',
                        backgroundColor: 'transparent',
                    }}
                />
            </View>
        </Marker.Animated>
    );
};

function _propsAreEqual(prev: CarMarkerProps, next: CarMarkerProps): boolean {
    return (
        prev.coordinate.latitude === next.coordinate.latitude &&
        prev.coordinate.longitude === next.coordinate.longitude &&
        prev.heading === next.heading &&
        prev.vehicleType === next.vehicleType &&
        prev.size === next.size &&
        prev.zIndex === next.zIndex &&
        prev.identifier === next.identifier
    );
}

export const CarMarker = React.memo(CarMarkerComponent, _propsAreEqual);

export default CarMarker;
